### ISSUE TITLE
how can i create custom login validation?

### ISSUE THREAD

**Issue by SwapnilAkolkar** [dektrium/yii2-user#1056]
### What steps will reproduce the problem?
I am trying to authenticate user from external mobile app, I have username & password from login form in mobile app, then I wrote function in yii2 ajax call to validate the user. BUt I am not able to find user by username and password.
### What is the expected result?
the function should return user information after validation of input credential username and password. 
### What do you get instead?
I tried to generate password hash but it generates diffrent values diffternt time
### Additional info

| Q                 | A
| ----------------- | ---
| Yii2 version      | 2
| Yii2-user version | latest
| PHP version       |  7.1

**Comment by Webkadabra** [comment]
kick him

**Comment by Webkadabra** [comment]
@SwapnilAkolkar are you on drugs?

**Comment by SwapnilAkolkar** [comment]
Teri maa ka bosses lawade, zar ke baal mother fucker ass hole @webkadabra

**Comment by SwapnilAkolkar** [comment]
No your father may drugs n produce you beti chod teri mala bhosada lavde ke
baal dektrium fucktroum madarchod mother fucker basterd ass hole fuck you
100000 times.. teri gand me dhanda sale tera baap chutiya madarchod

**Comment by SwapnilAkolkar** [comment]
Kick your mother @webkadabra

**Comment by Webkadabra** [comment]
this is gold
