### ISSUE TITLE
Add time zone to user profile

### ISSUE THREAD

**Issue by simonmesmith** [dektrium/yii2-user#164]
Currently, users can specify their location in their profile settings. A common use case is also for the user to be able to specify their timezone. We can then write a function to convert UTC timestamps to the user's local time. Are there plans for this on the roadmap (a search does not reveal any)? I would see this as: 

* Add timezone column in profile table
* Add timezone dropdown list in profile settings view
* Store selected timezone upon profile save
* Ideally add a function to call time for user; something like: Yii::$app->user->toLocalDateTime() with an optional argument that can be passed to convert a specified UTC time, defaulting to the current UTC time if no argument is passed

**Comment by moneyadmin** [comment]
Good idea!

**Comment by cornernote** [comment]
+1 - this would be really nice

**Comment by yarrgh** [comment]
+1 - I would be very interested in this
