### ISSUE TITLE
upload image profile 

### ISSUE THREAD

**Issue by tecnologiaterabyte** [dektrium/yii2-user#174]
Excellent extension works wonders, consult you wanted what would be the best way to upload an image and display it as avatar, additional to that gravatar , so if you have no account gravatar can upload a image system.

**Comment by raoul2000** [comment]
IMHO user profile including avatar management is not generic stuff and should be left to third party module

**Comment by cinghie** [comment]
Hi all,

I developed a small module that extends Yii2 User and puts the ability to insert a picture as an avatar and other fields in the user profile as firstname, lastname, date of birth and terms.

The module is under on development but works fine

**Comment by dmeroff** [comment]
Closed because of #755.
New issue created [here](https://github.com/dektrium/yii2-profile/issues/1)
