### ISSUE TITLE
Overriding models

### ISSUE THREAD

**Issue by rtwent** [dektrium/yii2-user#212]
User config:
'modules' => [
        'user' => [
            'class' => 'dektrium\user\Module',
            'controllerMap' => [
                'settings' => 'app\controllers\user\SettingsController'
            ],
            'modelMap' => [
                'Profile' => 'app\models\overriding\user\Profile',
            ],
        ],
    ],

In overrided controller I try to find user profile, as You do it in Your base controller:
$model = $this->finder->findProfileById(\Yii::$app->user->identity->getId());
I expect to get instance of "app\models\overriding\user\Profile" but get instance of dektrium\user\models\Profile
Your last update 0.9.0 was to cruel ;) Could You left some features for some time as deprecated. "ModelManager component has been dropped" this made me headache. Regards.

**Comment by trbsi** [comment]
The same here, I'm not sure how to access "finder->findProfileById(\Yii::$app->user->identity->getId());" anywhere from my app

**Comment by dmeroff** [comment]
This was a bug, which I've fixed. Please upgrade.
Before the release 1.0.0, no features will be marked as deprecated, because module is in initial development and it is normal to break bc at this time.
