### ISSUE TITLE
cannot login 

### ISSUE THREAD

**Issue by xdhanz** [dektrium/yii2-user#215]
i have last version of yii2 basic and yii2-user, but i cannot login using username that i had created.

that problem didnot appear in my other website that use old version of yii2-user

**Comment by dmeroff** [comment]
I can not reproduce the issue. Could you please provide more information? What is the error message? Does the error appear to registered or created by admin users?

**Comment by xdhanz** [comment]
there is no error message, after login it just sent back to home  (web/index.php)  without any sign of logged in, then when i try to open  user/admin/index  it return to the login form, 

i use username that i had created by signup using user/registration/register, and confirmed using link in runtime/mail

i had try many times, with this step

1. installl yii2 basic:
    composer create-project --prefer-dist yiisoft/yii2-app-basic basic

2. set database in config/db.php

3. update composer.json to add yii2-user
......
"require": {
        "php": ">=5.4.0",
        "yiisoft/yii2": "*",
        "yiisoft/yii2-bootstrap": "*",
        "yiisoft/yii2-swiftmailer": "*",
        "dektrium/yii2-user": "~0.9.1@dev"
},
....

4.  install yii2-user 
     composer update

5.  add yii2-user to the module in config/web.php
...
    'modules' => [
		'user' => [
			'class' => 'dektrium\user\Module',
			'enableUnconfirmedLogin' => true,
				'confirmWithin' => 21600,
				'cost' => 12,
				'admins' => ['admin','xdhanz']
        ],
        
    ],
...

6. run yii2-user migration
    $ php yii migrate/up --migrationPath=@vendor/dektrium/yii2-user/migrations

7.  open web/?r=user/registration/register
    signup new user  xdhanz

8. open confirmation link in runtime/mail
    
9. open web/?r=user/admin/index and then redirected to login form
 
   if i use  wrong username or wrong password it show the correct messages ("Invalid login or password), if i use the correct user and password (xdhanz), it show no message, just return the login form again.

my other site that run well (version 0.8.2), getting the same problem after i run "composer update"

**Comment by dmeroff** [comment]
Thank you for detailed description of how to reproduce issue. I've found the problem: you should remove `user` component from your config's components section.

``php
        // these lines should be removed
        'user' => [
            'identityClass' => 'app\models\User',
            'enableAutoLogin' => true,
        ],
```

This error occures because Yii2-user no longer update `user` component configuration automatically.

**Comment by xdhanz** [comment]
thank you very much, it worked now

**Comment by victorvirtual** [comment]
dmeroff thank for this solutions from Bolivia

**Comment by gomonkey** [comment]
thank you for the answer, I had the same problem

**Comment by janitov** [comment]
i have last version of yii2 advanced and yii2-user with yii2-rbac , but i cannot login using username that i had created. the problem is the same pointed up there, and I have removed the user component from your config's components section. but but login still does not work.

**Comment by saepulm** [comment]
I had problems with the login form and register that is not running at all, when I made the clouds went well but when I tried to upload it to the server and register the login button both backend and frontend does not work

**Comment by ponc83** [comment]
dmeroff solution worked for me
