### ISSUE TITLE
facebook app

### ISSUE THREAD

**Issue by chetanakambad** [dektrium/yii2-user#219]
i want to develop facebook app.

**Comment by chetanakambad** [comment]
In facebook social login give error:
   - Given URL is not permitted by the application configuration.: One or more of the given URLs is not allowed by the App's settings. It must match the Website URL or Canvas URL, or the domain must be a subdomain of one of the App's domains.
please give me solution.

**Comment by trbsi** [comment]
You have to set up your facebook app and enter urls to allow facebook app to run on those urls. Read more about it in some tutorials
![99](https://cloud.githubusercontent.com/assets/3958715/5602172/60f7c988-933b-11e4-977e-3cdd52df39fb.PNG)

**Comment by chetanakambad** [comment]
app creation complete thanks for that.
Now i want to know that when i am login through facebook after that how can i logout.

**Comment by dmeroff** [comment]
Logout the same way as if you were logged in using login and password. By action `user/security/logout` via POST request.

**Comment by chetanakambad** [comment]
ok thanks

**Comment by chetanakambad** [comment]
i want to send sms to mobile from localhost in yii2,so help me about that.

**Comment by dmeroff** [comment]
@chetanakambad this is not the best place to ask such questions. You should better ask on yii's forum or stackoverflow. Github issues should only be used in order to report bugs or request features. Any questions about module should be asked in google group or gitter chat.

**Comment by chetanakambad** [comment]
ok
