### ISSUE TITLE
Override Class

### ISSUE THREAD

**Issue by abhi1693** [dektrium/yii2-user#221]
I was attempting to override your `User` class with mine. I followed all the steps that you have mentioned in the docs. I get the following error:

    Invalid Configuration – yii\base\InvalidConfigException
    The configuration for the "manager" component must contain a "class" element.

My Config looks like:
    
     ....
     'modules' => [
        'user' => [
            'class' => 'dektrium\user\Module',
            'enableRegistration' => false,
            'enableConfirmation' => true,
            'components' => [
                'manager' => [
                    'userClass' => 'backend\models\user\User'
                ]
            ],
            'mailer' => [
                'sender' => 'library@teamvulcans.com',
                'welcomeSubject' => 'Welcome to Team Vulcans',
                'confirmationSubject' => 'Confirm Account',
                'reconfirmationSubject' => 'Email Change',
                'recoverySubject' => 'Recover Account'
            ]
     ]
    ]
    ....

My new Model class looks like:

    namespace backend\models\user;

    use dektrium\user\helpers\Password;
    use dektrium\user\models\User as BaseUser;
    use yii\log\Logger;
    use Yii;

    class User extends BaseUser
    {
        public function create(){...}
    }

**Comment by trbsi** [comment]
this is new way
https://github.com/dektrium/yii2-user/blob/master/docs/overriding-models.md
