### ISSUE TITLE
Refer to modelMap in createObject

### ISSUE THREAD

**Issue by kalayda** [dektrium/yii2-user#222]
Class name in createObject shold be taken from module's modelMap instead of absolute name.
I.e. not
> \Yii::createObject(User::className())

but
> \Yii::createObject($this->module->getModelMap()['User'])

**Comment by dmeroff** [comment]
No, this is not really needed. `Yii::createObject()` uses DI container to get the class. And in [bootstrap class](https://github.com/dektrium/yii2-user/blob/master/Bootstrap.php#L48) we define classes for DI container.
