### ISSUE TITLE
Overriding Model User.

### ISSUE THREAD

**Issue by tecnologiaterabyte** [dektrium/yii2-user#224]
This morning update, and now is not working relationship that had developed between the user and auth_assignment table to show the role of each user.

User.php:

<?php
namespace common\models;

use dektrium\user\models\User as BaseUser;

class User extends BaseUser
{
    public function getAuth_assignment()
    {
        return $this->hasOne(Auth_assignment::className(), ['user_id' => 'id']);
    }

}

Auth_assignment.php:

<?php

namespace common\models;

use yii\db\ActiveRecord;
use Yii;

class Auth_assignment extends ActiveRecord
{

    public static function tableName()
    {
        return 'auth_assignment';
    }

    public function getUser()
    {
        return $this->hasOne(User::className(), ['user_id' => 'id']);
    }

}

**Comment by dmeroff** [comment]
Please provider error you get. I can't help without knowing what is going wrong.

**Comment by tecnologiaterabyte** [comment]
Atached Error.
![error_01_yii2-user](https://cloud.githubusercontent.com/assets/4957021/5644620/d5cf27f2-9637-11e4-9167-cfa02ef8f3f3.png)

**Comment by dmeroff** [comment]
Strange issue. Are you overriding UserSearch class? If so could you please provide your module config and class source? Also please provide overriden view file source.

**Comment by tecnologiaterabyte** [comment]
![main-local](https://cloud.githubusercontent.com/assets/4957021/5645469/d236b650-9641-11e4-9a52-722845fbf031.png)
![model_user](https://cloud.githubusercontent.com/assets/4957021/5645472/d8197c06-9641-11e4-8036-5ff35ac94bc5.png)

**Comment by dmeroff** [comment]
I suppose I understand the problem. Since `UserSearch` is extended from `dektrium\user\models\User` class it don't know about your new user class. I'll try to fix it asap.

**Comment by tecnologiaterabyte** [comment]
if I imagine that as if I add in your model use working fine.

Atach Code:

![model_dektrium_user](https://cloud.githubusercontent.com/assets/4957021/5645690/251c9ee0-9645-11e4-8d44-91bcb39e9868.png)
![fine](https://cloud.githubusercontent.com/assets/4957021/5645697/3eef9070-9645-11e4-8959-fe783d0dff90.png)

**Comment by dmeroff** [comment]
Please, try if it is working now?
