### ISSUE TITLE
Error after update to 9.0+

### ISSUE THREAD

**Issue by stepanorda** [dektrium/yii2-user#225]
After update I get error "The configuration for the "manager" component must contain a "class" element." It works fine on 0.8.2

**Comment by jsobers1331** [comment]
Check out this link to the issue I had which sounds similar to what you have here.
https://github.com/dektrium/yii2-user/issues/210

See if you made the same misunderstanding as I did.

If not, place a screenshot of the config file which you are updating based on author guidelines.

**Comment by stepanorda** [comment]
```json
 'modules' => [ 
'user' => [
            'class' => 'dektrium\user\Module',
            'enableUnconfirmedLogin' => true,
            'confirmWithin' => 21600,
            'cost' => 12,
            'admins' => ['render'],
            'rememberFor' => 60 * 60 * 24 * 30 * 12,
            'components' => [
                'manager' => [
                    'userClass' => 'app\models\Users',
                    'loginFormClass' => 'app\models\LoginForm',
                ],
            ],
        ],
]
```

**Comment by dmeroff** [comment]
You have used outdated documentation. New guide is located [here](https://github.com/dektrium/yii2-user/blob/master/docs/overriding-models.md). You can also check out [UPGRADE.md](https://github.com/dektrium/yii2-user/blob/master/docs/overriding-models.md) to see what has been changed in 0.9.0.

**Comment by anders-akero** [comment]
Hi. Can you please say exactly what changes you did to get it to work?
I have the same problem after updating and I don't understand what has changed.
I'm pretty sure I need to add 'class' => 'something' to:
'user' => [
    'components' => [
        'manager' => [
But what?

**Comment by stepanorda** [comment]
user' => [
    'class' => 'dektrium\user\Module',
    'modelMap' => [
        'User' => 'app\models\User',
    ],
],

**Comment by anders-akero** [comment]
I still cant get it to work.
Exactly same error as before.
The configuration for the "manager" component must contain a "class" element.

    'modules' => [
        'v1' => [
            'class' => 'app\api\v1\Module',
        ],
        'user' => [
            'class' => 'dektrium\user\Module',
            'modelMap' => [// NOTE! This is the new I added from your comment
                'User' => 'app\models\User',// NOTE! This is the new I added from your comment
            ],// NOTE! This is the new I added from your comment
            'enableRegistration' => false,
            'enableGeneratingPassword' => false,
            'enablePasswordRecovery' => true,
            'enableConfirmation' => true,
            'enableUnconfirmedLogin' => false,
            'emailChangeStrategy' => dektrium\user\Module::STRATEGY_SECURE,
            'confirmWithin' => 3600 * 6,
            'rememberFor' => 3600 * 0.5,
            'cost' => 10, // used by Blowfish hash algoritm
            'urlPrefix' => 'user',
            'urlRules' => [],
            'controllerMap' => [
                'admin' => 'app\controllers\user\AdminController',
                'profile' => 'app\controllers\user\ProfileController',
                'registration' => 'app\controllers\user\RegistrationController',
                'settings' => 'app\controllers\user\SettingsController',
                'site' => 'app\controllers\SiteController',
            ],
            'mailer' => [
                'sender' => $params['email']['noReply'],
            ],
            'components' => [
                'manager' => [
                    'userClass' => 'app\models\User',
                    'tokenClass' => 'app\models\Token',
                    'profileClass' => 'app\models\Profile',
                    'accountClass' => 'dektrium\user\models\Account',
                    // Model that is used on user search on admin pages
                    'userSearchClass' => 'dektrium\user\models\UserSearch',
                    // Model that is used on registration
                    'registrationFormClass' => 'app\models\RegistrationForm',
                    // Model that is used on settings
                    'settingsFormClass' => 'app\models\SettingsForm',
                    // Model that is used on resending confirmation messages
                    'resendFormClass' => 'dektrium\user\models\ResendForm',
                    // Model that is used on logging in
                    'loginFormClass' => 'app\models\LoginForm',
                    // Model that is used on password recovery
                    'recoveryRequestFormClass' => 'dektrium\user\models\RecoveryForm',
                    // Model that is used on requesting password recovery
                    'recoveryRequestFormClass' => 'dektrium\user\models\RecoveryRequestForm',
                ],
            ],
            'admins' => [
                '',
            ],
        ],

**Comment by stepanorda** [comment]
You need to move everything from  'components' => [
            'manager' => [
to 
'modelMap' => [
syntax has changed

**Comment by dmeroff** [comment]
@stepanorda is correct. But, @anders-akero, have you checked out [upgrade instructions](https://github.com/dektrium/yii2-user/blob/master/UPGRADE.md) before asking this questions? It is clearly described there how you should adjust your config after upgrade from 0.8.*.

**Comment by arjenmeijer** [comment]
I would like to defend @anders-akero. The upgrade instruction focus on custom classes. If you did not change anything and just upgrade, it won't work. Even after the instructions above I do not have an idea what I should do to get this software working. Oke, my fault. But I do not understand eveything. I just want it to work. 

It would be nice to have a complete working version as example in the docs.

**Comment by anders-akero** [comment]
Hi.
I read the changelog and the documentation for example of the configuration. I could not find any example of the configuration and that is why I started searching for others with same issue and found this thread. I did not see the file UPGRADE.md for some reason, my mistake there.
I would recommend you to write the last answer from Stepanorda in the upgrade instructions. It was very clear and helpful to me and will be for many others as well I am sure of. In general a very good extension with a great potential. I would however give the advice for the future to write in what users should change in the upgrade instructions and not just write the new syntax.
I failed because I never understood that we had to move from components, I thought it was something new I just had to add.
Finally I would like to say that I am totally aware of that this extension is not in a stable release yet and that upgrading may break things.

In order to help others who may end up here and having the same issue I will show you my configuration after modification to work with version 0.9.2


        'user' => [
            'class' => 'dektrium\user\Module',
            'enableRegistration' => false,
            'enableGeneratingPassword' => false,
            'enablePasswordRecovery' => true,
            'enableConfirmation' => true,
            'enableUnconfirmedLogin' => false,
            'emailChangeStrategy' => dektrium\user\Module::STRATEGY_SECURE,
            'confirmWithin' => 3600 * 6,
            'rememberFor' => 3600 * 0.5,
            'cost' => 10, // used by Blowfish hash algoritm
            'urlPrefix' => 'user',
            'urlRules' => [],
            'controllerMap' => [
                'admin' => 'app\controllers\user\AdminController',
                'profile' => 'app\controllers\user\ProfileController',
                'registration' => 'app\controllers\user\RegistrationController',
                'settings' => 'app\controllers\user\SettingsController',
                'site' => 'app\controllers\SiteController',
            ],
            'modelMap' => [
                'User' => 'app\models\User',
                // Active record classes
                'userClass' => 'app\models\User',
                'tokenClass' => 'app\models\Token',
                'profileClass' => 'app\models\Profile',
                'accountClass' => 'dektrium\user\models\Account',
                // Model that is used on user search on admin pages
                'userSearchClass' => 'dektrium\user\models\UserSearch',
                // Model that is used on registration
                'registrationFormClass' => 'app\models\RegistrationForm',
                // Model that is used on settings
                'settingsFormClass' => 'app\models\SettingsForm',
                // Model that is used on resending confirmation messages
                'resendFormClass' => 'dektrium\user\models\ResendForm',
                // Model that is used on logging in
                'loginFormClass' => 'app\models\LoginForm',
                // Model that is used on password recovery
                'recoveryRequestFormClass' => 'dektrium\user\models\RecoveryForm',
                // Model that is used on requesting password recovery
                'recoveryRequestFormClass' => 'dektrium\user\models\RecoveryRequestForm',
            ],
            'mailer' => [
                'sender' => $params['email']['noReply'],
            ],
            'admins' => [
            ],
        ],

**Comment by dmeroff** [comment]
@anders-akero @arjenmeijer I'm agree with you, upgrade instructions may be a little bit confusing. I'll update them as soon as possible.

**Comment by withoutfx** [comment]
actually im using this in common config area:
user' => [
'class' => 'dektrium\user\Module',
'modelMap' => [
'User' => 'app\models\User',
],
],

but, afterthat all the capcha image is broken only when i try to ovrride User Model.
