### ISSUE TITLE
Overriding Model No Working.

### ISSUE THREAD

**Issue by tecnologiaterabyte** [dektrium/yii2-user#226]
Hi Overriding Model not working correctly RegistrationForm extend the model to add the captcha no longer works.

RegistrationForm.php:

<?php

namespace common\models;

use dektrium\user\models\RegistrationForm as BaseRegistrationForm;

class RegistrationForm extends BaseRegistrationForm
{
    /**
     * @var string
     */
    public $captcha;
    /**
     * @inheritdoc
     */
    public function rules()
    {
        $rules = parent::rules();
        $rules[] = ['captcha', 'required'];
        $rules[] = ['captcha', 'captcha'];
        return $rules;
    }
}

Config:

            'modelMap' => [
                'RegistrationForm' => 'common\models\RegistrationForm'
            ],

**Comment by dmeroff** [comment]
Please provider error you get. I can't help without knowing what is going wrong.

**Comment by tecnologiaterabyte** [comment]
Atached image, produces no mistake just not showing captcha.
![error_02_yii2-user](https://cloud.githubusercontent.com/assets/4957021/5644665/688954fa-9638-11e4-94af-11160e124d87.png)

**Comment by dmeroff** [comment]
I've just re-checked this guide and found only one mystake. It has been fixed. Please update your view file accordingly to provided in guide.
Concerning your issue, have you updated view application component configuration as said in guide? Seems that you are not overriding view file properly.

**Comment by tecnologiaterabyte** [comment]
Atach Config:

main.local.php:

<?php

$config = [
    'language' => 'es',
    'homeUrl' => '/',
    'modules' => [
        'user' => [
            'class' => 'dektrium\user\Module',
            'modelMap' => [
                'User'    => 'common\models\UserCommon',
                'Profile' => 'common\models\Profile',
                'LoginForm' => 'common\models\LoginCommon',
                'RegistrationForm' => 'common\models\RegistrationForm'
            ],
            'controllerMap' => [
                'security' => 'common\controllers\SecurityController',
                'recovery' => 'common\controllers\RecoveryController'
            ],
            'enableRegistration' => true,
            'enableUnconfirmedLogin' => true,
            'confirmWithin' => 21600,
            'cost' => 12,
            'admins' => ['admin']
        ],
    ],
    'components' => [
        // Configuración Usuarios Frontend //
        'user' => [
            'loginUrl' => ['/user/security/login'],
            'identityCookie' => [
                'name' => '_frontendIdentity',
                'path' => '/',
                'httpOnly' => true,
            ],
        ],
        // Configuración Cookies y Nombre Url Frontend //
        'request' => [
            // !!! insert a secret key in the following (if it is empty) - this is required by cookie validation
            'baseUrl' => '',
            'enableCookieValidation' => true,
            'cookieValidationKey' => 'CJgSi54GiLAYtQ6r6p486KGgeis3ycSf',
            'csrfParam' => '_frontendCSRF',
            'csrfCookie' => [
                'httpOnly' => true,
                'path' => '/',
            ],
        ],
        // Theme Backend AdminLTE //
        'view' => [
            'theme' => [
                'pathMap' => [
                    '@frontend/views/layouts' => '@frontend/web/themes/modernbusiness/views/layouts',
                    '@frontend/views/site' => '@frontend/web/themes/modernbusiness/views/site',
                    '@dektrium/user/views/recovery' => '@frontend/web/themes/modernbusiness/views/recovery',
                    '@dektrium/user/views/registration' => '@frontend/web/themes/modernbusiness/views/registration',
                    '@dektrium/user/views/security' => '@frontend/web/themes/modernbusiness/views/security',
                    '@dektrium/user/views/settings' => '@frontend/web/themes/modernbusiness/views/settings',
                ],
            ],
        ],
        // Configuración Session Frontend //
        'session' => [
            'name' => 'FRONTENDSESSID',
            'cookieParams' => [
                'path' => '/',
            ],
        ],
    ],
];

// Configuración Gii y Barra Debug Frontend //
if (!YII_ENV_TEST) {
    // configuration adjustments for 'dev' environment
    $config['bootstrap'][] = 'debug';
    $config['modules']['debug']['class'] = 'yii\debug\Module';
    $config['modules']['debug']['allowedIPs'] = ['200.8.244.189'];

    $config['bootstrap'][] = 'gii';
    $config['modules']['gii'] = [
        'class' => 'yii\gii\Module',
        'allowedIPs' => ['200.8.244.189'],
    ];
}

return $config;

RegistrationForm.php:

<?php

namespace common\models;

use dektrium\user\models\RegistrationForm as BaseRegistrationForm;

class RegistrationForm extends BaseRegistrationForm
{
    /**
     * @var string
     */
    public $captcha;
    /**
     * @inheritdoc
     */
    public function rules()
    {
        $rules = parent::rules();
        $rules[] = ['captcha', 'required'];
        $rules[] = ['captcha', 'captcha'];
        return $rules;
    }
}

Register.php:

<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use yii\captcha\Captcha;

/**
 * @var yii\web\View $this
 * @var yii\widgets\ActiveForm $form
 * @var app\models\RegistrationForm $model
 */
$this->title = Yii::t('user', 'Sign up');
$this->params['breadcrumbs'][] = $this->title;

?>
<div class="row">
    <div class="col-md-4 col-md-offset-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><?= Html::encode($this->title) ?></h3>
            </div>
            <div class="panel-body">
                <?php $form = ActiveForm::begin([
                    'id' => 'registration-form',
                ]); ?>

                <?= $form->field($model, 'username') ?>

                <?= $form->field($model, 'email') ?>

                <?= $form->field($model, 'password')->passwordInput() ?>

                <?= $form->field($model, 'captcha')->widget(Captcha::className(), ['captchaAction' => '/site/captcha']) ?>

                <?= Html::submitButton(Yii::t('user', 'Sign up'), ['class' => 'btn btn-success btn-block']) ?>

                <?php ActiveForm::end(); ?>
            </div>
        </div>
        <p class="text-center">
            <?= Html::a(Yii::t('user', 'Already registered? Sign in!'), ['/user/security/login']) ?>
        </p>
    </div>
</div>

SiteController:

    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
            ],
        ];
    }

Its Work in Yii2-User 0.8.2 No Working in Yii-2-User-0.9.2

**Comment by tecnologiaterabyte** [comment]
Ready solved problem, clear cache.

**Comment by JPRusaki** [comment]
I have the same problem, here's my code:

config:

`'user' => [
            // commented params have def values
            'class' => 'dektrium\user\Module',
            'modelMap' => [
                'RegistrationForm' => 'app\models\RegistrationForm',
                'User' => 'app\models\User',
                'Token' => 'app\models\Token'
            ],`

app\models\RegistrationForm.php

`<?php

namespace app\models;

use dektrium\user\models\RegistrationForm as BaseRegistrationForm;
use dektrium\user\models\User;

class RegistrationForm extends BaseRegistrationForm
{
    public function register()
    {
        if (!$this->validate()) {
            return false;
        }

        /** @var User $user */
        $user = Yii::createObject(User::className());
        $user->setScenario('register');
        $this->loadAttributes($user);

        if (!$user->register($pers_val_url)) {
            return false;
        }

        Yii::$app->session->setFlash(
            'info',
            Yii::t('user', 'Your account has been created and a message with further instructions has been sent to your email')
        );

        return true;
    }
}
`
