### ISSUE TITLE
Method Override Problem

### ISSUE THREAD

**Issue by abhi1693** [dektrium/yii2-user#227]
I have overridden your User class. All the functions in my custom class works fine except the getIsAdmin(). It shows that it is overridden but doesn't actually works. What could be causing such an error?

If I write my code in your method, it works but it doesn't work with my class.

**Comment by abhi1693** [comment]
![image](https://cloud.githubusercontent.com/assets/5083532/5646504/1c480ed6-96a3-11e4-80c0-512fa1fae92c.png)

![image](https://cloud.githubusercontent.com/assets/5083532/5646513/39d92746-96a3-11e4-964a-64dd74517447.png)

<?php

namespace backend\models\user;

use cakebake\actionlog\model\ActionLog;
use dektrium\user\helpers\Password;
use dektrium\user\models\Token;
use dektrium\user\models\User as BaseUser;
use yii\behaviors\TimestampBehavior;
use yii\log\Logger;
use Yii;

/**
 * User ActiveRecord model.
 *
 * @author Abhimanyu Saharan <abhimanyu@teamvulcans.com>
 */
class User extends BaseUser
{
    const ROLE_CREATOR = 'Creator';
    const ROLE_SUPER_ADMIN = 'Super Admin';
    const ROLE_ADMIN = 'Admin';

    /** @inheritdoc */
    public function behaviors()
    {
        return [
            TimestampBehavior::className(),
        ];
    }

    /** @inheritdoc */
    public function scenarios()
    {
        return [
            'connect' => ['username', 'email'],
            'create' => ['username', 'email'],
            'update' => ['username', 'email', 'password'],
            'settings' => ['username', 'email', 'password']
        ];
    }

    /** @inheritdoc */
    public function rules()
    {
        return [
            // username rules
            ['username', 'required', 'on' => ['connect', 'create', 'update']],
            ['username', 'match', 'pattern' => '/^[a-zA-Z0-9]\w+$/'],
            ['username', 'string', 'min' => 3, 'max' => 25],
            ['username', 'unique'],
            ['username', 'trim'],

            // email rules
            ['email', 'required', 'on' => ['connect', 'create', 'update']],
            ['email', 'email'],
            ['email', 'string', 'max' => 255],
            ['email', 'unique'],
            ['email', 'trim'],

            // password rules
            ['password', 'string', 'min' => 6, 'on' => ['create']],

            // role rules
            ['role', 'in', 'range' => [self::ROLE_CREATOR, self::ROLE_SUPER_ADMIN]]
        ];
    }

    /**
     * This method is used to create new user account.  After saving user to database, this method
     * uses mailer component to send confirmation to user via email.
     *
     * @throws \RuntimeException
     * @return bool
     */
    public function create()
    {
        if ($this->getIsNewRecord() == false) {
            throw new \RuntimeException('Calling "' . __CLASS__ . '::' . __METHOD__ . '" on existing user');
        }

        $this->trigger(self::USER_CREATE_INIT);

        if ($this->save()) {
            $this->trigger(self::USER_CREATE_DONE);
            $token = Yii::createObject([
                'class' => Token::className(),
                'type' => Token::TYPE_CONFIRMATION
            ]);
            $token->link('user', $this);
            $this->mailer->sendConfirmationMessage($this, $token);

            Yii::$app->session->setFlash('info', 'Confirmation mail has been sent');
            Yii::getLogger()->log('User has been created', Logger::LEVEL_INFO);

            ActionLog::add(ActionLog::LOG_STATUS_SUCCESS, 'Created user: ' . $this->username);

            return true;
        }

        Yii::getLogger()->log('An error occurred while creating account', Logger::LEVEL_ERROR);
        return false;
    }

    /**
     * This method attempts user confirmation. It uses finder to find token with given code and if it is expired
     * or does not exist, this method will throw exception.
     *
     * If confirmation passes it will return true, otherwise it will return false.
     *
     * @param  string $code Confirmation code.
     */
    public function attemptConfirmation($code)
    {
        /** @var Token $token */
        $token = $this->finder->findToken([
            'user_id' => $this->id,
            'code' => $code,
            'type' => Token::TYPE_CONFIRMATION,
        ])->one();

        if ($token === null || $token->isExpired) {
            Yii::$app->session->setFlash('danger', 'Confirmation link is invalid or out-of-date. You can try requesting a new one.');
        }

        $token->delete();

        $this->confirmed_at = time();
        $this->password = Password::generate(8);
        Yii::getLogger()->log('User ' . $this->email . ' has been confirmed', Logger::LEVEL_INFO);

        if ($this->save(false)) {
            if ($this->mailer->sendWelcomeMessage($this)) {
                Yii::$app->session->setFlash('success', 'Awesome, you\'r almost there! Your account credentials have been mailed to you.');
            } else {
                Yii::$app->session->setFlash('danger', 'Something went wrong...Contact Admin asap');
            }
        } else {
            Yii::$app->session->setFlash('danger', 'Something went wrong and your account has not been confirmed.');
        }
    }

    public function getIsAdmin()
    {
        return Yii::$app->authManager->checkAccess($this->getId(), static::ROLE_CREATOR);
    }
}

**Comment by tecnologiaterabyte** [comment]
if you use yii2-admin and rback-db uses the relationship User -> Auth_assignment

For Example:

User.php: (Custom)

    public static function getUseradmin($login)
    {
        $user = UserCommon::findOne(['username' => $login]);
        $auth_assignment = $user ->auth_assignment;
        if (!is_null($auth_assignment)) {
            $auth_assignment = $user->auth_assignment->item_name;
            if ($auth_assignment == "Administrador") {
                return true;
            } else {
                return false;
            }
        } else {
            return false;
        }
    }

    public function getAuth_assignment()
    {
        return $this->hasOne(Auth_assignment::className(), ['user_id' => 'id']);
    }

**Comment by abhi1693** [comment]
I'm using mdmsoft/yii2-admin and there is no UserCommon model.

**Comment by tecnologiaterabyte** [comment]
UserCommon = UserCustom

**Comment by abhi1693** [comment]
This is also giving the same error.

**Comment by abhi1693** [comment]
When I changed the dektrium's User model:

    const ROLE_CREATOR='Creator';
    public function getIsAdmin()
    {
        return Yii::$app->authManager->checkAccess($this->getId(), self::ROLE_CREATOR);
    }

The result:
![image](https://cloud.githubusercontent.com/assets/5083532/5647035/3e2e3a2a-96a8-11e4-8b2e-dbbb74e17235.png)

But when I override it. It gives me the 404 error

**Comment by abhi1693** [comment]
I fail to understand why it is not overriding it?

**Comment by abhi1693** [comment]
Sorry, to trouble you. Finally, I made it work. Thanks for your support
