### ISSUE TITLE
Error on Migration

### ISSUE THREAD

**Issue by escalante308** [dektrium/yii2-user#228]
Hi! I'm trying to apply the migration, but i'm getting this error: 

![sin titulo](https://cloud.githubusercontent.com/assets/10157285/5671157/fd09a2c2-9757-11e4-8682-c6c899feee5a.png)

I'm using Yii2 Advanced Template, with PostgreSQL Database. I've checked the DB connection string in Common/Config/

Thanks in advance!

**Comment by dmeroff** [comment]
Your console application config is wrong. You are setting `db` component not in `components` config section.
