### ISSUE TITLE
Error registration confirm

### ISSUE THREAD

**Issue by Graid2030** [dektrium/yii2-user#229]
> Database Exception – yii\db\Exception

> dektrium\user\models\Token does not have a primary key. You should either define a primary key for the corresponding table or override the primaryKey() method.

**Comment by dmeroff** [comment]
Which module's version are you using? It is already fixed in [master](https://github.com/dektrium/yii2-user/blob/master/models/Token.php#L116)

**Comment by Graid2030** [comment]
In composer
```
             "dektrium/yii2-user": "*"
```
in changelog
> 0.8.2 [14 December 2014]

**Comment by dmeroff** [comment]
Please, use following version in your composer.json and update:
`"dektrium/yii2-user": "0.9.*@dev"`
