### ISSUE TITLE
Improve registration via networks

### ISSUE THREAD

**Issue by dmeroff** [dektrium/yii2-user#232]
At the moment user forced to create new account (enter email and username) after signing in via social network. However we can get that information from data provided by network. If network does not provide email (like twitter) then special form should be shown to user.

**Comment by hiep8024** [comment]
dmeroff,
I heard that Twitter had released API to get email from oAuth using in iOS and Android. They document for web in recent future. So we can wait.

**Comment by dmeroff** [comment]
@hiep8024 thank you for information. It is really cool that they are implementing this.

**Comment by thiagotalma** [comment]
@dmeroff , you are in need of help with that?

**Comment by dmeroff** [comment]
@thiagotalma thank you, but I've almost finished this. I can describe, how it works at the moment:
If social network provides an email address, then we check if there is a user with such email, and if so we connect these accounts, otherwise we're trying to create new user with such email and we're generating username for him based on the email address.

If social network does not provide email address, then we show registration form.

**Comment by dmeroff** [comment]
List of networks that provides user's email address:

- Google Plus
- Facebook
- VKontakte
- Github

**Comment by dmeroff** [comment]
New version can be tried out by using following composer version constraint:
`"dektrium/yii2-user": "dev-social_login_improves"`

It still has some problems, which I want to fix as soon as possible.

**Comment by thiagotalma** [comment]
Very good!  :+1:

**Comment by dmeroff** [comment]
Done!
Docs located [here](https://github.com/dektrium/yii2-user/blob/master/docs/social-auth.md).

**Comment by thiagotalma** [comment]
Congratulations @dmeroff !
Nice work.
