### ISSUE TITLE
Argument 3 passed to dektrium\user\controllers\SecurityController::__construct() must be an instance of dektrium\user\Finder

### ISSUE THREAD

**Issue by alexk984** [dektrium/yii2-user#233]
Argument 3 passed to dektrium\user\controllers\SecurityController::__construct() must be an instance of dektrium\user\Finder, none given, called in /var/www/pravru/vendor/yiisoft/yii2/base/Module.php on line 534 and defined

![default](https://cloud.githubusercontent.com/assets/893697/5695604/1b87708c-99bd-11e4-9ca7-82d28fb6a3f4.png)

I tryied to do this **\Yii::$container->set('dektrium\user\Finder', 'dektrium\user\Finder');** but it still not working.

All is up to date.

**Comment by dmeroff** [comment]
Did you install module using composer?

**Comment by alexk984** [comment]
Yes, i added to composer.json:

"dektrium/yii2-user": "*"

**Comment by dmeroff** [comment]
Seems that module hasn't installed correctly. Could you please provide content of file `vendor/yiisoft/extensions.php`?

**Comment by alexk984** [comment]
'dektrium/yii2-user' => 
       array (
         'name' => 'dektrium/yii2-user',
         'version' => '9999999-dev',
         'alias' => 
         array (
           '@dektrium/user' => $vendorDir . '/dektrium/yii2-user',
         ),
         'bootstrap' => 'dektrium\\user\\Bootstrap',
       ),

**Comment by dmeroff** [comment]
Hmm, that's strange. I can not reproduce the problem.
It seems that you are using an out-dated yii version? Could you please answer which yii version do you use?

**Comment by alexk984** [comment]
2.0.0-beta

**Comment by dmeroff** [comment]
Yes, that is the problem. You should update to stable yii2 version (2.0.0 and higher) in order to use yii2-user 0.9.0. 

I think I should change version constraint in module's composer.json in order to prevent issues like this.
