### ISSUE TITLE
Getting error during updating with composer

### ISSUE THREAD

**Issue by it3rmit** [dektrium/yii2-user#235]
I have added the following string to my composer.json as specified in the guide
```
"dektrium/yii2-user": "~0.9.*@dev"
```
When I am trying to update packages with composer I am getting an error
```
[UnexpectedValueException]                                                  
Could not parse version constraint ~0.9.*: Invalid version string "~0.9.*" 
```
Everything works without this string, everything works fine also, if I specify 
```
"dektrium/yii2-user": "0.9.1@dev"
```
Am I the one, who is getting this error? What kind of reason could cause this error?

**Comment by jethroredblu** [comment]
Hi,
add  "dektrium/yii2-user": "*" and NOT "dektrium/yii2-user": "0.9.1@dev".
So, this works fine.

**Comment by dmeroff** [comment]
Guide fixed. It is better to use `"dektrium/yii2-user": "0.9.*@dev"`
