### ISSUE TITLE
Improve registration process

### ISSUE THREAD

**Issue by dmeroff** [dektrium/yii2-user#236]
At the moment it is pretty hard to add new fields to registration form (e.g. allow users to fill some profile fields), so some changes should be done:

- [x] Refactor registration process
- [x] Add new guide on how to add custom fields to registration form

**Comment by ismakv** [comment]
It would be nice to have the possibility to register only through email without login.

**Comment by thiagotalma** [comment]
> It would be nice to have the possibility to register only through email without login.

+1 :+1:

**Comment by dmeroff** [comment]
Done. However registration without username is still not available.

**Comment by thyseus** [comment]
One can simply "hack in" registration without username by adding

```
 public function beforeValidate() {
        $this->username = $this->email;
        return parent::beforeValidate();
    }
``` 

to the RegistrationForm model and removing the 'username' field from the view. Mind https://github.com/dektrium/yii2-user/pull/369 though.

dmeroff: Are you already implementing registration without username? If not, i would like to add this feature natively.

**Comment by dmeroff** [comment]
@thyseus this hack may not work sometimes. It's because of username regexp pattern. Email address can contain more characters than it allows. So the validation rules for username should be disabled in some way.

You are very welcome to send a PR.
