### ISSUE TITLE
About API access, tokens and refresh tokens

### ISSUE THREAD

**Issue by belerophon** [dektrium/yii2-user#244]
Hi there

- I'm using this library to login user using a custom **oAuth2** provider. Besides just using the server where the oAuth provider exists to get user details for the registration and login, **I need to further use its other APIs**, for which I need an Access Token (and Refresh Token). 
Both Access Token and Refresh Token, are retrieved by the `yii2-authclient` used on this extension, and one can get them using the `$client` variable passed to the `authenticate` method of this extension's `SecurityController`.

Once the `SecurityController` makes use of the user attributes, needed to register the user, the **`$client` variable is discarded, and the Access Token (and Refresh Token) is lost**.

_So, my doubt is about 2 things:_
1. Shouldn't Access Token be saved to allow for further logins while discarding the need to call the Authorize endpoint everytime? 
  - Why keep on repeating the Authorization step of oAuth when the logging in the same user further down in time?
  - The Access Token is interesting not only for user's login, but also for the application work, when it has to communicate with the Server's APIs. Shouldn't it be maintained right after the first Authorize step?

2. If I want to save these tokens by my own, is overriding the `SecurityController` the correct place to do it, and insert the logic to take the `$client`'s Access Token and save it on my own tables?

Thanks in advance!!
André

**Comment by dmeroff** [comment]
1. No, I don't think that Yii2-user should handle saving of tokens for future API requests. It only provides ability for users to log in via social networks.
2. Yeah, I think so.
