### ISSUE TITLE
User Account Confirmation Problem

### ISSUE THREAD

**Issue by abhi1693** [dektrium/yii2-user#248]
Users who are registered are unable to confirm their account. Whenever they click on the link, they are redirected to the login page. I know that you have provided admin the power to confirm others account. But, this is should also work without admins intervention.

Sample link:

     http://localhost:8080/Project/All/beta-v0.1.1/backend/user/confirm/4/C73DxRcjQoJvl6qaZeX1CKAc1sPIGiEv

This links works only if the user is logged in. Can you help me out where I might have committed the mistake.

**Comment by dmeroff** [comment]
Yii2-user allows both guests and logged-in users to access confirmation links (https://github.com/dektrium/yii2-user/blob/master/controllers/RegistrationController.php#L58).

It seems that you have some application-wide access control checks somewhere in your application.

**Comment by abhi1693** [comment]
I'm using yii2-admin. Is there a work-around?

**Comment by dmeroff** [comment]
I never used yii2-admin, but it seems to me that it denies access for guests. You should configure that extension so that it will not deny yii2-user actions.
