### ISSUE TITLE
Can't override model

### ISSUE THREAD

**Issue by a2dgroup** [dektrium/yii2-user#257]
Hi,

thank you for the great extension. I've got this issue:

I'm trying to override the "User" and the "UserSearch" model, but it seems to ignore it.
I've got this web.php configuration:

Components sections:

![schermata 2015-01-28 alle 14 59 55](https://cloud.githubusercontent.com/assets/7554891/5938774/5bfb33c6-a6fe-11e4-8967-e64b38602fcc.png)

Module section
![schermata 2015-01-28 alle 14 56 26](https://cloud.githubusercontent.com/assets/7554891/5938732/0c4f5ad2-a6fe-11e4-9030-f2087f591578.png)

and this "User" module class
![schermata 2015-01-28 alle 14 57 03](https://cloud.githubusercontent.com/assets/7554891/5938756/3e4d5430-a6fe-11e4-8b78-29745c5e831e.png)

The override for views and controlelrs works like a charm!

Thank you

Alessandro

**Comment by dmeroff** [comment]
It should work. Could you please describe what exactly is going wrong?

**Comment by a2dgroup** [comment]
Hi, thank you for reply.

I've set up everything like in the pics posted above, but it seems to ignore the override.
So, in the example with the override of the User module (last pic), the system load the plugin base class and ignore my override where I've added the "role" property.

Alessandro

**Comment by dmeroff** [comment]
How do you exactly checking that module uses overriden models? Could you do `var_dump(Yii::$app->getModule('user')->modelMap)` and provide the output.

**Comment by a2dgroup** [comment]
I've made a mistake in issue's title, I wrote "module" instead of model. Sorry! I've changed it.
The problem is on rewrite of User and UserSearch model. 

I'm checking the user model rewrite by trying to use a property that I've added to the model itself.

I report the var_damp:

![schermata 2015-01-30 alle 08 55 31](https://cloud.githubusercontent.com/assets/7554891/5972671/ca904a78-a85d-11e4-8048-6b8c18565618.png)

Thank you

**Comment by dmeroff** [comment]
I understood. Could you please provide code that you've written to check that model is overriden.
You've provided var_dump output, and it contains your model names, which means that they are overriden and used by module.

**Comment by a2dgroup** [comment]
Hi,
got it! I've made a mistake in the model override code, I was defining a variable with the same name of the table's column, so I got the db value overridden!

Now it works fine!

Thank you for the support and sorry for the waste of time!

Ale
