### ISSUE TITLE
Default user and profile table names

### ISSUE THREAD

**Issue by harlangray** [dektrium/yii2-user#259]
The migration creates {{%user}} and {{%profile}} tables. Where can I set the default names to user_user and user_profile?

**Comment by dmeroff** [comment]
At the moment, there is now way to do this. You only can set prefix for `db` component, but it will affect all models and migration that uses that prefix.
As a quick solution, you can change this lines in migration and override needed models.
BTW I'll try to add special module option to do this automatically.

**Comment by dmeroff** [comment]
Unfortunately I don't see a clean and easy way of implementing this.

**Comment by sbhuvanas** [comment]
is there any solution to add a new table and insert the needed data in one table?? Kindly help in this process..
