### ISSUE TITLE
Get user name

### ISSUE THREAD

**Issue by redreeva** [dektrium/yii2-user#265]
Hi! How can I get current username?

**Comment by trbsi** [comment]
I created new function for it so I can modify it if I need
>     use dektrium\user\models\User;
>	public function getUsername($IDuser=NULL)
>	{
>		if($IDuser!=NULL)
>			$username=User::findOne($IDuser);
>		else
>			$username=User::findOne(Yii::$app->user->getId());
>		return $username->username;
>	}

but I guess there is simpler solution

**Comment by redreeva** [comment]
trbsi, thank you for your implementation! But after user login and redirect to index page authentication is "lost", i.e. it is not retained. (It's not your fault, I just asked)

**Comment by trbsi** [comment]
What do you mean by: authentication is lost

**Comment by redreeva** [comment]
Look, I fill in login and password and press "Sign in". The page is reloads. I try get any user details, but I can't do this. So I think, that authentication or not worked or someone else.

**Comment by trbsi** [comment]
That is strange. It works perfectly here. It depends of your configuration and installation. Did you follow documentation of yii2-user here on GitHub

**Comment by dmeroff** [comment]
Current user can be fetched using `Yii::$app->user->identity`. It contains `User` object, so you can use `Yii::$app->user->identity->username` to get current user's username.

Authentication may not work if you have `user` component configuration in your config files. It is mentioned in installation guide.
