### ISSUE TITLE
Authentication via social networks

### ISSUE THREAD

**Issue by redreeva** [dektrium/yii2-user#271]
Hi! I can't understand how implement authentication via social networks. 
I followed all instructions in documentation, but I had stopped at function successCallback, which should contains some code I don't know. At forums I seen many solves, but nothing helped.
Authentication dialog show: "Calling unknown method: dektrium\user\Module::model()" or "Error: redirect_uri_mismatch". 
Please help me solve this issue.

**Comment by dmeroff** [comment]
You don't need to implement any method yourself. You just need to register applications in needed networks, and then configure `authClientCollection` application component.

https://github.com/dektrium/yii2-user/blob/master/docs/social-auth.md

**Comment by redreeva** [comment]
Thank you for fast response. Look, in this case, authentication dialog show: Page not found.

**Comment by redreeva** [comment]
Dmitry, please don't leave me with my problem. I fight with social authentication during two days and it not gives me any results.

**Comment by dmeroff** [comment]
On which step are you getting "Not found" error? Could you please describe in steps what are you doing before this error occurs?

**Comment by redreeva** [comment]
Of course! At first, I registered web apps at social nets. After, I declared authClientCollection with all clients at config file, as you wrote above. That's all.

**Comment by dmeroff** [comment]
I mean, when are you getting error? When you click social network button, or after authenticating in popup window, or on any other moment?

**Comment by redreeva** [comment]
When I click social network button

**Comment by dmeroff** [comment]
Could you please provide a screenshot of the error?

**Comment by redreeva** [comment]
http://joxi.ru/LVm6qkwiz1JVrZ

**Comment by dmeroff** [comment]
Strange url. Are you sure you are using correct login page? Yii2-user login route is `user/security/login`, not `site/login`.

**Comment by redreeva** [comment]
Yes, my used login route is user/security/login, but it route contains login link only. I had to used it somewhere else, didn't I?

**Comment by dmeroff** [comment]
It is strange that auth widget redirects you to `site/auth`, but not to `user/security/auth`. Are you overriding login page view?

**Comment by redreeva** [comment]
Only for login link

**Comment by dmeroff** [comment]
Could you please provide the view file code?

**Comment by redreeva** [comment]
Of course. Here you're.

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use dektrium\user\widgets\Connect;

$this->registerCssFile('@web/css/login.css');
$this->title = Yii::t('user', 'Log in');
$this->params['breadcrumbs'][] = $this->title;
?>

<?= $this->render('/_alert', ['module' => Yii::$app->getModule('user')]) ?>

<div class="site-login">
    <div>
        <div >
            <div class="pull-left login-sign">
                <h1><?= Html::encode($this->title) ?></h1>
                <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text </p>
            </div>
            <div class="pull-left login-form">
                <?php $form = ActiveForm::begin([
                    'id'                     => 'login-form',
                    'enableAjaxValidation'   => true,
                    'enableClientValidation' => false,
                    'validateOnBlur'         => false,
                    'validateOnType'         => false,
                    'validateOnChange'       => false,
                ]) ?>

                <?= $form->field($model, 'login', ['inputOptions' => ['autofocus' => 'autofocus', 'class' => 'form-control', 'tabindex' => '1', 'placeholder' => 'Username']])->label(false) ?>

                <?= $form->field($model, 'password', ['inputOptions' => ['class' => 'form-control', 'tabindex' => '2', 'placeholder' => 'Password']])->passwordInput()->label(false) ?>

                <div class="join-fields">
                    <?= $form->field($model, 'rememberMe')->checkbox(['tabindex' => '4']) ?>
                    <div class="form-group forgot-pass"><?= Html::a(Yii::t('user', 'Forgot password?'), ['/user/recovery/request'], ['tabindex' => '5']); ?></div>
                </div>

                <?= Html::submitButton(Yii::t('user', 'Sign in'), ['class' => 'btn btn-primary btn-block', 'tabindex' => '3']) ?>

                <?php ActiveForm::end(); ?>
            </div>
        </div>
    </div>
</div>

**Comment by redreeva** [comment]
$this->registerCssFile('@web/css/login.css');
$this->title = Yii::t('user', 'Log in');
$this->params['breadcrumbs'][] = $this->title;
?>

<?= $this->render('/_alert', ['module' => Yii::$app->getModule('user')]) ?>

Div site-login contains:
<?php $form = ActiveForm::begin([
                    'id'                     => 'login-form',
                    'enableAjaxValidation'   => true,
                    'enableClientValidation' => false,
                    'validateOnBlur'         => false,
                    'validateOnType'         => false,
                    'validateOnChange'       => false,
                ]) ?>

                <?= $form->field($model, 'login', ['inputOptions' => ['autofocus' => 'autofocus', 'class' => 'form-control', 'tabindex' => '1', 'placeholder' => 'Username']])->label(false) ?>

                <?= $form->field($model, 'password', ['inputOptions' => ['class' => 'form-control', 'tabindex' => '2', 'placeholder' => 'Password']])->passwordInput()->label(false) ?>

                <div class="join-fields">
                    <?= $form->field($model, 'rememberMe')->checkbox(['tabindex' => '4']) ?>
                    <div class="form-group forgot-pass"><?= Html::a(Yii::t('user', 'Forgot password?'), ['/user/recovery/request'], ['tabindex' => '5']); ?></div>
                </div>

                <?= Html::submitButton(Yii::t('user', 'Sign in'), ['class' => 'btn btn-primary btn-block', 'tabindex' => '3']) ?>

                <?php ActiveForm::end(); ?>

**Comment by dmeroff** [comment]
I dont see here social buttons widget. Is it view file you are using?

**Comment by redreeva** [comment]
I didn't understood what you want at first time:)) I add this code at layout main:
<?= yii\authclient\widgets\AuthChoice::widget([
                'baseAuthUrl' => ['site/auth']
            ]) ?>

**Comment by redreeva** [comment]
OH!!!!!! I see mistake!!!!

**Comment by redreeva** [comment]
Thank you!!! You are perfect!!!

**Comment by redreeva** [comment]
Dmitry, I have another question:) How can I parse email from social net for authentication form via social net? And for what i should fill out it's field if i can parse email

**Comment by dmeroff** [comment]
At the moment, you can do this only by overriding controllers and models and writing all logic yourself. Registration via networks without entering any credentials [is on roadmap](https://github.com/dektrium/yii2-user/issues/232).

**Comment by redreeva** [comment]
Ok. Thank you for your help!

**Comment by redreeva** [comment]
Dmitry, hi! Do you have work experience in authentication via Google+ or Tumblr? Yesterday I wrote here in first question of this topic about Google error "redirect_uri_mismatch". This problem is not gone still. And added another one with Tumblr (after allowing access to my personal data for application shows an error: "oauth_signature does not match expected value") though I sure it was before. Do you have any ideas how solve it's issues?

**Comment by dmeroff** [comment]
I've used only Google API, and I've met the same problem. I've solved it by enabling pretty urls in application, and using `http://yoursite.com/user/security/auth?authclient=google`. By the way, Google apis settings take some time to be applied, so you should wait 5-10 minutes after changing them.

**Comment by redreeva** [comment]
Dmitry, thank you for your help!!! I'm very inattentive!:(

**Comment by rahah66** [comment]
hi How to access social network attributes?
