### ISSUE TITLE
Remove flash messages once displayed to avoid duplication

### ISSUE THREAD

**Issue by nirvana-msu** [dektrium/yii2-user#273]
I'm using yii2-user with advanced application template, and unless you make any changes to default configuration, all flash messages are duplicated. I know that you can simply turn off alerting in yii2-user by setting `enableFlashMessages` to `false`, but what would make it even better is if this extension removed messages that it had already flashed from queue, just like it is done in `Alert` widget supplied with advanced application template. If this was the case there would be no conflict in the first place.

**Comment by dmeroff** [comment]
I don't think that flash messages should be removed manually, since they are flushed when application ends. If you have your own widget to display alerts, so simply turn off `enableFlashMessages`, as you've mentioned.
