### ISSUE TITLE
Interrupting authorization through social network makes it impossible to connect the account later on

### ISSUE THREAD

**Issue by nirvana-msu** [dektrium/yii2-user#275]
Steps to reproduce the problem:
 1. Try logging in with a social network, e.g. facebook. This will create an entry in `{{social_account}}` table with `user_id` set to `NULL`.
 2. When asked to provide a username / email either close the page, or follow the link saying you already have an account on the website.
 3. Login with your username / password and try linking facebook account.

As a result, webpage displays: `This account has already been connected to another user`. There seems to be no way to re-connect your facebook account as it is stuck with not being assigned to any user (i.e. having `user_id` set to `NULL`).

Am I missing something obvious here?

**Comment by dmeroff** [comment]
Thank you for reporting. Fixed.
