### ISSUE TITLE
Call to a member function where() on null

### ISSUE THREAD

**Issue by trbsi** [dektrium/yii2-user#278]
I'm trying to find user by ID and I'm doing this by 
```
use dektrium\user\Finder;
$finder = new Finder;
$finder->findUserById(Yii::$app->user->getId());
```
but it gives me error:
http://s12.postimg.org/cu3mrh1ml/Capture.png

**Comment by dmeroff** [comment]
You should instantiate finder using `Yii::createObject` or retrivieng it from DI container:

```php
$finder = Yii::createObject(Finder::className());
// OR
$finder = Yii::$container->get(Finder::className());
```

BTW you may access current user model by using `Yii::$app->user->identity`.
