### ISSUE TITLE
Filter Gridview Create_at /admin/index.html

### ISSUE THREAD

**Issue by tecnologiaterabyte** [dektrium/yii2-user#280]
Hi dektrium, when you try to filter by create_at column, it gives the error that must be an integer, you should place the conversion in the Model UserSearch so that it is done correctly,

Thks,

**Comment by dmeroff** [comment]
Added datepicker to grid view, so users can be now filtered by date.

**Comment by tecnologiaterabyte** [comment]
Thks, dmeroff.
