### ISSUE TITLE
Admin update problems..

### ISSUE THREAD

**Issue by tiffoknee** [dektrium/yii2-user#282]
Getting a bunch of probs with the 0.9.4 update..

(on saving an update)
<pre>PHP Fatal Error &#039;yii\base\ErrorException&#039; with message &#039;Call to a member function load() on array&#039; 

in /var/www/vendor/dektrium/yii2-user/controllers/AdminController.php:271

(in index) -> admincontroller -- actionIndex
Call to undefined method yii\helpers\Url::current()

I've reset to 0.9.3 for now and it's all fine again..

**Comment by dmeroff** [comment]
Thank you for reporting, fixed.
