### ISSUE TITLE
How to use yii2-user with yii advance template

### ISSUE THREAD

**Issue by rahulsinh** [dektrium/yii2-user#284]
how to use yii2-user instead of yii advance template like login form registration form into menu

**Comment by dmeroff** [comment]
*Please, if you have any questions, ask them in google group or gitter chat. Github issues are for reporting issues and requesting new features.*

Advanced template is not fully supported at the moment. But you may create two new module classes, extend them from yii2-user module class, then configure their classmaps to give access only to needed controllers. Then you should add that module classes to configuration.

**Comment by vladim1** [comment]
What do you mean by ```then configure their classmaps to give access only to needed controllers```. Where can I do this? I don't see classmap property in the Module
