### ISSUE TITLE
Cannot route with urlRules

### ISSUE THREAD

**Issue by kmergen** [dektrium/yii2-user#285]
Hallo,
I cannot route with the pattern used in user Module.php in property $urlRules.

I need the urlPrefix ('user') to route correctly. But this don't work automatically.

For example:

In property urlRules : ```'forgot' => 'recovery/request'``` not work
If I change it to ```'user/forgot' => 'recovery/request'``` work

**Comment by dmeroff** [comment]
I don't understand what is working incorrect? Creating urls? Accessing module's pages? Could you please explain more clearly?

**Comment by dmeroff** [comment]
Frozen since no answer from you. Reopen this issue when needed information will be provided.
