### ISSUE TITLE
yii2-user and AccessRule

### ISSUE THREAD

**Issue by bbratu** [dektrium/yii2-user#288]
I am building a small site and AccessRule can satisfy my needs. I am writing my implementation so that others can use it if they need something similar.

I have created the file common\components\AccessRule.php
<pre><code>
namespace app\common\components;
use Yii;

class AccessRule extends \yii\filters\AccessRule {

    /**
     * @inheritdoc
     */
    protected function matchRole($user)
    {
        if (empty($this->roles)) {
            return true;
        }
        foreach ($this->roles as $role) {
            if ($role === '?') {
                if (Yii::$app->user->isGuest) {
                    return true;
                }
            } elseif ($role === '@') {
                if (!Yii::$app->user->isGuest) {
                    return true;
                }
            } elseif ($role === 'admin') {
                if (!Yii::$app->user->isGuest && Yii::$app->user->identity->isAdmin) {
                    return true;
                }
            }
        }

        return false;
    }
}
</code></pre>

and in my controller

<pre><code>
use app\common\components\AccessRule;
</code></pre>

and in behaviors()
<pre><code>
            'access' => [
                'class' => \yii\filters\AccessControl::className(),
                'ruleConfig' => [
                    'class' => AccessRule::className(),
                ],
                //'only' => ['create', 'update', 'index', 'delete'],
                'rules' => [
                    [
                        'actions' => ['create', 'update', 'index', 'delete'],
                        'allow' => true,
                        'roles' => ['admin'],
                    ],
                    [
                        'actions' => ['view', 'search'],
                        'allow' => true,
                        'roles' => ['?', '*', 'admin'],
                    ],
                ],
            ],
</code></pre>

The code is based on this article:
http://thecodeninja.net/2014/12/simpler-role-based-authorization-in-yii-2-0/

If there is a better way to do it please let me know.

**Comment by dmeroff** [comment]
I'll add this as a guide in documentation as soon as possible. Thank you.

**Comment by dmeroff** [comment]
This guide has been added.
