### ISSUE TITLE
how to change loginUrl

### ISSUE THREAD

**Issue by philippfrenzel** [dektrium/yii2-user#289]
Hi, how can I change the loginUrl from bootstrap.php

**Comment by philippfrenzel** [comment]
Hi, made a "walk around" with custom view and custom controller and now it works fine, so feel free to ignore the original request! Thanks! Philipp

**Comment by tecnologiaterabyte** [comment]
It could explain better how did you change the loginUrl of bootstrap.php me interested in the template advanceapp have 2 urls Login and  Loginadmin, now I have extended the view and the controller of LoginAdmin as you did to tell the bootstrap by which loginby default.

**Comment by dmeroff** [comment]
@tecnologiaterabyte you can just set `loginUrl` in your config file as follows:

```php
'components' => [
  'user' => [
    'loginUrl' => ['site/login'],
  ],
],
```

**Comment by philippfrenzel** [comment]
nope, get's overwritten by bootstrap from module

**Comment by dmeroff** [comment]
The latest version (0.9.3) allows you to override that value from config. I've checked it a few minutes ago ;)

**Comment by tecnologiaterabyte** [comment]
Work Fine v. (0.9.3), great job soon I will get in my blog a complete guide on how to implement yii2-user in advanced app, for me the best extension of yii2 of user authentication.
