### ISSUE TITLE
Permission for User module through Yii2 Admin

### ISSUE THREAD

**Issue by harlangray** [dektrium/yii2-user#293]
I have given permission to a user to use some urls in user module. Somehow these users cannot use the module.  It seems only the users specified as 'admins' in config file can use the module. Am I missing some setting here? Thanks.

BTW thanks for this very useful module.

**Comment by dmeroff** [comment]
Yii2-user don't use any other extensions to control access to admin pages. It is done only by configuring `admin` property. If you need custom access control, you may override admin controller.
