### ISSUE TITLE
Documentation updates

### ISSUE THREAD

**Issue by dmeroff** [dektrium/yii2-user#297]
- [x] Add the guide "How to add custom field to user model" (#296)
- [x] Add the guide "How to use RBAC with Yii2-user"
- [x] Add the guide "How to use Yii2-user with Yii2 advanced template"

**Comment by thiagotalma** [comment]
:+1:

**Comment by philippfrenzel** [comment]
+1

**Comment by dmeroff** [comment]
Started working on guide "How to add custom field to user model" #323 #296

**Comment by jsobers1331** [comment]
nice

**Comment by dmeroff** [comment]
Guide "How to add custom field to user model" is written, unfortunately it only covers a way of how to add new field which is editable only on admin view. This is because of shitty code inside of RegistrationForm, which provides only very hacky way to add new fields. When I finish refactoring of registration process, I will update the guide.

**Comment by tecnologiaterabyte** [comment]
A personal opinion is that additional fields to the record can be stored in an alternate table that does not modify the user model, could be in the user profile, Add many fields to user registration, would make tedious user registration, this process should be simple as possible.

**Comment by dmeroff** [comment]
@tecnologiaterabyte it depends on project. Sometimes you need to add new fields to registration form, and module should not restrict this.
