### ISSUE TITLE
username doesnt allow "-"

### ISSUE THREAD

**Issue by philippfrenzel** [dektrium/yii2-user#298]
Hi,

the rules for the username don't allow "-" [minus] : can this be "opened" ?

Thanks Philipp

**Comment by dmeroff** [comment]
At the moment, the only way to do this is overriding rules method of User model. I'm thinking on how to provide easy way to change validation rules, but I don't think this will be implemented soon.

**Comment by philippfrenzel** [comment]
Changed rule in 'local' Model and Works Fine! Thanks! No Need to change, just add docs?;)
