### ISSUE TITLE
Getting other profile info from Gravatar

### ISSUE THREAD

**Issue by andredp** [dektrium/yii2-user#301]
Hey @dmeroff,

First of all, thanks a bunch for this module... It has been saving me days of work (in the middle of a college semester that is gold!).

I was looking at the gravatar implementation on this module and I wanted to load up the profile fiedls (name, location, etc) from the gravatar profile as soon as I registered a new user (my site doesn't let users to register themselves). 

Should I override the whole Admin Controller to be able to do it?

IMO, I think you should implement some callbacks (like 'onBeforeRegister', 'onAfterRegister', etc) so we have the flexibility of extending your classes without actually overriding the classes (which is a huge pain to update)

**Comment by dmeroff** [comment]
I think it's better to override profile model, then change beforeSave method, where you'll get information from gravatar account and fill needed fields.

Yes, I have plans to add events to most critical places of code, so You will be able to add handlers for them.

**Comment by andredp** [comment]
Oh, that seems like a better Idea than changing the controller. Thanks!
