### ISSUE TITLE
Password strength check

### ISSUE THREAD

**Issue by thiagotalma** [dektrium/yii2-user#303]
Hello again!

I would suggest another important improvement is lacking in yii2-user: password strength check.

I suggest the following regex: `^\S*(?=\S{6,})(?=\S*[a-z])(?=\S*[A-Z])(?=\S*[\d])\S*$`
    `(?=\S{6,})` = at least length 6
    `(?=\S*[a-z])` = containing at least one lowercase letter
    `(?=\S*[A-Z]`) = and at least one uppercase letter
    `(?=\S*[\d])` = and at least one number

Your project is growing and becoming popular. Congratulations!
I believe it would be good to have these default rules, but with configurable parameters.

**Comment by dmeroff** [comment]
Hello,
First of all, thank you for congratulations.

I don't like the idea when website makes user to create password that user don't want. I mean everyone is responsible himself for the security of his account, and if user want to have weak password, he should be able to have it. And it really annoys me when the website shows me a message, which says "Password should have at least 1 digit, 1 lowercase, 1 uppercase, special symbols and a couple of hieroglyphs". So I want Yii2-user to be free of these rules.

BTW these rules can be added to the guide as a "How to" article.
BTW2 I'm thinking on how to make validation rules more centralized and configurable. At the moment developer should override model and then override full `rules` method with copy-pasting validation rules from parent model. In my opinion it should be much easier. But at the moment I don't know how this can be implemented to be simple and easy to do.
