### ISSUE TITLE
getUser() type of yii\web\User

### ISSUE THREAD

**Issue by chrisschd** [dektrium/yii2-user#306]
Hello!

What did a make wronge? I use your great extention and it works fine but when I call Yii::$app->getUser() it will be type of yii\web\User (echo Yii::$app->getUser()->className()). Why not the User Class of your extention?

Thanks for help!

**Comment by dmeroff** [comment]
Hello,

`Yii::$app->getUser` is an instance of `yii\web\User` because it is a user *component*. Yii2-user does not provide any custom user component, so this is normal.

BTW `className` is a static method, you shouldn't call it in that way.
