### ISSUE TITLE
Login with social network account and cannot save account information cos no password has been set up before

### ISSUE THREAD

**Issue by soulge** [dektrium/yii2-user#310]
Because i register the account using social network account, that means i dnt need to set up password. but when i try to update the account information, i saw the update password function there. it looks like you cannot set up a new password without current password.

i think it is a bug which you cannot recognize whether a current password is necessary in case user is registered by social network account.

**Comment by dmeroff** [comment]
This is not a bug. Password for user registered via network is generated automatically and sent via email message on the registration step.
