### ISSUE TITLE
Migration when user table already exists

### ISSUE THREAD

**Issue by Arnaud-G1** [dektrium/yii2-user#312]
Hi,
I've installed and used Advanced template before installing this great extension to my project 

I'm suggesting to add a test in the migration to detect if a user table already exists and reuse it if already exisitng (and adapt the fields to the new table keeping mainly email, id and auth_token).

Dropping the user table can have significant side effects if there are other linked tables.

Other side effect, is that profile entry may need to be added when missing in original user table

**Comment by dmeroff** [comment]
Hello,
You should adopt your tables yourself. Migrations are designed to be applied to clean application, and adding checks to their code will provide complication and may cause unneeded troubles.
For example, the migration will need to select all users from existing table, and then create profile entries for them. So I don't think this will be implemented in any way.
