### ISSUE TITLE
page is not redirecting to login or any page 

### ISSUE THREAD

**Issue by ajkosh** [dektrium/yii2-user#313]
when i m typing this it is taking me yii2 login page not to ur yii2-user login page
this is url i m using
http://localhost/basicP/web/user/security/login
and how to redirect from sitecontroller to ur login page when application run
when i m using this it is fine
http://localhost/basicP/web/index.php?r=user/security/login,how i can over ride your view files with my themes

**Comment by dmeroff** [comment]
Please, make sure you don't have `user` component configuration in your main config file, because it overrides settings provided by yii2-user.
You can override view files as described in documentation.

**Comment by ajkosh** [comment]
but how i can use my login.php class

**Comment by ajkosh** [comment]
i have multiple themes so user can choose any theme so according to theme i m changing login page so how i can handle with ur modules,plz dot mind can u tell me how your mail confirm is working,how u getting key from url nd calling action

**Comment by ajkosh** [comment]
now this is coming ERRoR User::identityClass must be set.

**Comment by ajkosh** [comment]
should i raise issue again coz u closed ,my config file is k no user component is there

**Comment by dmeroff** [comment]
First of all, please, can you please stop shorten words? It is really hard for me to understand you messages when you use "plz", "u", "coz", etc.

Secondly, you should configure your themes configs as described in documentation.

Thirdly, if you are getting "User::identityClass must be set" error, then you've installed yii2-user in a wrong way. Did you used composer? If you didn't I can't help you, because only composer installation is supported.

**Comment by ajkosh** [comment]
yes i used composer,and sorry for shorten words.

**Comment by ajkosh** [comment]
i tried two times with new installation but it is same error.

**Comment by ajkosh** [comment]
http://localhost/pm/web/site/site/site/site/site/site/site/site/site/site/site/site/site/site/site/site/site/site/site/site/login
this is coming when trying to login

**Comment by dmeroff** [comment]
1) Overriding view files (login.php is a view file) is described in documentation.
2) Which error are you getting exactly? Could you please provide a screenshot of that error? Also please provide content of `composer.lock` and `@vendor/yiisoft/extensions.php` files.

**Comment by ajkosh** [comment]
it is long file should i post here

**Comment by ajkosh** [comment]
this is how i m extending controller for implement theme
i have controller and all other controller extending from this controller here i m setting view for theme(main.php)
class BaseController extends \yii\web\Controller
{

public function init(){
	$theme= Themes::find()->where(['id'=>1])->one();
$title=$theme['title'];
$this->getView()->theme = Yii::createObject([
    'class' => '\yii\base\Theme',
    'pathMap' => [ 
        '@app/views' => [ 
            '@webroot/theme/'.$title.'/views',
         ]
     ],
   
])

here i m finding which theme is active that theme main.php is overriding ,i m not setting in configuaration file.so how i will set this,

2.how to sent user directly to your login page not yii2 site/login action

**Comment by dmeroff** [comment]
1) Uhm, what is the problem? Add the line mentioned in guide to your theme configuration inside the controller, like so:
```php
'@dektrium/user/views' => '@webroot/theme/'.$title.'/user/views'
```

2) I'm sorry, but I can not understand your problem. Yii2-user automatically configures user component to redirect to `/user/security/login`, unless you don't do following:
- installed yii2-user without composer
- have outdated yii2 version (yii2-user supports only stable versions, not beta, rc or alpha)
- have `user` component configuration inside any of your config files

**Comment by ajkosh** [comment]
already i did as u said it is not effecting 
i also did same
'@dektrium/user/views' => '@webroot/theme/'.$title.'/user/views'

**Comment by ajkosh** [comment]
i type this full url for login 
http://localhost/pm/web/index.php?r=user/security/login
otherwise it is going to site/login
