### ISSUE TITLE
Forbidden (#403) error when logged in on /user/login

### ISSUE THREAD

**Issue by rubenheymans** [dektrium/yii2-user#314]
When I'm logged in and I go to /user/login, I get a Forbidden (#403) error
How can I prevent this?

**Comment by dmeroff** [comment]
In my opinion it is logically correct to raise Forbidden error.
If you have reasons to visit login page, when already logged in, you should override security controller, and then change access control rules.

P.S. Github issues are for reporting bugs and issues, not for asking questions. If you have one you'd better to ask it in google group or in gitter.

**Comment by ermGit** [comment]
@rubenheymans Did you solve this issue?  I am having the same problem with getting a 403 error.  I get the error when I do the following sequence: I login in the backend, view my frontend, and then try to return to my backend.

**Comment by rubenheymans** [comment]
@ermGit it's almost 5 years ago, I switched to javascript a long time ago
