### ISSUE TITLE
Meaning of some tables and collumns

### ISSUE THREAD

**Issue by invaderhd** [dektrium/yii2-user#318]
This is not really a bug is more a clarification. I think you should add to Documentation 2 ou 3 lines explaining the database tables. 

For example the token table that is this? This token change over time? This token is the one that is to validate an account?

What is the auth_key on user table?

**Comment by dmeroff** [comment]
Does it really matter? If I have enough time, I'll add this, but not in the near future.

token table is used to save recovery and confirmation tokens.
auth_key is needed by Yii2 authentication system, you can read more in Yii docs.
