### ISSUE TITLE
404 Error when trying to access anything in /user/...

### ISSUE THREAD

**Issue by Griffolion** [dektrium/yii2-user#320]
I installed everything according to the instructions, and my Yii app has not thrown any errors, so the module has installed fine.

I attempt to access the user admin areas with localhost/appname/web/user/admin/index and I get a 404 error. For posterity, I attempted the default login process (as it would use new User class in extension), and it gives a 404 error when I attempt to login with something.

**Comment by jsobers1331** [comment]
you can't access anything under "user/"?

If that's so, how were you able to login?

Can you access the login page using "/user/security/login"?
Per instructions on https://github.com/dektrium/yii2-user/blob/master/docs/available-actions.md

**Comment by Griffolion** [comment]
It was the default login page. I used that to check if it knew which User class to use, and it did, and thus threw an error. But this is irrelevant now.

Yes, I can access /user/security/login, but when I click the sign up link, I get a 404 with the URL bar leading me to /user/register. If manually change the URL to /user/registration/register then it works fine. I have some rules in my urlManager component config:

'<controller:\w+>/<id:\d+>' => '<controller>/view',
'<controller:\w+>/<action:\w+>/<id:\d+>' => '<controller>/<action>',
'<controller:\w+>/<action:\w+>' => '<controller>/<action>',
'gii'=>'gii',
'gii/<controller:\w+>'=>'gii/<controller>',
'gii/<controller:\w+>/<action:\w+>'=>'gii/<controller>/<action>',

Are any of these messing with your own routing rules?

**Comment by jsobers1331** [comment]
That's great, Happy coding. 

@dmeroff think you can close this when ready.
