### ISSUE TITLE
add user_type and email_type field to user table

### ISSUE THREAD

**Issue by ajkosh** [dektrium/yii2-user#323]
i added fields to user table but it is not saving data to db

**Comment by ajkosh** [comment]
how to extend registration process and add fields to registration form

**Comment by dmeroff** [comment]
As I've already said, answer questions in [Gitter chat](https://gitter.im/dektrium/yii2-user) or in google group.

There is no guide at the moment, but you can override needed model and view to add new fields. Also make sure that you added fields to scenarios and rules.

**Comment by ajkosh** [comment]
i m sorry but you are not replying anywhere,if you can give hint better,you just closing issue for you project,but it does not mean you should not tell or help us,already i read you issues ,so many peoples left your yii2 user,even i m also leaving .

**Comment by ajkosh** [comment]
i posted there if you will not reply i have to create new issue again becoze it is bug ,i think ,if we can add additional fields

**Comment by dmeroff** [comment]
I'm trying to answer to everyone's questions. Sometimes I just don't have enough time or rarely I don't have answer to questions.

I've answered your on Gitter, check it out.

I'll close any topics here which are not a bug. This is not a bug, just missed docs.

**Comment by jsobers1331** [comment]
@ajkosh if you want I would help you extend this module to add fields to the registration form. I've done something similar and @dmeroff  if you don't mind, i've been watching issues created here and this isn't a bug. you can add field if you want to.

@ajkosh Just looking into overriding models in the documentation section, this is what i used. if you have any questions feel free to ask me...

**Comment by ajkosh** [comment]
you can add fields but problem to use those fields in registration form is not easy,
see this https://github.com/dektrium/yii2-user/issues/236.i dont it is fixed or not,if we cant add fields to registration form then it is bug,or you can say need enhancement .if you have solution please provide me

**Comment by ajkosh** [comment]
i added fields what it is not saving i added field n registration model and set into set attributes,but it is not saving,null is going,then i set to safe in rules,but still it is not working,i am planning to add field user type in user table ,so according to user type i m setting rbac on roles,so every user has user type and user type has role so ,user type is different table,just using as foreign key in user table.i m trying to add yii2 admin with this ,if it is possible ,please help with this .

**Comment by jsobers1331** [comment]
you can add fields to the registration form, this isn't bug.  sure i will help you.

Sounds to me like you are doing everything based on documentation here:
https://github.com/dektrium/yii2-user/blob/master/docs/overriding-models.md
https://github.com/dektrium/yii2-user/blob/master/docs/overriding-views.md
https://github.com/dektrium/yii2-user/blob/master/docs/overriding-controllers.md

The important thing with adding fields and using foreign key relation you should have the right function calls as well so you can get your data from other tables. you can easily so this using the gii utility emded in Yii2, NOT overwriting but using the functions generated and merging the differences.

Also if you can provide an example of your model that might be helpful to determine what rules you should be using. Also you did right with having user type as a different table. I did the same thing using the foreign key relation. Personally i don't like to add fields to the user table so in case @dmeroff extends the module and add more fields there won't be conflicts with upgrading using migration scripts. so if possible use another table to hold the data for your new fields.

Also it is strange you are getting null data entered in your table, from my research, this could mean that the data entered is not what the database is expecting and resulting in the database entering the default values which tends to be null or all zeros, i had the same problem yesterday with another module until i realized the datatypes in mysql table was incorrect type and once i updated to correct type the value saved correctly.

**Comment by ajkosh** [comment]
hi thnku for reply.
it will great help if you just explain a rough flow of this.yii2-user.
i m not overriding models ,i m changing yii2-user user.php and regisration.php.
is it right?
did you check yii2-admin?can i implement with yii2-user.

**Comment by jsobers1331** [comment]
>i m not overriding models ,i m changing yii2-user user.php and regisration.php.
>is it right?

No this is not correct, you should never change files in the vendor folder or modules code directly, when author updates his branch here on github and releases the update all your changes and potentially be lost.  

you need to override models if you would like to save other fields into the database.

For example, if you are using advance template for yii2, you will see path common\models\user.php.  This is the file you will edit.
Never edit the files in vendor\dektrium\yii2-user.

Follow the documentation in https://github.com/dektrium/yii2-user/blob/master/docs/overriding-models.md This will show you how.

In relation to changing the registration process, you need to override the controller so you can direct which pages should display after log in and also views you will need to update if you want to show custom fields like a second password or check-boxes etc. (see documentation links above on how to override)

**Comment by ajkosh** [comment]
i have model as you said so how to save now
namespace app\models;

use dektrium\user\models\User as BaseUser;

class User extends BaseUser
{
   
    public function register()
    {
       //if i write here register function how it will override
    }
}

**Comment by ajkosh** [comment]
can u help me to override register function with extra fields

**Comment by jsobers1331** [comment]
First check if your model is in the right place, usually i keep my models which i will use in both backend and frontend in the common folder. so it would be "namespace common\models;"

> public function register()
>{
>    //if i write here register function how it will override
> }

Should not be in Models, this should be done in the controller. 
You should overload RegistrationForm file so you can add fields on registration form, See example below....

For example:

> namespace frontend\models\user;

> use \dektrium\user\models\RegistrationForm as BaseRegistrationForm;

> /**
>  * Registration Form 
>  */
> class RegistrationForm  extends BaseRegistrationForm
> {
    
>     public $captcha;
    
 >    public $password_repeat;

 >    /**
 >     * @inheritdoc
 >     */
 >    public function rules()
>     {
  >       $rules = parent::rules();
 >        $rules[] = ['captcha', 'required'];
>         $rules[] = ['captcha', 'captcha'];
>         $rules[] = ['password_repeat', 'required', 'skipOnEmpty' => $this->module->enableGeneratingPassword];
>         $rules[] = ['password_repeat', 'compare', 'compareAttribute' => 'password', > 'message'=>"Passwords don't match"];
>         return $rules;
        
        
>    } 
 
Overriding models would contain information for new fields or custom labels, relations, etc.

As for the function you showed me above, i would put that in the overridden controller called "RegistrationController", this way you can add custom logic to process new fields added in above model RegistrationForm.

Hope this helps...

**Comment by dmeroff** [comment]
@jsobers1331 I've edited your messages to apply the code highlighting. You can read [here](https://guides.github.com/features/mastering-markdown/) section "Syntax highlighting" ;)

**Comment by jsobers1331** [comment]
:) thanks.

**Comment by ajkosh** [comment]
when i m run application how to send this to login page everytime,if user is guest,where i can set this,and i did nt find forgot action in your docs,what is actions name user/forgot or else

**Comment by ajkosh** [comment]
i have problem i have already a basemodel and basecontroller for common use and alll others controllers and models ectending from these so how i can override your models or controllers

**Comment by jsobers1331** [comment]
You can control when to send a user to login page quite easily by the use of "AccessControl" class:
http://www.yiiframework.com/doc-2.0/yii-filters-accesscontrol.html

As for overriding any of his functions, just reuse the function name i believe of any his functions  you would like to override in your file and Yii2 will use your function declaration in place of his.

This is explained in https://github.com/dektrium/yii2-user/blob/master/docs/overriding-controllers.md and https://github.com/dektrium/yii2-user/blob/master/docs/overriding-models.md

**Comment by ajkosh** [comment]
yes ,i did everything is working but i have basemodel class and base controller ,i have option for multiple themes,with toggle you can change themes,even login and registration page also.i can override his view and controller and model,but my all models and controllers are extending from basemodel and basecontroller.
in base controller i have this
$this->getView()->theme = Yii::createObject([
    'class' => '\yii\base\Theme',
    'pathMap' => [ 
        '@app/views' => [ 
            '@webroot/theme/'.$title.'/views',
         ]
     ],
   ]);
so in title variable i m passing path of main.php which is existing in themes folder ,so my all controllers are rendering to view according to themes.
so i have one option ,that i m doing now i extending yii2-user models and controllers with my basemodel and basecontrollers.
is it right ?or any other way
thnku for helps and it is great work

**Comment by ajkosh** [comment]
when any field is empty this is coming ,is it fine or any error
{"login-form-login":["Login cannot be blank."],"login-form-password":["Password cannot be blank."]}

**Comment by jsobers1331** [comment]
yes you way sounds right to me, extending yii2-user models and controllers using basemodel and base controllers.

**Comment by jsobers1331** [comment]
It is fine to have warnings such as these, these aren't errors. This is client-side validation and ensure the user enters something into the fields before submitting form for processing.

Sorry for the late reply, but life calls and can take up much of my time.

yes it is great work and I'm sure @dmeroff appreciates your use and support for it.
