### ISSUE TITLE
Use PHPMailer instead of Swiftmailer

### ISSUE THREAD

**Issue by Inttegrum** [dektrium/yii2-user#328]
I see that Swiftmailer is used in Mailer::sendMessage() and I wonder if this can be changed to PHPMailer without any trouble.

My hosting provider for some reason has Swiftmailer banned and I can't use it.

**Comment by dmeroff** [comment]
Yii2-user does not use Swiftmailer itself, it just uses `mailer` application component. By default it is swiftmailer, but you can use [this extension](https://github.com/SDKiller/zyx-phpmailer) to enable PHPMailer support.
So you just install that extension and change your application config to use that extension.

**Comment by Isan26** [comment]
Helped me too..thanks
