### ISSUE TITLE
ReflectionException 'Class bidder does not exist'   in vendor/yiisoft/yii2/di/Container.php:408

### ISSUE THREAD

**Issue by workforme** [dektrium/yii2-user#329]
==========the action is:
public function actionBidit(){
        if(!Yii::$app->user->isGuest)
        {
                $inv = new FillInvestForm();
                if($inv->load(Yii::$app->request->post())) {
                Yii::info("xxxxxxxx".VarDumper::dumpAsString($inv->attributes));
                        if($inv->makeInvest()){
                               .......
                        }
                }
                $loan= Loan::findOne($_GET['loanid']);
                $inv->bidder="aaaaaa";
                return $this->render('a',['model' => $inv]);
        }else{
             return $this->redirect("/index.php?r=site/login");
        }
}

=========the view is:
                 <?php $form = ActiveForm::begin(['id' => 'form-loan',
                                                  'fieldConfig' => [  'template'=>"{input}\n{error}",   ],
                                ]);
                 ?>
                         <?= $form->field($model,'bidder')->hiddenInput(['style'=>'width:240px']);?>
                  <?php ActiveForm::end(); ?>

=========at last,here is my FillInvestForm

class FillInvestForm extends Model
{
    public $amount;
    public $phone;
    public $loan_rate;
    //public $invest_fee;
    public $wmstat;   
 
    public $loanid;
    public $bidder;
    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
    ['loanid',
    'bidder',
    'amount',
    'phone',
    'loan_rate',
    'wmstat'],'required'  ];
    }

    public function attributeLabels()
    {
        return [
    'loanid'=>'',
    'bidder'=>'',
    'amount'=>'',
    'phone'=>'',
    'loan_rate'=>'',
    'wmstat'=>''];
    }

    public function makeInvest()
    {
        Yii::info("####".VarDumper::dumpAsString($this->attributes));
        if ($this->validate()) {
            return Invest::create($this->attributes);
        }

        return -1;
    }
}

======it is simple. but when i refer to invest/bidit&loanid=1
i jsut got the error as it it in the title. this is the whole stack:======

2015-04-01 18:14:31 [61.135.152.208][5][326330r588imhfs6853n90suv4][error][yii\base\ErrorException:256] exception 'yii\base\ErrorExcepti
on' with message 'Exception 'ReflectionException' with message 'Class bidder does not exist' 

in /home/www/womitest/vendor/yiisoft/yii2/di/Container.php:408

Stack trace:
#0 /home/www/womitest/vendor/yiisoft/yii2/di/Container.php(408): ReflectionClass->__construct('bidder')
#1 /home/www/womitest/vendor/yiisoft/yii2/di/Container.php(354): yii\di\Container->getDependencies('bidder')
#2 /home/www/womitest/vendor/yiisoft/yii2/di/Container.php(147): yii\di\Container->build('bidder', Array, Array)
#3 /home/www/womitest/vendor/yiisoft/yii2/BaseYii.php(344): yii\di\Container->get('bidder', Array, Array)
#4 /home/www/womitest/vendor/yiisoft/yii2/validators/Validator.php(204): yii\BaseYii::createObject(Array)
#5 /home/www/womitest/vendor/yiisoft/yii2/base/Model.php(422): yii\validators\Validator::createValidator('bidder', Object(frontend\models\FillInvestForm), Array, Array)
#6 /home/www/womitest/vendor/yiisoft/yii2/base/Model.php(386): yii\base\Model->createValidators()
#7 /home/www/womitest/vendor/yiisoft/yii2/base/Model.php(184): yii\base\Model->getValidators()
#8 /home/www/womitest/vendor/yiisoft/yii2/base/Model.php(715): yii\base\Model->scenarios()
#9 /home/www/womitest/vendor/yiisoft/yii2/widgets/ActiveField.php(699): yii\base\Model->activeAttributes()
#10 /home/www/womitest/vendor/yiisoft/yii2/widgets/ActiveField.php(202): yii\widgets\ActiveField->getClientOptions()
#11 /home/www/womitest/vendor/yiisoft/yii2/widgets/ActiveField.php(193): yii\widgets\ActiveField->begin()
#12 /home/www/womitest/vendor/yiisoft/yii2-bootstrap/ActiveField.php(188): yii\widgets\ActiveField->render(NULL)
#13 /home/www/womitest/vendor/yiisoft/yii2/widgets/ActiveField.php(149): yii\bootstrap\ActiveField->render()
#14 /home/www/womitest/frontend/themes/default/invest/a.php(21): yii\widgets\ActiveField->__toString()
#15 /home/www/womitest/vendor/yiisoft/yii2/base/View.php(325): require('/home/www/womit...')
#16 /home/www/womitest/vendor/yiisoft/yii2/base/View.php(247): yii\base\View->renderPhpFile('/home/www/womit...', Array)
#17 /home/www/womitest/vendor/yiisoft/yii2/base/View.php(149): yii\base\View->renderFile('/home/www/womit...', Array, Object(frontend\controllers\InvestController))
#18 /home/www/womitest/vendor/yiisoft/yii2/base/Controller.php(367): yii\base\View->render('a', Array, Object(frontend\controllers\InvestController))
#19 /home/www/womitest/frontend/controllers/InvestController.php(50): yii\base\Controller->render('a', Array)

======
can anyone give me some hints?
i google all the day.but got nothing,any help will be appretiated!

**Comment by dmeroff** [comment]
Closed since this question is not about Yii2-user. You should ask such questions on Yii forums or StackOverFlow, but not in Yii2 extension repository.
