### ISSUE TITLE
Contribution - Guide "How to use Yii2-user with Yii2 advanced proyect template"

### ISSUE THREAD

**Issue by tecnologiaterabyte** [dektrium/yii2-user#335]
INSTALLATION
------------

### Install from an Archive File

Extract the archive file downloaded from [yiiframework.com](http://www.yiiframework.com/download/) to
a directory named `advanced` that is directly under the Web root.

Then follow the instructions given in "GETTING STARTED".

### Install via Composer

If you do not have [Composer](http://getcomposer.org/), you may install it by following the instructions
at [getcomposer.org](http://getcomposer.org/doc/00-intro.md#installation-nix).

You can then install the application using the following command:

~~~
php composer.phar global require "fxp/composer-asset-plugin:1.0.0"
php composer.phar create-project --prefer-dist --stability=dev yiisoft/yii2-app-advanced advanced
~~~

GETTING STARTED
---------------

After you install the application, you have to conduct the following steps to initialize
the installed application. You only need to do these once for all.

1. Run command `init` to initialize the application with a specific environment.
2. Create a new database and adjust the `components['db']` configuration in `common/config/main-local.php` accordingly.
3. Set document roots of your Web server:

- for frontend `/path/to/yii-application/frontend/web/` and using the URL `http://frontend/`
- for backend `/path/to/yii-application/backend/web/` and using the URL `http://backend/`

To login into the application, you need to first sign up, with any of your email address, username and password.
Then, you can login into the application with same email address and password at any time.

ADD .htacess ROOT DIRECTORY (Backend - [/admin]) - (Frontend - [/])
-------------------------------------------------------------------

/ Root Directory .htaccess yii2-check-advanced

    # prevent directory listings
    Options -Indexes
    IndexIgnore */*
    
    # follow symbolic links
    Options FollowSymlinks
    RewriteEngine on
    
    RewriteRule ^admin(/.+)?$ /backend/web/$1 [L,PT]
    RewriteRule ^(admin)/$ /$1 [L,R=301]
    RewriteRule ^(.+)?$ /frontend/web/$1

ADD .htacess BACKEND WEB DIRECTORY
----------------------------------

/backend/web Backend Web Directory .htaccess yii2-check-advanced

    # if a directory or a file exists, use the request directly
    # otherwise forward the request to index.php
    RewriteCond %{REQUEST_FILENAME} !-f
    RewriteCond %{REQUEST_FILENAME} !-d
    RewriteRule . index.php

ADD .htacess FRONTEND WEB DIRECTORY
-----------------------------------

/frontend/web Frontend Web Directory .htaccess yii2-check-advanced

    # if a directory or a file exists, use the request directly
    # otherwise forward the request to index.php
    RewriteCond %{REQUEST_FILENAME} !-f
    RewriteCond %{REQUEST_FILENAME} !-d
    RewriteRule . index.php
    
- INSTALL EXTENSION YII2-USER
-----------------------------

### Install via Composer

    composer require "dektrium/yii2-user:0.9.*@dev"
    
### Update database schema
    
    php yii migrate/up --migrationPath=@vendor/dektrium/yii2-user/migrations

### common/config/main.php

       'components' => [
           // Configuration Urls Managers //
           'urlManager' => [
               'enablePrettyUrl' => true,
               'suffix'=>'.html',
               'showScriptName' => false,
           ],
       ],

### backend/config/main.php
    
        'modules' => [
            // Configuration Yii2-User Backend //
            'user' => [
                'class' => 'dektrium\user\Module',
                'enableFlashMessages' => false,
                'enableRegistration' => false,
                'enableUnconfirmedLogin' => false,
                'confirmWithin' => 21600,
                'cost' => 12,
                'admins' => ['admin']
            ],
        ],
        'components' => [
            // Configuration Yii2-User Backend //
            'user' => [
                'enableAutoLogin' => true,
                'identityCookie' => [
                    'name' => '_backendIdentity',
                    'path' => '/admin',
                    'httpOnly' => true,
                ],
            ],
        ],
        
    ### backend/config/main-local.php     
        
        'components' => [
            // Configuration Request Backend [Yii2-User] //
            'request' => [
                // !!! insert a secret key in the following (if it is empty) - this is required by cookie validation
                'baseUrl' => '/admin',
                'enableCookieValidation' => true,
                'enableCsrfValidation' => true,
                'cookieValidationKey' => 'OJp79x4y2u4D017tKrSnNEcFwKOt__I6',
                'csrfParam' => '_backendCSRF',
                'csrfCookie' => [
                    'httpOnly' => true,
                    'path' => '/admin',
                ],
            ],
            // Configuration Session Backend [Yii2-User] //
            'session' => [
                'name' => 'BACKENDSESSID',
                'cookieParams' => [
                    'httpOnly' => true,
                    'path' => '/admin',
                ],
            ],        
        ],        

### backend/views/layouts/main.php
    
        if (Yii::$app->user->isGuest) {
            $menuItems[] = ['label' => 'Login', 'url' => ['/user/security/login']];
            } else {
                $menuItems[] = [
                    'label' => 'Logout (' . Yii::$app->user->identity->username . ')',
                    'url' => ['/user/security/logout'],
                    'linkOptions' => ['data-method' => 'post']
                ];
        }    
 
### frontend/config/main.php
     
        'modules' => [
            // Configuration Yii2-User Frontend //
            'user' => [
                'class' => 'dektrium\user\Module',
                'enableFlashMessages' => false,
                'enableRegistration' => false,
                'enableUnconfirmedLogin' => false,
                'confirmWithin' => 21600,
                'cost' => 12,
            ],
        ],  
        'components' => [
            // Configuration Yii2-User Frontend //
            'user' => [
                'enableAutoLogin' => true,
                'identityCookie' => [
                    'name' => '_backendIdentity',
                    'path' => '/admin',
                    'httpOnly' => true,
                ],
            ],
        ],       
         
    ### frontend/config/main-local.php   
          
        'components' => [
            // Configuration Request Frontend [Yii2-User] //
            'request' => [
                // !!! insert a secret key in the following (if it is empty) - this is required by cookie validation
                'baseUrl' => '',
                'enableCookieValidation' => true,
                'cookieValidationKey' => 'OSpRM5C0MCVbCEn6tvPUh3zmAH1JM3LM',
                'csrfParam' => '_frontendCSRF',
                'csrfCookie' => [
                    'httpOnly' => true,
                    'path' => '/',
                ],
            ],
            // Configuration Session Frontend [Yii2-User] //
            'session' => [
                'name' => 'FRONTENDSESSID',
                'cookieParams' => [
                    'path' => '/',
                ],
            ],            
        ],     

### frontend/views/layouts/main.php
    
        if (Yii::$app->user->isGuest) {
            $menuItems[] = ['label' => 'Signup', 'url' => ['/user/registration/register']];
            $menuItems[] = ['label' => 'Login', 'url' => ['/user/security/login']];
            } else {
                $menuItems[] = [
                    'label' => 'Logout (' . Yii::$app->user->identity->username . ')',
                    'url' => ['/user/security/logout'],
                    'linkOptions' => ['data-method' => 'post']
                ];
        }

**Comment by thiagotalma** [comment]
Nice.

It is not necessary to repeat the parameters are the same as common.

I suggest you change the value of the "cookieValidationKey" by "YOUR_KEY_HERE."

**Comment by thiagotalma** [comment]
Perfectly.

Bur what I meant is that not once set a parameter in `common/main` is not necessary to repeat it in the `frontend/main` and `backend/main`.

**Comment by tecnologiaterabyte** [comment]
Of course, I repeat settings yii2-user in backend and frontend, for example to disable logging of users in the backend, and disable access to the admin in the frontend panel, if it comes to that, anyway place all suggestions and make changes the idea is to make the best configuration

**Comment by dmeroff** [comment]
Done! Thank you for your contribution.

**Comment by distancelove10** [comment]
i am do it the same following about,but when i access register,i received message An internal server error occurred.

**Comment by thiagotalma** [comment]
Please enable debug to see the details of the error.

**Comment by loveorigami** [comment]
@distancelove10 I have similar problem on server
* I am install yii2. Upload to server. All works good.
* Next I config url manageк and can enter to site.com and site.com/admin
![admin01](https://cloud.githubusercontent.com/assets/98164/7920872/42bc4798-08aa-11e5-84de-3edd854aa0fc.jpg)

* Next I am add in composer
```php
"dektrium/yii2-user": "0.9.*@dev"
```
* composer up - on local works good
* Only folder vendor upload to server. Not configurating files.
* And have error after request to site.com/admin
![admin2](https://cloud.githubusercontent.com/assets/98164/7920992/15f4ca36-08ab-11e5-95ef-d83339e12ed6.jpg)

* How can this be? I do not understand

Tell me how to fix it. Thanks!

**Comment by loveorigami** [comment]
After some time I can to site.com/admin, but not get  site.com.
After this I redirecting to site.com/admin...

here link http://yii.loveorigami.info/admin

**Comment by msushil** [comment]
how can I change the layout like we overwrite the theme of the view of this module

**Comment by paskuale75** [comment]
point 3 : create two document roots ... howto ? Document Rott can be only one on apache or not ?
