### ISSUE TITLE
Allow page redirect after login to be set

### ISSUE THREAD

**Issue by jas0995** [dektrium/yii2-user#337]
When a user is successfully logged in, yii2-user is hard coded to redirect to home via...

    public function actionLogin()
    {
        if (!\Yii::$app->user->isGuest) {
            $this->goHome();
        }

It would be very nice to be able to specify what page the user would be redirect to after sucesfull login.

In my case, after login, I would like to redirect them to a 'My Account' page, but that might not work for everyone...

**Comment by thiagotalma** [comment]
The best solution for YOU is to override the controller: https://github.com/dektrium/yii2-user/blob/master/docs/overriding-controllers.md

**Comment by jas0995** [comment]
I was looking at doing that after I determined that the redirect was hard coded.  I am still sorting out how the override stuff works.

But I figured I would make a suggestion as well, since I figured I might not be the only one that wants to redirect somewhere else... 

Thanks for your nudge that I was on the right path.

-John

**Comment by thiagotalma** [comment]
Do not get me wrong, I just wanted to help. :smile: 

Your need is immediate and this demand, if executed, will take a long time.

99% of projects redirecting to the home.

**Comment by jas0995** [comment]
No problem, I understand.

I like yii2-user, and I expect I will need to override several things because my requirements are somewhat specific.  I just have not done much work with yii2 yet, and not understand all the details with overriding classes yet.

I think overriding this will be a good start for me!!

Thank you
-John

**Comment by dmeroff** [comment]
Yes, at the moment the only way is overriding controllers. But in `1.0.0-alpha` I'll introduce events inside of controllers and models, and you'll be able to hook into controller and redirect user even without overriding the whole controller.

**Comment by savjignesh** [comment]
add this to web.php

'components' => [
       
        'user' => [
            //'identityClass' => 'common\models\User',
            'identityClass' => 'dektrium\user\models\User',
            'enableAutoLogin' => true,
        ],

**Comment by abdulmanan7** [comment]
Do we have any controller event for After Login .
I see here
https://github.com/dektrium/yii2-user/blob/master/docs/using-controller-events.md

for Registration
