### ISSUE TITLE
Feature Filters Backend and Frontend.

### ISSUE THREAD

**Issue by tecnologiaterabyte** [dektrium/yii2-user#338]
Hi, @dmeroff, a better way to apply filters is by actions (https://github.com/dektrium/yii2-user/blob/master/docs/available-actions.md), not to block the complete of controller actions.

Example Code:

config/common.php:

            'as backend' => [
                'class' => 'dektrium\user\filters\BackendFilter',
                'actions' => ['register'], // actions a block.
            ],

dektrium/user/filters/BackendFilter.php

    <?php

    namespace dektrium\user\filters;

    class BackendFilter extends \yii\base\ActionFilter
    {

        public $actions;

        /**
        * @param \yii\base\Action $action
        */

        public function beforeAction($action)
        {
            if (in_array($action->controller->action->id, $this->actions)) {
                throw new \yii\web\NotFoundHttpException('Not found');
            }
        
            return true;
        }
    }

also check this other solution to test both codeception and both work well, this is by route:

Example Code:

config/common.php:

            'as backend' => [
                'class' => 'dektrium\user\filters\BackendFilter',
                'actions' => ['user/registration/register'],
            ],

dektrium/user/filters/BackendFilter.php:

        class BackendFilter extends \yii\base\ActionFilter
        {
            public $actions;
            /**
           * @param \yii\base\Action $action
           */

           public function beforeAction($action)
            {
                if (in_array($action->controller->route, $this->actions)) {
                    throw new \yii\web\NotFoundHttpException('Not found');
                }
        
               return true;
            }
        }

Note: Sorry for my bad English, is google translator :)

**Comment by dmeroff** [comment]
You can do this with current version of filter as follows:
```php
'as backend' => [
     'class' => 'dektrium\user\filters\BackendFilter',
     'only'  => ['register'], // actions a block.
],
```

**Comment by tecnologiaterabyte** [comment]
Does not work, does not block the action,

Thanks in advance,

**Comment by tecnologiaterabyte** [comment]
Work Fine:

Example Code:

    'as backend' => [
         'class' => 'dektrium\user\filters\BackendFilter',
         'only'  => ['registration/register'], // actions a block.
],
