### ISSUE TITLE
confirmation code duplication with db

### ISSUE THREAD

**Issue by ajkosh** [dektrium/yii2-user#340]
if i m creating account and i did not get confirmation message,and i try again for resend.
if i try this many times it is creating to many tokens with user_id,even only one token is using for confirmation,so i think it is wrong to add new token again and again,we should check if there is no token with related user_id then you should add otherwise you should update code and time

**Comment by dmeroff** [comment]
I'll fix this. Thanks for reporting.

**Comment by dmeroff** [comment]
Fixed! Sorry for the delay.
