### ISSUE TITLE
problem urlPrefix.

### ISSUE THREAD

**Issue by tecnologiaterabyte** [dektrium/yii2-user#343]
Hi @dmeroff 'urlPrefix' => '/' work for '/login' no works for 'admin/index',

Thks in Advance,

**Comment by dmeroff** [comment]
It's ok, because there are no rules for `user/admin/index` route. You should add new rule to the `urlRules` property (like `admin/<action\w+>` => `admin/<action>`).

**Comment by tecnologiaterabyte** [comment]
Ok Thks.
