### ISSUE TITLE
Error overriding model Profile

### ISSUE THREAD

**Issue by marg8com** [dektrium/yii2-user#344]
When i try to override the Profile model, i get this error:

    Call to a member function load() on a non-object

In the config file i have added this line:

    'user' => [
    	 'class' => 'dektrium\user\Module',
    	 'modelMap' => [
        	'Profile' => 'app\models\Profile',
    	 ],
    	 'admins' => ['admin'],
    	 'enableConfirmation' => false,
    	 'enableRegistration' => false,
    ],

and this is my Profile model

    namespace app\models;
    use dektrium\user\models\Profile as BaseProfile;
    
    class Profile extends BaseProfile
    {	
        public static function tableName()
        {
            return 'Producer';
        }
    
    public function rules()
    {
        return [
            [['bornDate'], 'safe'],
            [['user_id'], 'integer'],
            [['textId', 'bornCity', 'photo'], 'string', 'max' => 150],
            [['firstName', 'lastName', 'bornCountry', 'address'], 'string', 'max' => 100],
            [['bornState'], 'string', 'max' => 2],
            [['city'], 'string', 'max' => 95],
            [['codiceFiscale'], 'string', 'max' => 16],
            [['vat', 'phone'], 'string', 'max' => 13],
            [['iban'], 'string', 'max' => 35],
            [['paypalAccount'], 'string', 'max' => 45],
            [['textId'], 'unique']
        ];
    }
    
    
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'textId' => 'Text ID',
            'firstName' => 'First Name',
            'lastName' => 'Last Name',
            'bornCity' => 'Born City',
            'bornState' => 'Born State',
            'bornCountry' => 'Born Country',
            'bornDate' => 'Born Date',
            'address' => 'Address',
            'city' => 'City',
            'codiceFiscale' => 'Codice Fiscale',
            'vat' => 'Vat',
            'iban' => 'Iban',
            'paypalAccount' => 'Paypal Account',
            'photo' => 'Photo',
            'phone' => 'Phone',
            'user_id' => 'User ID',
        ];
    }
    
    
    public function getPayment()
    {
        return $this->hasOne(Payment::className(), ['id' => 'id']);
    }
    
    public function getProducerCatalogs()
    {
        return $this->hasMany(ProducerCatalog::className(), ['producerId' => 'id']);
    }
    }

In the attached file there is the detailed error.
Thanks

![schermata 2015-04-10 alle 13 12 23](https://cloud.githubusercontent.com/assets/11753528/7086609/454845c0-df83-11e4-8523-3542ea28aab9.png)

**Comment by thiagotalma** [comment]
The error is saying that you are calling a method for a non-existent object.

You need to make sure that `$profile` is not null before attempting to load.

```php
if ($profile != null && $profile->load(...) && $profile->save()) {
...
}
```

**Comment by marg8com** [comment]
Thanks thiagotalma, i've find the real problem:
the object was null because in my Producers table there was not any record associated with user_id.
