### ISSUE TITLE
Error when install in advanced tamplate

### ISSUE THREAD

**Issue by goffyara** [dektrium/yii2-user#345]
#### Hi!
When i add to frontend config this (how in [docs](https://github.com/dektrium/yii2-user/blob/master/docs/usage-with-advanced-template.md)):
```php
 'modules' => [
    'user' => [
        // following line will restrict access to admin page
        'as frontend' => 'dektrium\user\filters\FrontendFilter',
    ],
],
```
i see this error:
> ReflectionException
> Class dektrium\user\filters\FrontendFilter does not exist
 > In sitename\vendor\yiisoft\yii2\di\Container.php

What i doing wrong? Thanks.

**Comment by dmeroff** [comment]
You should update your `yii2-user` installation.

**Comment by QuinLena15** [comment]
I see error: Class dektrium\user\filters\FrontendFilter does not exist
What to do?

**Comment by dmeroff** [comment]
@QuinLena15 as I've already said: you should update the module.

**Comment by neilworley** [comment]
Hi I get the same error and I have updated the module.

**Comment by dirttech** [comment]
@dmeroff What do you mean by updating 'module'?

**Comment by Evstigneev** [comment]
@dirttech composer.phar update

**Comment by ROOPARAVICHANDRAN** [comment]
me also getting the same error,



ReflectionException

Class dektrium\user\filters\FrontendFilter does not exist

i updated the composer to.. but still stuck with same error...
can any body can help me to solve dis ...

**Comment by ROOPARAVICHANDRAN** [comment]
how to upadte yii2/user module??

**Comment by lalwanikamal165** [comment]
ERROR NOT GOING AFTER UPDATING ??
WHAT TO DO??

**Comment by mgitech** [comment]
same error here also any help how to setup module

**Comment by lalwanikamal165** [comment]
hi , i hosted my advance yii application, www.myrepairgeek.com.

**Comment by lalwanikamal165** [comment]
@mgitech  use "yii2-advanced-one-domain-config" github project to configure your project.
