### ISSUE TITLE
cant't use the SecurityController's action

### ISSUE THREAD

**Issue by xiaomalover** [dektrium/yii2-user#350]
If config urlManager like 'enablePrettyUrl' => true, controller name 'security' will auto hide,lead to can't find the action,(eg: '/user/security/login' will become 'user/login' and cant login)

**Comment by dmeroff** [comment]
Can't you only access those actions when `enablePrettyUrl` is true? Or you can't access actions even without `enablePrettyUrl` enabled?

**Comment by xiaomalover** [comment]
I can access those actions normally without enablePrettyUrl enabled, but when enablePrettyUrl is true,I cant't access SecurityController's action, because if when enablePrettyUrl is true, the controllerid security will auto hide (eg: '/user/security/login' will become 'user/login' and cant login), I try rename the controller id like securitys,it can work normally, Whether security is the Yii's reserved field

**Comment by xiaomalover** [comment]
It's funny, now can work normally. I close the issues now, by the way thank you very much.
