### ISSUE TITLE
ClientInterface: implement or remove defaultTitle()

### ISSUE THREAD

**Issue by maxxer** [dektrium/yii2-user#355]
For Yandex and VKontakte you added the `defaultTitle()` method which returns a localized page name. I've two doubts:
* why this is not implemented in other clients?
* is it really needed for the title to be localized? An app name is always the same, despite of the locale (facebook, google, twitter...)

**Comment by dmeroff** [comment]
I can explain: in Russia both Yandex and VKontakte are known and used in russian language ("Яндекс" and "ВКонтакте"), and in projects uses russian language as default they both needs to be translated. However international titles (facebook, google, etc) have no translations.

**Comment by maxxer** [comment]
thanks
