### ISSUE TITLE
Support for Google Authenticator ?

### ISSUE THREAD

**Issue by marsuboss** [dektrium/yii2-user#358]
Is it possible to add Google Authenticator ?

See : https://github.com/sonata-project/GoogleAuthenticator or https://github.com/PHPGangsta/GoogleAuthenticator

**Comment by thiagotalma** [comment]
@marsuboss You can send a PR.
It would be a great contribution.

**Comment by dmeroff** [comment]
No, there is no plans for implementing this. You can try to add it yourself and then send a pull-request with a guide of how to include it in yii2-user.
