### ISSUE TITLE
Improve image handling

### ISSUE THREAD

**Issue by invaderhd** [dektrium/yii2-user#363]
In my most recent project I need to add a profile picture to user profile, after I done that I realize that you use something like this:
```
<img src="http://gravatar.com/avatar/<?= $user->profile->gravatar_id ?>?s=24" />
```
In some views, since now in my profile I have a field called photo I had to override some of your views to display the correct image.

I think you can add a getPhoto() function to profile model and this function will return the profile picture, so if a user add a new field to profile model to handle the user picture, instead of need to override multiple view we only need to override this getPhoto function and everything works.

An example in profile model
```
public function getPhoto($size = 200){
        if(!empty($this->photo))
            return $this->photo;
        else if(!empty($this->gravatar_id))
            return "http://gravatar.com/avatar/$this->gravatar_id?s=$size&d=".urlencode(\Yii::$app->params['defaultUserPhoto']);
        else{  
            return \Yii::$app->params['defaultUserPhoto'];
        }
    }
```
Then in your views instead of using this:
```
<img src="http://gravatar.com/avatar/<?= $user->profile->gravatar_id ?>?s=24" />
```
you should use something like this:
```
<img src="<?= $user->profile->getPhoto(24) ?>" width="24px" height="24px" />
```

As you can see the getPhoto function can receive a size argument that will be use on gravatar, maybe is even better if we can pass the width and height. In your views you should add the width and height to img tag to prevent bigger images from break your design.

**Comment by dmeroff** [comment]
Profile image handling will be refactored in 1.0.0-alpha. See #174
