### ISSUE TITLE
Getting unknown property: common\models\User::status

### ISSUE THREAD

**Issue by JPRusaki** [dektrium/yii2-user#364]
I get this error when I try to create a new user. I followed the latest documentation and I am implementing advanced template.

exception 'yii\base\UnknownPropertyException' with message 'Getting unknown property: common\models\User::status' in D:\Programes instal.lats\xampp\htdocs\yiitester\vendor\yiisoft\yii2\base\Component.php:143

**Comment by dmeroff** [comment]
Yii2-user does not use either `common\models\User` model class or `status` field. This error may only appear if you will access default yii2-app-advanced registration/login pages. In case of yii2-user you should access /user/register/registration and /user/security/login to register and login.

**Comment by hicham-es** [comment]
worked when i changed " /user/register/registration" to " /user/registration/register"
