### ISSUE TITLE
"independent sessions in one domain" not working

### ISSUE THREAD

**Issue by dbd5** [dektrium/yii2-user#367]
Hello,

Thanks for your work putting in this extension together.

I believe I have followed your setup instructions correctly for "independent sessions in one domain".
I am using Kartik's advanced Yii2-app-practical-a which is designed for a single domain and supports the structure front (http://domain/app) and backend (http://domain/backend)

Unfortunately when I change the path setting for backend to anything but "/", logon fails. I have tried both "/admin" and "/backend"

        'user' => [
            'identityCookie' => [
                'name'     => '_backendIdentity',
                'path'     => '/admin',
                'httpOnly' => true,
            ],
        ], 

I believe leaving the path as "/" defeats the objective completely, please advice what I might be doing wrong.

Regards,

Adam

**Comment by tecnologiaterabyte** [comment]
Example Backend Config:

    ### backend/config/main.php
    
    return [
        'id' => 'app-backend',
        'basePath' => dirname(__DIR__),
        'controllerNamespace' => 'backend\controllers',
        'bootstrap' => ['log'],
        'modules' => [
            // Configuration [Yii2-User Backend] //
            'user' => [
                'class' => 'dektrium\user\Module',
                'as backend' => [
                    'class' => 'dektrium\user\filters\BackendFilter',
                    'only' => ['registration/register'], // Block View Register Backend
                ],
            ],
        ],
        'components' => [
            // Configuración [User Cookies Backend] //
            'user' => [
                'identityCookie' => [
                    'name' => '_backendIdentity',
                    'path' => '/admin',
                    'httpOnly' => true,
                ],
            ],
            // Configuración [Yii2-Log Backend] //
            'log' => [
                'traceLevel' => YII_DEBUG ? 3 : 0,
                'targets' => [
                    [
                        'class' => 'yii\log\FileTarget',
                        'levels' => ['error', 'warning'],
                    ],
                ],
            ],
            // Configuración [Yii2-Error Backend] //
            'errorHandler' => [
                'errorAction' => 'site/error',
            ],
            // Configuration [Session Backend] //
            'session' => [
                'name' => 'BACKENDSESSID',
                'cookieParams' => [
                    'httpOnly' => true,
                    'path' => '/admin',
                ],
            ],
        ],
        'params' => $params,
    ];
        
    ### backend/config/main-local.php     
        
    $config = [
        'components' => [
            // Configuration [Yii2-Request Backend] //
            'request' => [
                // !!! insert a secret key in the following (if it is empty) - this is required by cookie validation
                'baseUrl' => '/admin',
                'enableCookieValidation' => true,
                'enableCsrfValidation' => true,
                'cookieValidationKey' => 'Your Cookie Validation Key',
                'csrfParam' => '_backendCSRF',
                'csrfCookie' => [
                    'httpOnly' => true,
                    'path' => '/admin',
                ],
            ],
            // Configuration [Yii2-Session Backend] //
            'session' => [
                'name' => 'BACKENDSESSID',
                'cookieParams' => [
                    'httpOnly' => true,
                    'path' => '/admin',
                ],
            ],
        ],
    ];

    if (!YII_ENV_TEST) {
        // configuration adjustments for 'dev' environment
        $config['bootstrap'][] = 'debug';
        $config['modules']['debug'] = 'yii\debug\Module';

        $config['bootstrap'][] = 'gii';
        $config['modules']['gii'] = 'yii\gii\Module';
    }

    return $config;
