### ISSUE TITLE
[proposal] use DateTime instead of Integer with Timestamp for Date Fields

### ISSUE THREAD

**Issue by thyseus** [dektrium/yii2-user#372]
Currently we use int(11) containing the UNIX Timestamp for all the date fields (created_at, ...). This is fine, but using the DateTime format of the corresponding SQL database would be better in my opinion. 

If you agree, i would write a migration, refactor the code and tests for this.

**Comment by blackwolfinsane** [comment]
+ 1

**Comment by dmeroff** [comment]
What is the pros of this change? Imo it is fine to use integer for "system" datetime fields. Could you please provide an example of the problem that this change will solve?

**Comment by thyseus** [comment]
There is no technical advantage (nowadays in times of computing power and memory abundance, at least), it is just a matter of style. Actually, to have it "academically correct" i propose the DateTime type according to this page: 

http://www.made2mentor.com/2011/05/date-vs-integer-datatypes-as-primary-key-for-date-dimensions/

It also is the most space efficient type:

Decimal(8,0): 5 bytes
Date: 3 bytes, 0001-01-01 through 9999-12-31
Int: 4 bytes

**Comment by thiagotalma** [comment]
The article deals with the use of dates as the primary key of a table.

I see no reason for the change.

**Comment by dmeroff** [comment]
I also see no reason for this change, since it will not give any profit.
