### ISSUE TITLE
path /user/security/login not working -> 404

### ISSUE THREAD

**Issue by scoutbox** [dektrium/yii2-user#375]
Hi
I've tried to setup this modul several times, but it's not working, because, I'm sure, I've missed something.
But from the beginning:
I work on a windows7 with usbw as webserver.
I use  the step by step description on
https://github.com/dektrium/yii2-user/blob/master/docs/getting-started.md

`composer create-project --prefer-dist yiisoft/yii2-app-basic yii2_user` ->  everything OK
no `php init` possible
I made a MySQL-DB and changed appdir\config\db.php to this settings

Step 1
`composer require "dektrium/yii2-user:0.9.*@dev"` -> OK

Setp 2
in appdir\config\web.php I deleted the use-section in components
and copied the moduls code after the components section straight before 'params'

Step 3
`php yii migrate/up --migrationPath=@vendor/dektrium/yii2-user/migrations`
-> Migrated up successfully.

Now I start my browser with
e.g. `http://127.0.0.1/appdir/web/user/registration/register`
but the browser comes up with
`404 Not Found`
all other actions from
`https://github.com/dektrium/yii2-user/blob/master/docs/available-actions.md`
do the same ;(

So my questions are:
what did I forget?
Is there a discussionforum for yii2-user to searching for help?

Thank you.

**Comment by dmeroff** [comment]
Yes there is a [Gitter chat](https://gitter.im/dektrium/yii2-user) and a [Google Group](https://groups.google.com/forum/#!forum/yii2-user). Could you please duplicate your question in one of them, because Github is for reporting issues but not for questions.
