### ISSUE TITLE
PDO Exception - No database selected

### ISSUE THREAD

**Issue by dbd5** [dektrium/yii2-user#379]
Hello,

I'm having this strange error after integration, could you point me in the right direction as to what could be wrong?

![screen shot 2015-05-17 at 1 59 15 pm](https://cloud.githubusercontent.com/assets/9496750/7670465/60d4a96e-fc9d-11e4-8bcd-238b8fe6faad.png)

Regards,

Adam

**Comment by thiagotalma** [comment]
This is not a yii2-user error.

**Comment by dbd5** [comment]
I agree totally, my bad - resolved

Adam
