### ISSUE TITLE
404, admin page not found

### ISSUE THREAD

**Issue by Boco10** [dektrium/yii2-user#383]
Log:

15:31:56.209	error	yii\web\HttpException:404	exception 'yii\web\NotFoundHttpException' with message 'Not found' in C:\xampp\htdocs\wizz\vendor\dektrium\yii2-user\filters\FrontendFilter.php:33 Stack trace: #0 C:\xampp\htdocs\wizz\vendor\yiisoft\yii2\base\ActionFilter.php(71): dektrium\user\filters\FrontendFilter->beforeAction(Object(yii\base\InlineAction)) #1 [internal function]: yii\base\ActionFilter->beforeFilter(Object(yii\base\ActionEvent)) #2 C:\xampp\htdocs\wizz\vendor\yiisoft\yii2\base\Component.php(541): call_user_func(Array, Object(yii\base\ActionEvent)) #3 C:\xampp\htdocs\wizz\vendor\yiisoft\yii2\base\Module.php(607): yii\base\Component->trigger('beforeAction', Object(yii\base\ActionEvent)) #4 C:\xampp\htdocs\wizz\vendor\yiisoft\yii2\base\Controller.php(139): yii\base\Module->beforeAction(Object(yii\base\InlineAction)) #5 C:\xampp\htdocs\wizz\vendor\yiisoft\yii2\base\Module.php(455): yii\base\Controller->runAction('index', Array) #6 C:\xampp\htdocs\wizz\vendor\yiisoft\yii2\web\Application.php(84): yii\base\Module->runAction('user/admin/inde...', Array) #7 C:\xampp\htdocs\wizz\vendor\yiisoft\yii2\base\Application.php(375): yii\web\Application->handleRequest(Object(yii\web\Request)) #8 C:\xampp\htdocs\wizz\frontend\web\index.php(18): yii\base\Application->run() #9 {main}

Code:

class FrontendFilter extends \yii\base\ActionFilter
{
    /**
     * @var array
     */
    public $controllers = ['admin'];
    
    /**
     * @param \yii\base\Action $action
     */
    public function beforeAction($action)
    {
        if (in_array($action->controller->id, $this->controllers)) {
            throw new \yii\web\NotFoundHttpException('Not found');
        }
        
        return true;
    }
}

It's working when i comment out the in_array section.
Any idea what's going on?

**Comment by thiagotalma** [comment]
Hello!

This filter has exactly this function: return a 404 error when trying to access the admin through the frontend.

**Comment by Boco10** [comment]
Hmm, i understand now.
If i use it the normal way the problem is:
i can't login with backend, since the security action is denied.
i can't manage user from frontend.

Am i missing any settings, i was using the guilde for sperate session id for backend and frontend.

**Comment by dmeroff** [comment]
@Boco10 there is a problem with this filter, because it does not allow authentication on backend. At the moment you can fix it by configuring behavior as follows:

```php
'modules' => [
    'user' => [
        // following line will restrict access to admin page
        'as backend' => [
            'class' => 'dektrium\user\filters\BackendFilter',
            'controllers' => ['profile', 'recovery', 'registration', 'settings']
    ],
],
```

I'll fix this asap.

**Comment by yonifine** [comment]
Hi dmeroff,

first of all thanks for the great extension. I was facing similar issue when I integrate adminlte with yii2-user. I was not able to login to the admin page. after i used the above fix in the configuration it worked. thanks and keep up the good work

**Comment by dmeroff** [comment]
Fixed.
