### ISSUE TITLE
Logout POST

### ISSUE THREAD

**Issue by vsmelarkod** [dektrium/yii2-user#384]
I created a link in layout/main.php using 

echo Yii::$app->user->isGuest ?
                                        Html::a('<i class="fa fa-lock pr-5"></i>Login', ['/user/security/login']) :
                                        Html::a('<i class="fa fa-unlock pr-5"></i>Logout', ['/user/security/logout'], ['data-method' => 'post']);

Which generated the following after I login - 
a href="/rgcf/web/user/logout" data-method="post"><i class="fa fa-unlock pr-5"></i>Logout</a

I also included <?= Html::csrfMetaTags() ?> in the head of layout/main.php

But, when I click the Logout link, it throws error #405. Method Not Allowed. This url can only handle the following request methods: POST.

Thank you for your guidance.

**Comment by dmeroff** [comment]
That's not yii2-user problem. You don't have YiiAsset included on your pages, which allows to use links to send post requests.
P.S. Please don't use github to ask such kind of questions, instead use our google group or gitter.
