### ISSUE TITLE
Extent "admins" configuration to allow role assignment

### ISSUE THREAD

**Issue by waza-ari** [dektrium/yii2-user#385]
I would like to allow all users with a specific roles to perform user management, instead of manually specifying each and every user in a static configuration file.

Hence I would like to propose an extension, that role names can be specified (for example "@admins"), which allows all users with the role "admins" assigned to perform administrative changes.

**Comment by dmeroff** [comment]
This may be useful, I'll probably implement this.

**Comment by dmeroff** [comment]
Done!
