### ISSUE TITLE
PHP Fatal Error 'yii\base\ErrorException' with message 'Class 'dektrium\user\mig rations\Migration' not found'

### ISSUE THREAD

**Issue by msstoci** [dektrium/yii2-user#386]
C:\xampp\htdocs\gemastik\_protected>php yii migrate/up --migrationPath=@vendor/d
ektrium/user/migrations
Yii Migration Tool (based on Yii v2.0.4)

Total 8 new migrations to be applied:
        m140209_132017_init
        m140403_174025_create_account_table
        m140504_113157_update_tables
        m140504_130429_create_token_table
        m140830_171933_fix_ip_field
        m140830_172703_change_account_table_name
        m141222_110026_update_ip_field
        m141222_135246_alter_username_length

Apply the above migrations? (yes|no) [no]:y
*** applying m140209_132017_init
PHP Fatal Error 'yii\base\ErrorException' with message 'Class 'dektrium\user\mig
rations\Migration' not found'

in C:\xampp\htdocs\gemastik\_protected\vendor\dektrium\user\migrations\m140209_1
32017_init.php:19

Stack trace:
#0 [internal function]: yii\base\ErrorHandler->handleFatalError()
#1 {main}

C:\xampp\htdocs\gemastik\_protected>

**Comment by dmeroff** [comment]
Did you installed yii2-user using composer?

**Comment by dmeroff** [comment]
Closed since no answer was given.

**Comment by mogilka** [comment]
I have the same trouble. Yii2-user installed via composer

**Comment by akhiltanveer** [comment]
C:\xampp\htdocs\isa-usa2>php yii migrate/up --migrationPath=@vendor/yiisoft/vend
or/dektrium/yii2-user/migrations
Yii Migration Tool (based on Yii v2.0.11)

Total 12 new migrations to be applied:
m140209_132017_init
m140403_174025_create_account_table
m140504_113157_update_tables
m140504_130429_create_token_table
m140830_171933_fix_ip_field
m140830_172703_change_account_table_name
m141222_110026_update_ip_field
m141222_135246_alter_username_length
m150614_103145_update_social_account_table
m150623_212711_fix_username_notnull
m151218_234654_add_timezone_to_profile
m160929_103127_add_last_login_at_to_user_table

Apply the above migrations? (yes|no) [no]:yes
*** applying m140209_132017_init
PHP Fatal error: Class 'dektrium\user\migrations\Migration' not found in C:\xam
pp\htdocs\isa-usa2\vendor\yiisoft\vendor\dektrium\yii2-user\migrations\m140209_1
32017_init.php on line 17
PHP Fatal Error 'yii\base\ErrorException' with message 'Class 'dektrium\user\mig
rations\Migration' not found'

in C:\xampp\htdocs\isa-usa2\vendor\yiisoft\vendor\dektrium\yii2-user\migrations
m140209_132017_init.php:17

Stack trace:
#0 [internal function]: yii\base\ErrorHandler->handleFatalError()
#1 {main}

C:\xampp\htdocs\isa-usa2>

same problem here did anyone find solution ? please help

**Comment by vietnux** [comment]
tôi cũng gặp vấn đề này???
