### ISSUE TITLE
Нет перевода в языковых файлах

### ISSUE THREAD

**Issue by zxczxc12** [dektrium/yii2-user#388]
Отсутствует выражение : 
Your account has been created and a message with further instructions has been sent to your email

**Comment by dmeroff** [comment]
В ветке `master` могут быть неточности перевода, рекомендую пользоваться стабильной на данный момент версией (0.9.4). Переводы будут поправлены ближе к релизу, а пока можете прислать пулл-реквест, исправляющий ошибку.
P.S. давайте всё-таки на английском в следующий раз, это всё же международный сайт.
