### ISSUE TITLE
Добавить таблицам модуля уникальный префикс

### ISSUE THREAD

**Issue by gglp** [dektrium/yii2-user#390]
Возможно стоило бы добавить всем таблицам модуля уникальный префикс (например, usr_ или что-то подобное). Также, как сделано, например, в authManager - префикс у всех таблиц auth_ (в добавление к общему для приложения префиксу).

Насколько я понимаю это повлечёт только изменение названий таблиц в моделях на примерно {{%usr_user}} или {{%usr_social_account}}. Ну и изменение внешних ключей для таблиц.

Могу попробовать сделать pull request, хотя раньше ещё не делал.

Я при подключении модуля столкнулся с тем, что у меня уже была таблица account и этим блокировались миграции модуля. Пришлось вручную переименовывать имеющуюся таблицу в базе, а затем возвращать имя обратно. Хорошо что при этом название таблицы модуля изменилось на отличное от account.
При этом, т.к. миграции модуля и миграции общего приложения выполняются в разных потоках, то необходим хитрый порядок выполнения миграций при деплое на внешний сервер: выполняем часть миграций из приложения, затем все из модуля, затем опять часть из приложения - человеческая ошибка практически гарантирована.

**Comment by dmeroff** [comment]
Во-первых, давайте в следующий раз на английском, впредь буду закрывать все issue не на английском.

Во-вторых, к сожалению, просто так взять и поменять названия таблиц уже поздно, так как это может серьезно так поломать обратную совместимость (уже работающие приложения могут иметь собственные внешние ключи на таблицы модуля). И хотя модуль еще не имеет стабильной версии, так ломать совместимость я не буду.
Как вариант можно добавить новое свойство модуля, которое будет хранить префикс таблиц (по умолчанию - ''), и дергать это свойства в местах где устанавливаются имена таблиц. Но как скоро такой патч будет готов, я пока сказать не могу. Если вы готовы предоставить пулл-реквест, буду рад.

В-третьих, что касается порядка миграций - могу посоветовать [вот это расширение](https://github.com/dmstr/yii2-migrate-command), которое позволяет одновременно накатывать миграции из разных мест.
