### ISSUE TITLE
2 предложения по улучшению модуля

### ISSUE THREAD

**Issue by zxczxc12** [dektrium/yii2-user#391]
1) Добавить в документацию по работе с событиями следующий пример ( в конце топика ):
http://www.yiiframework.ru/forum/viewtopic.php?f=19&t=21644&p=150029#p150029

Лично я потратил 4(!!) часа что бы понять как оно работает . Для новичков будет самое оно .

2) Непонятно почему в таком модуле нет опции, что бы при создании юзера сразу не применялось бы какое то правило RBAC для него 

PS На английском не могу из за плохого его знания

**Comment by thiagotalma** [comment]
https://translate.google.com/

**Comment by dmeroff** [comment]
Давайте всё-таки на английском в следующий раз.

1) Документацию добавлю.
2) Посмотрю, что можно сделать.
