### ISSUE TITLE
how can i access profile table attributes from layout after login

### ISSUE THREAD

**Issue by yiqiang** [dektrium/yii2-user#393]
i tried

Yii::$app->getModule('user')->getUser()->profile->getAttribute('gravatar_email');

no working.

**Comment by thiagotalma** [comment]
Try this:

```php
Yii::$app->user->profile->gravatar_email;
```

Or this:

```php
Yii::$app->user->identity->profile->gravatar_email;
```

**Comment by yiqiang** [comment]
Yii::$app->user->identity->profile->gravatar_email; works thanks

**Comment by dmeroff** [comment]
Please use [gitter](https://gitter.im/dektrium/yii2-user) for asking questions.
