### ISSUE TITLE
user/admin/index has error 'Unserialization of configuration schema failed'

### ISSUE THREAD

**Issue by coradite** [dektrium/yii2-user#395]
Hi,

I get the following error when I navigate to the user/admin/index. 

>PHP User Error – yii\base\ErrorException

>Unserialization of configuration schema failed, sha1 of file was da39a3ee5e6b4b0d3255bfef95601890afd80709

 I have narrowed it down to the registration_id column on the grid view. If I comment out the 'format'=>'html' part everything works OK. Is that part correct or am I doing something wrong?

**Comment by dmeroff** [comment]
This is not Yii2-user issue, it seems to be a problem with Yii2 Gridview widget or probably with HtmlPurifier.

**Comment by coradite** [comment]
Ok thanks for the info!

**Comment by sadam-sds** [comment]
@dmeroff . thanks for answer .
