### ISSUE TITLE
Assignments can not be removed

### ISSUE THREAD

**Issue by schmunk42** [dektrium/yii2-user#398]
with latest `yii2-rbac`

Error: `Items cannot be blank`

![bildschirmfoto 2015-06-03 um 05 20 02](https://cloud.githubusercontent.com/assets/649031/7952146/8bab5cfc-09b1-11e5-9de6-7c1aae06a314.png)

**Comment by dmeroff** [comment]
I'll fix this on weekend, too many work right now.

**Comment by dmeroff** [comment]
Fixed in Yii2-rbac.
