### ISSUE TITLE
isAdmin() needs to check if the user is currently logged in

### ISSUE THREAD

**Issue by vsmelarkod** [dektrium/yii2-user#399]
Hi,

I am checking if a user is an admin with the following IF - Yii::$app->user->identity->getIsAdmin() or Yii::$app->user->identity->isAdmin. 

Both of them throws PHP errors if no user is logged in. Can the method check if the user is currently logged in and then return TRUE if they are admin? if not logged in, then return FALSE?

Thank you.

**Comment by philippfrenzel** [comment]
Fails while User identity is none object, Needs to be checked before?!

**Comment by vsmelarkod** [comment]
I want to show "edit" buttons to an administrator only. So, I am trying to use the above commands to check if the logged in user is an admin or not. IF admin, then show edit buttons. But, when no one is logged in, it says "Trying to get property of non-object". Wouldn't it be better if the getIsAdmin() method checks if there is a user logged in first and then check if that user is an admin?

**Comment by vsmelarkod** [comment]
I solved it by using IF(!Yii::$app->user->isGuest && Yii::$app->user->identity->isAdmin). both conditions together like I found in a piece of code. Although I don't see why not check if the user is logged in the isAdmin() method.

**Comment by dmeroff** [comment]
@vsmelarkod this cannot be done in any way: `Yii::$app->user->identity` is a currently *logged in* user. So if user is not logged in there is no identity and we cannot call method on null.
