### ISSUE TITLE
Timeout after login

### ISSUE THREAD

**Issue by yiqiang** [dektrium/yii2-user#400]
by using yii2-user how to logout user after 5 mins such as 'authTimeout' => 5, in fact i have set the rememberFor but it is not working

    'modules' => [
        'user' => [
            'class' => 'dektrium\user\Module',
            'as frontend' => 'dektrium\user\filters\FrontendFilter',
            'rememberFor' => 120,
            'controllerMap' => [
                'settings' => 'frontend\controllers\UserController'
            ],
            'modelMap' => [
                'Profile' => 'common\models\Profile',
            ],
        ],
    ],

**Comment by dmeroff** [comment]
You have to set [authTimeout](http://www.yiiframework.com/doc-2.0/yii-web-user.html#$authTimeout-detail) property of user component to achieve what you want.

**Comment by yiqiang** [comment]
so i directly set this property under modules>user?

**Comment by icemall** [comment]
Adding authTimeout property with 'dektrium\user\Module' class gives out an unknown property error. And still, why rememberFor property won't work?
