### ISSUE TITLE
Problem related to user role.user role is not defined into user table.

### ISSUE THREAD

**Issue by rahulsinh** [dektrium/yii2-user#402]
after signup a confirmation link send to user when user go to the backend and open profile.in this profile not dife the role of user is admin,author,editor and etc. how to use yii-user rbac feature.there are no guidelines for use rbac in yii2-user.

**Comment by dmeroff** [comment]
Please, use [Gitter](https://gitter.im/dektrium/yii2-user) to ask questions.
