### ISSUE TITLE
Login problem when checkbox login-form[rememberMe] is not checked

### ISSUE THREAD

**Issue by Denisis** [dektrium/yii2-user#403]
I've installed yii2 and login module using composer and the following issue occured: 
1. After login attempt without setting "remember me" checkbox, there is a redirect to the index page. 
2. E-mail approve link does't login too. But in this case, after transition to the site, on the first page there is a user name on the top of the page firstly, but actually user does not logged in and after refresh page looks as for guest.
3. If to set checkbox "rememberMe", logged in without problems

**Comment by dmeroff** [comment]
You probably do have problems with sessions, you should find them out and fix them yourself.
