### ISSUE TITLE
There are any way to check is a specific users is online?

### ISSUE THREAD

**Issue by invaderhd** [dektrium/yii2-user#404]
This is not exactly an issue is more a question, there are any way to determine if a specific user is online or not?
This can be very useful in some situations. Like implementing an forum where we show the name of the users currently online.

**Comment by dmeroff** [comment]
No, there is no way to do this. And there will be no feature like this in the future, you have to implement this yourself.

**Comment by fourclub** [comment]
подскажи, каким способом использую твое расширение это проще всего сделать?
