### ISSUE TITLE
How to redirect back to sign-up form

### ISSUE THREAD

**Issue by vinod27ece** [dektrium/yii2-user#405]
Hi, I want to use login with facebook in my sign-up form. After authentication from facebook, I do not want to login user, instead I want to take some more input field from user and then user will be able to login. So how can I implement callback function after authentication with facebook pop-up box get closed.

**Comment by dmeroff** [comment]
Please use [Gitter chat](https://gitter.im/dektrium/yii2-user) to ask questions.
