### ISSUE TITLE
Auth url is wrong

### ISSUE THREAD

**Issue by trbsi** [dektrium/yii2-user#408]
When I go to user/settings/network and try to connect with Facebook or Google it redirects me to
user/settings/connect?authclient=facebook which doesn't exist
It should redirect me to
user/security/auth?authclient=facebook 

I think error is in createClientUrl() in widgets/Connect.php

**Comment by trbsi** [comment]
I guess it should be like this
```
    public function createClientUrl($provider)
    {
        if ($this->isConnected($provider)) 
		{
            return Url::to(['/user/settings/disconnect', 'id' => $this->accounts[$provider->getId()]->id]);
        } 
		else 
		{
            return Url::to(['/user/settings/auth', 'authclient' => $provider->getId()]);
           // return parent::createClientUrl($provider);
        }
    }
```

**Comment by dmeroff** [comment]
You probably have outdated version OR you have overriden `views/settings/networks.php` view file, where connect widget is configured. You have to make sure that `baseAuthUrl` is set to `/user/security/auth`, (https://github.com/dektrium/yii2-user/blob/master/views/settings/networks.php#L40)
