### ISSUE TITLE
Adding Custom field to profile & registration form

### ISSUE THREAD

**Issue by ajoudeh** [dektrium/yii2-user#409]
Hi,

I tried to add new custom field to profile & view it on registration from, but when i save the form the field still blank, can you tell me why??

I follow  the steps on your doc `Adding fields from Profile to the registration form` but it's still blank & the function `loadAttributes` is not used, Why??

Thanks,

**Comment by invaderhd** [comment]
I have the same problem I found it today, but in my case is not a but in my server I have a version that is different from the one in this repository. If you have in composer "dektrium/yii2-user": "*", then probably you have the same problem

**Comment by dmeroff** [comment]
You should upgrade Yii2-user via composer to use this feature.

**Comment by ajoudeh** [comment]
I already download the latest version throw composer by adding  `"dektrium/yii2-user": "*"` to composer.json file, but when I compare the codes I found difference, so I download it manual as zip file & replace it, then all things work fine

Thanks,
