### ISSUE TITLE
Redirect after registration, password recovery, etc

### ISSUE THREAD

**Issue by invaderhd** [dektrium/yii2-user#411]
At this point after some actions like registration, password recovery and other actions, the extension render the view "messages".

But in many cases we could want to redirect to other page for example to home. At this point there are no way to do it in a easy way. If I want to redirect the user to home I need to override multiple actions in multiple controllers.

I try to redirect from inside the view ("message") but since my layout handle the flash messages I lose it in the redirection. 

I think this can be improved in the future.

**Comment by dmeroff** [comment]
I'll add event triggers in controllers in the near feature, so you'll be able to redirect user instead showing him a message page.

**Comment by thiagotalma** [comment]
+1 :+1:

**Comment by invaderhd** [comment]
Perfect @dmeroff

**Comment by dmeroff** [comment]
Done! Example of redirect user after registration:

```php
'user' => [
    'class' => \dektrium\user\Module::className(),
    'controllerMap' => [
        'registration' => [
            'class' => RegistrationController::className(),
            'on ' . RegistrationController::EVENT_AFTER_REGISTER => function ($e) {
                Yii::$app->response->redirect(array('/user/security/login'))->send();
                Yii::$app->end();
            }
        ],
    ],
],
```

Moreover I'm thinking on adding redirects after most of actions as a default.
