### ISSUE TITLE
Not getting Email in authentication with google

### ISSUE THREAD

**Issue by vinod27ece** [dektrium/yii2-user#412]
Hi I am not able to get Email in my database while authentication via google.

As in Google.php, it is using 
public function getEmail()
    {
        return isset($this->getUserAttributes()['email'])
            ? $this->getUserAttributes()['email']
            : null;
    }

but I am getting data in view attribites 'emails' and that too is an array.(like 
"emails":[{"value":"email_value","type":"account"}]
)

So how to override Google.php in clients folder.

**Comment by dmeroff** [comment]
You should extend `dektrium\user\clients\Google` with your own class (you can locate it anyware you want) and then use it in configuration instead of Yii2-user class.

**Comment by vinod27ece** [comment]
Thanks, this solved my problem
