### ISSUE TITLE
Yii2 advanced, new install of Yii2-user, migrated, set up, but still as it would want to use the old (original) user module

### ISSUE THREAD

**Issue by cloudswitch** [dektrium/yii2-user#414]
Hi!

I've just installed the extension, on a Yii2 advanced template, I've done migration, I've set up everything according to docs, and it seem like it simply doesn't recognize the change and want to use the original built-in user module of Yii2. What can be wrong? Thanks!

**Comment by cloudswitch** [comment]
Sorrysorrysorry, maybe I have something not completely understood. So when I have an advanced Yii2 template, I don't have to migrate? (I have done, and maybe that's why it doesn't work?)

**Comment by cloudswitch** [comment]
It's not really clear what one has to do in order to make this extension work (maybe only for a pro). Would be good to write a tutorial for beginners... Thanks

**Comment by dmeroff** [comment]
There is no `user` module in yii2-advanced template. However it has some user features like registration and password recovery. Yii2-user does not replace them, but add new module, which can be accessed via other urls (/user/registration/register, /user/security/login, etc). You can read more in documentation (list of available actions).

**Comment by cloudswitch** [comment]
"There is no user module in yii2-advanced template." - I know.
"...which can be accessed via other urls (/user/registration/register, /user/security/login, etc)." - that was the problem, that I couldn't access these links.

**Comment by cloudswitch** [comment]
now with basic yii2 template it seems to work!
