### ISSUE TITLE
Showing default rating in Kartik star rating widget

### ISSUE THREAD

**Issue by 256cool** [dektrium/yii2-user#416]
Hi Guys,
I am using kartik widget to display the rating of the user as below
```
<?php $endorsementmodel = new Endorsement;
	echo $form->field($endorsementmodel, 'sense_of_fasion')->widget(StarRating::classname(), ['pluginOptions' => ['size'=>'xs', 'showCaption'=>false, 'readonly' => true]
	]); ?>
``` 
I want to show user some default rating for him, how can I provide the input to the above form?

**Comment by philippfrenzel** [comment]
Hey, you posted this issue in yii2 issues too and seems to be solved, can you pls. close it here?

**Comment by 256cool** [comment]
Solution - https://github.com/yiisoft/yii2/issues/8818#issuecomment-112627533
