### ISSUE TITLE
A safe way to add function dektrium / yii2-user

### ISSUE THREAD

**Issue by dbd5** [dektrium/yii2-user#418]
Hello,

Thanks for this excellent module once again!

I will like to add a function needed by my application to the user model but I will like to do it in a way that prevents composer from overwriting or discarding this code when you make changes to this module. 
Is there a way to achieve this similar to the theme option you provided for overriding the views?

Regards,

Adam

**Comment by dmeroff** [comment]
You can override model as said in documentation and add functions you need.

**Comment by dbd5** [comment]
Thank you Sir - forgive me, I know I saw that in the docs before but I think I maybe read it with only one eye
