### ISSUE TITLE
Configuration for yii\web\User move to configuration of module

### ISSUE THREAD

**Issue by IStranger** [dektrium/yii2-user#420]
Now when you enable this module, you can not use your own configuration for "user" component, because in Bootstrap class exist hard code:

```php
Yii::$container->set('yii\web\User', [
    'enableAutoLogin' => true,
    'loginUrl'        => ['/user/security/login'],
    'identityClass'   => $module->modelMap['User'],
]);
```
see https://github.com/dektrium/yii2-user/blob/master/Bootstrap.php#L71

I propose to make this code more flexible.
We can add in module configuration additional property with config for this injection, for example:
```php
$defaultWebUserConfig = [
    'enableAutoLogin' => true,
    'loginUrl'        => ['/user/security/login'],
    'identityClass'   => $module->modelMap['User'],
];
// ...
$webUserConfig = array_merge( $defaultWebUserConfig, $module->webUserConfig );
Yii::$container->set('yii\web\User', $webUserConfig);
```
Then we can inject own class)

**Comment by dmeroff** [comment]
It is not hardcoded, you are still able to use your own user component, however you have to set `enableAutoLogin`, `loginUrl` and `identityClass` the same way as in the bootstrap file.

**Comment by rawevolution** [comment]
Hi dmeroff, Can you please provide an example of how to specify your own web user class in web.php config?

**Comment by rawevolution** [comment]
I realise you may have meant you need to amend the bootstrap.php file itself but I was hoping for a way to configure it just from web.php.  In the end the main thing I wanted to do was run a function after the afterLogin event and I figured out the way to do that was by putting the component user config back in, i.e, 
<code>
    'components' => [
        'user' => [
            'on afterLogin' => ['app\events\AfterLoginEvent', 'handleNewUser'],
</code>
Cheers
