### ISSUE TITLE
first init alert

### ISSUE THREAD

**Issue by des1roer** [dektrium/yii2-user#423]
An Error occurred while handling another error:
exception 'PDOException' with message 'SQLSTATE[42S22]: Column not found: 1054 Unknown column 'status' in 'where clause'' in D:\open\OpenServer\domains\localhost\yii2-app-advanced\vendor\yiisoft\yii2\db\Command.php:825
Stack trace:

**Comment by dmeroff** [comment]
That's not yii2-user issue. There is not `status` column in yii2-user, so it can not be used anywhere. You probably used wrong url to access module. Please check out "List of available actions" in documenation.
