### ISSUE TITLE
confirmation email missing (master branch)

### ISSUE THREAD

**Issue by mzysk** [dektrium/yii2-user#426]
There's no confirmation message mailer in User model if enableConfirmation is true.

**Comment by mzysk** [comment]
@dmeroff - when we can expect to get an update on that?

**Comment by dmeroff** [comment]
I cannot reproduce the issue. Please check if you have `welcome` message view file overriden, since confirmation link is now sent using this template.

**Comment by xiandalisay** [comment]
I have the same issue though I just copied the configs on the docs.
