### ISSUE TITLE
Yii-user advanced template admin access

### ISSUE THREAD

**Issue by xiandalisay** [dektrium/yii2-user#430]
I followed the instructions for the advanced template. Still, I could not login using the specified username for admins... I already saved the login details of "admin" in the `user` table by signing up on the frontend.

@common/config

'modules' => [
	    'user' => [
            'class' => 'dektrium\user\Module',
            'enableUnconfirmedLogin' => true,
	        'confirmWithin' => 21600,
	        'cost' => 12,
	        'admins' => ['admin'],
     ],
],

**Comment by dmeroff** [comment]
I dont understand your problem, could you please provide more information.

**Comment by dmeroff** [comment]
Closed since no answer.

**Comment by xiandalisay** [comment]
I am using the advanced template. Also, I followed the instructions needed to incorporate this extension. I tried to login in the backend. But I could not login. I am stuck at the login page. I had specified the username of the admins, posted above. 

I had created a role "admin" and attached to the user named "admin". but I did not used yii2-rbac.

**Comment by dmeroff** [comment]
If you are redirected back to the login page after sign in, this probably means that you have `user` component defined in your backend config file.

**Comment by xiandalisay** [comment]
Yes, I do have. Same in the instructions posted in configuring the advance template...

'components' => [
        'user' => [
            'identityCookie' => [
                'name'     => '_backendIdentity',
                'path'     => '/admin',
                'httpOnly' => true,
            ],
            
        ],
        'session' => [
            'name' => 'BACKENDSESSID',
            'cookieParams' => [
                'httpOnly' => true,
                'path'     => '/admin',
            ],
        ],  ....
]

**Comment by dmeroff** [comment]
It's strange. Frontend app does not have the same problem? Could you please provide `user` component conifuguration from common and frontend config files?

**Comment by xiandalisay** [comment]
Yeah, it's strange. It's been days figuring this out. There's no user component on the common/config/main, only user module. I wrote it in the previous comment. There's only user component on backend and frontend as written in the instructions.

Frontend::
'components' => [
        'user' => [
            'identityCookie' => [
                'name'     => '_frontendIdentity',
                'path'     => '/',
                'httpOnly' => true,
            ],
            'identityClass' => 'dektrium\user\models\User',
            'enableAutoLogin' => true,
        ],
        'session' => [
            'name' => 'FRONTENDSESSID',
            'cookieParams' => [
                'httpOnly' => true,
                'path'     => '/',
            ],
        ],

**Comment by xiandalisay** [comment]
I tried reproducing by creating a new project. It doesn't work. In my composer.json. 
        "dektrium/yii2-user": "*"

**Comment by dmeroff** [comment]
Where you're overriding user model? In frontend or common config file? If you're doing it in common config, you should place it in frontend config.

**Comment by xiandalisay** [comment]
I placed it in the frontend config

**Comment by xiandalisay** [comment]
There is no difference if I extended it or not, since it's on the frontend. The problem is at the backend. Please check. Is your current advance template works on the backend?

Though maybe this is not related, I installed yii2-rbac. I set the role of my user "admin" with `admin`. It gave the access on the module.

**Comment by buuug7** [comment]
you  have  solve  your  problems？

**Comment by anushkanz** [comment]
I have same issue, i cant access that user/admin/ area

**Comment by balo85** [comment]
Same problem here. With clean install of yii2-user, registration and login from frontend work fine, but login in backend is not working

**Comment by myomyintaung512** [comment]
Just change   'path'     => '/admin' to  'path'     => '/', @backend/config/main.php and solved it.

@backend/config/main.php 
'user' => [
            'identityCookie' => [
                'name'     => '_backendIdentity',
                'path'     => '/',
                'httpOnly' => true,
            ],
        ],
        'session' => [
            'name' => 'BACKENDSESSID',
            'cookieParams' => [
                'httpOnly' => true,
                'path'     => '/',
            ],
        ],

**Comment by RGTimothy** [comment]
@myomyintaung512 it works!! But then I'm wondering, we followed the configuration steps using yii2-user for advance template and then find this issue. Is this a bug? And after I solved this by your way (changing backend config), I can log in through backend, but still can do the same on the frontend. I think it should not happen since we follow the instructions to prevent this too.

**Comment by myomyintaung512** [comment]
@RGTimothy For different sessions for backend and frontend, You should change your configuration like this.
@backend/config/main.php 
'components' => [
...
        'user' => [
            'identityCookie' => [
                'name'     => '_backendIdentity',   // unique for backend
                'path'     => '/backend/web', // correct path for the backend app.
                'httpOnly' => true,
            ],
        ],
        'session' => [
            'name' => 'BACKENDSESSID', // unique for backend
	    'savePath' => __DIR__ . '/../runtime', // a temporary folder on backend
            'cookieParams' => [
                'httpOnly' => true,
                'path'     => '/backend/web', // correct path for the backend app.
            ],
        ],
...
],
@frontend/config/main.php
 'components' => [
    ...
        'user' => [
            'identityCookie' => [
                'name'     => '_frontendIdentity', // unique for frontend
                'path'=>'/frontend/web', // correct path for the frontend app.
                'httpOnly' => true,
            ],
        ],
        'session' => [
            'name' => 'FRONTENDSESSID', // unique for frontend
			'savePath' => __DIR__ . '/../runtime', // a temporary folder on frontend
            'cookieParams' => [
                'httpOnly' => true,
                'path'=>'/frontend/web', // correct path for the frontend app.
            ],
        ],
...
],

**Comment by yonifine** [comment]
This is not a bug. the problem is with the /admin path. if you are using backend and if you need to use the same way as in the doc, you have to make sure your webserver is configured to redirect the admin page to /admin. if you are using different domains for frontend and backend / should be used instead of /admin.

**Comment by dmeroff** [comment]
Closed.
If someone still encounters this problem, please recreate topic on [support forum](https://dektrium.com).

**Comment by xushaun** [comment]
@myomyintaung512   great job Thanks, I have encounter same paroblem

**Comment by moonlordx2x** [comment]
how to fix this zzz i got the same problem
