### ISSUE TITLE
Blocked user can access account using social login.

### ISSUE THREAD

**Issue by vinod27ece** [dektrium/yii2-user#434]
Hi, 
I am using this extension in my project and I am stuck with one case, like A user has registered using facebook, Then I blocked user using Admin-Panel. But still user is able to log-in into system using facebook.

**Comment by dmeroff** [comment]
This is a bug, I'll fix this asap.

**Comment by dmeroff** [comment]
Fixed! Sorry for the delay!

**Comment by vinod27ece** [comment]
Thanks, very much.

One more query, I have override your module, So If I update module, will it
affect existing code?



On Sun, Sep 20, 2015 at 2:47 AM, Dmitry Erofeev <notifications@github.com>
wrote:

> Fixed! Sorry for the delay!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dektrium/yii2-user/issues/434#issuecomment-141708290>.
>



-- 

[image: Back Home]

*Vinod Agarwal *

Associate Software Engineer | Web
*mobile* +91-77373-47242 *|*   www.aurigait.com

*skype * vinod27ece

This message may contain confidential and/or privileged information. It is
intended to be read only by the individual or entity to whom it is
addressed or by their designee. If the reader of this message is not the
intended recipient, you are on notice that any uses, copy, disclose or
distribution of this message, in any form, is strictly prohibited. If you
have received this message in error, please notify the sender by reply
email or by telephone and delete or destroy any copy of this message. Thank
you.

**Comment by dmeroff** [comment]
If you have overridden module as explained in documentation, then you wont get any problems. Hovewer if you update module's code inside `vendor` directory, then composer will override your changes.

**Comment by vinod27ece** [comment]
Thank you for this extension :)

On Sun, Sep 20, 2015 at 7:36 PM, Dmitry Erofeev <notifications@github.com>
wrote:

> If you have overridden module as explained in documentation, then you wont
> get any problems. Hovewer if you update module's code inside vendor
> directory, then composer will override your changes.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dektrium/yii2-user/issues/434#issuecomment-141787129>.
>



-- 

[image: Back Home]

*Vinod Agarwal *

Associate Software Engineer | Web
*mobile* +91-77373-47242 *|*   www.aurigait.com

*skype * vinod27ece

This message may contain confidential and/or privileged information. It is
intended to be read only by the individual or entity to whom it is
addressed or by their designee. If the reader of this message is not the
intended recipient, you are on notice that any uses, copy, disclose or
distribution of this message, in any form, is strictly prohibited. If you
have received this message in error, please notify the sender by reply
email or by telephone and delete or destroy any copy of this message. Thank
you.
