### ISSUE TITLE
How to use beforeLogin and AfterLogin events

### ISSUE THREAD

**Issue by vinod27ece** [dektrium/yii2-user#435]
Hi,

I want to implement some functionality in user beforLogin() and afterLogin() functionality. Since there are many ways for a use to get logged in into system , So How could I override this default functionalities.

**Comment by memsis** [comment]
Subscribed because I'm trying to figure out the exact same thing. I'm trying to use the event triggered in afterLogin(), but I can't figure out where to dump my code... THe User model isn't the right place, that's what I know.

**Comment by wmfunk** [comment]
i have the same issue. Some example or howto, would be nice!
thx

**Comment by rawevolution** [comment]
Hey there,
I had this same issue a few days ago. Not sure if this is the best way but it works.

Create a class the implements bootstrap interface, I did:
<code>
<?php
namespace app\bootstraps;
use yii\base\BootstrapInterface;

class AppBootstrap implements BootstrapInterface{

   public function bootstrap($app){
      $app->user->on(\yii\web\User::EVENT_BEFORE_LOGIN,['app\models\user\User', 'beforeLogin']);
      $app->user->on(\yii\web\User::EVENT_AFTER_LOGIN,['app\models\user\User', 'afterLogin']);
      $app->user->on(\yii\web\User::EVENT_BEFORE_LOGOUT,['app\models\user\User', 'beforeLogout']);
   }
}
</code>

I've overridden the user class and added the relevant functions there but you can reference any class and function you want.

Finally, just add the following to your web.php file

<code>
$config = [
    'id' => 'basic',
    'name' => 'x',
    'basePath' => dirname(__DIR__),
    'bootstrap' => [
        'log',
        'app\bootstraps\AppBootstrap',
    ],
.....etc
</code>

**Comment by dmeroff** [comment]
The way that @rawevolution described is ok.

**Comment by taskas** [comment]
I found this issue on google results and tought it might be useful too - there's easier way to attach events.
1. create event handler, let's say create file in frontend\events\UserEvents:
```<?php
namespace frontend\events;

class UserEvents {
    public static function handleBeforeLogin($event)
    {
        var_dump($event);
        exit('UserEvents::handleBeforeLogin');
    }
}
```
2. modify config/main.php:
```
'components' => [
...
    'user' => [
        'on '.\yii\web\User::EVENT_BEFORE_LOGIN => ['frontend\events\UserEvents', 'handleBeforeLogin'],
....
````
That's it.
