### ISSUE TITLE
Enter in someone's account after registration via social network

### ISSUE THREAD

**Issue by loveorigami** [dektrium/yii2-user#447]
In yii forum I read next bug:
http://yiiframework.ru/forum/viewtopic.php?f=9&t=16660&p=152240#p152240

---

After registering via the social network (google), I was redirected to the link type http://yii2-user.dmeroff.ru/user/registration/connect?account_id=xxx in order to specify email.

If you manually change the ID to the address sooner or later get on someone's account, who do not have email. Pointing out some garbage - and I'm inside.

**Comment by dmeroff** [comment]
This has been fixed in master branch.
