### ISSUE TITLE
Update the 'usernameLength' to match in multiple models

### ISSUE THREAD

**Issue by invaderhd** [dektrium/yii2-user#448]
At the moment you are using different usernameLength in the rules of the models for example in User model you have 255 and in SettingsForm you have 20.

This should be the same in everyplace. The rules for the username should be the same in every model.

This can cause problems for example if you register by facebook then you can get a username with more than 20 characters and if you go an try to edit your password you will need to change the username because it return an error.

**Comment by thiagotalma** [comment]
PR welcome

**Comment by dmeroff** [comment]
Yes, it will be awesom, if you send a pull-request with this change!

**Comment by dmeroff** [comment]
Fixed! Sorry for the delay!
