### ISSUE TITLE
redirect to getReturnUrl

### ISSUE THREAD

**Issue by wispoz** [dektrium/yii2-user#449]
instead of:  
    if ($model->load(Yii::$app->getRequest()->post()) && $model->login()) {
            return $this->goBack();
        }
use:
 if ($model->load(Yii::$app->getRequest()->post()) && $model->login()) {
            return $this->redirect(Yii::$app->user->getReturnUrl());
        }

**Comment by dmeroff** [comment]
`$this->goBack` means the same as `$this->redirect(Yii::$app->user->getReturnUrl())`, so nothing should be changed.
