### ISSUE TITLE
Translations inside Bootstrap.php in multi-language websites

### ISSUE THREAD

**Issue by invaderhd** [dektrium/yii2-user#451]
I have a multilanguage website I use https://github.com/codemix/yii2-localeurls to handle the languages. But I check that the subject of registration emails or recovery password emails are allways sent in the default language of the website.

I do some debugs and if I put something like this inside Bootstrap.php

```
\Yii::$app->session->setFlash('success', "bootstrap language: ".\Yii::$app->language);
```

I always get the default language instead of the current language selected by the user. Any quick fix for this?

**Comment by dmeroff** [comment]
I don't think that yii2-user is compatible with that extension at the moment. I'll try to do my best to fix this.

**Comment by dmeroff** [comment]
Fixed!
