### ISSUE TITLE
BackendFilter security

### ISSUE THREAD

**Issue by inververs** [dektrium/yii2-user#453]
Hello, if in BackendFilter (file vendor\dektrium\yii2-user\filters\BackendFilter.php) in $controllers array i have 'security' item, than i cant open backend main page. I have 404 exception with not found message. But if i delete 'security' and leave only this: 
public $controllers = ['profile', 'recovery', 'registration', 'settings']; then everything starts to work: i see login form and so on..
What I did not set up? It seems everything done under the instruction

**Comment by Oreolek** [comment]
+1. BackendFilter filters out the ability to log in (`/user/`**security**`/login`)

Also, the documentation missed the urlManager configuration: prettyUrls should be in `<module>/<controller>/<action>` format

**Comment by xiandalisay** [comment]
@Oreolek How can I login considering the login is filtered out?

**Comment by Oreolek** [comment]
Working on it. For now, just comment that out.

**Comment by dmeroff** [comment]
This is fixed in master branch. I'm going to release new version 0.9.5 which will contain this fix.
