### ISSUE TITLE
Good night, 404 error on /user/admin/index

### ISSUE THREAD

**Issue by fernandrez** [dektrium/yii2-user#454]
Good night, thanks so much for this extension. It really helps novice programmers like me leverage on community knowledge, thank you very much. I am getting a 404 exception when trying to access user/admin/index. I followed instructions for advanced template without using independent sessions.
https://github.com/dektrium/yii2-user/blob/master/docs/usage-with-advanced-template.md

Please could you guide me in what can be wrong?

![captura de pantalla 2015-08-10 23 12 42](https://cloud.githubusercontent.com/assets/2273908/9189954/5029314c-3fb5-11e5-878f-3db4114f4ba1.png)

**Comment by wartron** [comment]
You should be able to access it from the backend app.  The 'as frontend' property on the module config prevents the AdminController from being loaded in the frontend app.

**Comment by fernandrez** [comment]
Thanks that worked out!!

**Comment by dmeroff** [comment]
Closed, since answer was given.

**Comment by dirttech** [comment]
@wartron How can i access it from backend app?
