### ISSUE TITLE
Performance issue: web content cache

### ISSUE THREAD

**Issue by xiandalisay** [dektrium/yii2-user#459]
The session and the cache should be automatically destroyed after log out. Am I right? I was wondering how did this happened. One time, it reached over 500 MB. ![capture](https://cloud.githubusercontent.com/assets/7392803/9323476/b4705e9c-45b3-11e5-9a19-ef86a60b6189.PNG)

**Comment by dmeroff** [comment]
I'm not sure that this is a yii2-user problem, since this extensions uses Yii2 components to operate with session. When user logs out Yii2-user calls logout method of Yii2 user component which destroys session data.
