### ISSUE TITLE
Login on backend

### ISSUE THREAD

**Issue by balo85** [dektrium/yii2-user#463]
Hello again,
now that the route work fine, i have created the first user from the frontend panel.
In the frontend i can login and logout without problem.
But in the backend panel the login page give me a 404 error. I check the log panel and i found that the action called have an id "security". 
In the filters/BackendFilter.php i have that if id is "security" it have to give me a NotFoundHttpException, so the 404 is right here. But so how can the admin login?
If i remove the "security" item from the array i can log in the backend without any problem.
Thanks

**Comment by dmeroff** [comment]
This has been fixed in master branch, you should update to the latest code.
