### ISSUE TITLE
Social account auth not working - dev-master

### ISSUE THREAD

**Issue by zychu** [dektrium/yii2-user#464]
Auth method returns that error (facebook and twitter):

Getting unknown property: dektrium\user\models\Account::email

under url:

http://xxx.dev/user/security/auth?authclient=facebook&code=xxxxxxxxx

Can't login and sign in with current version.

----

looks like $client informations (username, email) are not properly stored in Account object.

**Comment by mushketer888** [comment]
I agree with you.Have the same problem!
But with Google account

**Comment by mushketer888** [comment]
SOLVED IT!
I changed version for this module in composer.json like this:
"dektrium/yii2-user":"0.9.4",

and also changed:
"minimum-stability": "dev",

to avoid warnings

everything works now!

**Comment by zychu** [comment]
@mushketer888 - so you downgraded plugin, am i right? It's not a solution.

**Comment by mushketer888** [comment]
Well.Youre right its bad solution cause i now got other error in /user/admin controller about JUI
unknown property: yii\jui\DatePicker::dateFormat
As i understood (and checked) by installation guide composer doesnt download version with social clients! (there is no such folder at all!)
so when trying to pick other version where social clients exist-it works..but something other stops to work :D

**Comment by mushketer888** [comment]
Now all is working fine!
"dektrium/yii2-user":"0.9.3",
and
"minimum-stability": "beta",

its is enough if you dont plan to update modules regulary (maybe yet)

**Comment by mushketer888** [comment]
You can try this:
install yii2-user as written in guide
BUT download latest zip archive from github(here) and just place folder clients which doesnt exist yet
in vendor/dektrium/yii2-user
and all must work!

seems like someone just forgot to commit/rebranch it somewhere

**Comment by dmeroff** [comment]
@zychu you're using code from master branch but didn't apply new migrations.
