### ISSUE TITLE
Migration doesn't work

### ISSUE THREAD

**Issue by Graphyxx** [dektrium/yii2-user#465]
When i enter : php yii migrate/up --migrationPath=@vendor/dektrium/yii2-user/migrations
Cmd send me PHP Fatal Error 'yii\base\errorexecption' 'Class 'dektrium\user\migrations\Migration' not found'
in C:\wamp\www\vendor\dektrium\yii2-user\migrations\m140209_132017_init.php:7

**Comment by w84gg** [comment]
And when I writed this command - it printed error.
Migration failed. Directory specified in migrationPath doesn't exist: 
@vendor/dektrium/yii2-user/migrations

**Comment by dmeroff** [comment]
@Graphyxx the error you mentioned can only appear if you installed yii2-user manually. Please reinstall it using composer.

**Comment by thientc84** [comment]
I try to install via Composer but still get this error!
