### ISSUE TITLE
Incorrect sql statement for postgresql in migration

### ISSUE THREAD

**Issue by chelishchev** [dektrium/yii2-user#467]
Hi!
I use postgresql and migration *m141222_110026_update_ip_field* has incorrect code. 

```
$this->alterColumn('{{%user}}', 'registration_ip', Schema::TYPE_STRING . '(45) DEFAULT NULL');
```
http://www.postgresql.org/docs/9.1/static/sql-altertable.html

If you don't mind I advising remove "DEFAULT NULL". It's unnecessary.

**Comment by dmeroff** [comment]
Hello!
Could you please send a pull-request which changes behavior of migration only for postrgresql?

**Comment by chelishchev** [comment]
Funny :)
I've started to create pull request but I couldn't find problem statement:
```
$this->alterColumn('{{%user}}', 'registration_ip', Schema::TYPE_STRING . '(45) DEFAULT NULL');
```
And solution was simple. My project uses yii2-user as

```
    "require": {
        "dektrium/yii2-user": "1.0.x-dev",
    }
```

But your project has aliases:
```
        "branch-alias": {
            "dev-master": "0.9.x-dev",
            "dev-develop": "1.0.x-dev"
        },
```
Unfortunately branch *develop* is old and doesn't have any progress.

So migration *m141222_110026_update_ip_field* (in master) is right to use with postgresql.
