### ISSUE TITLE
Installation command error in docs/getting-started.md

### ISSUE THREAD

**Issue by rexct** [dektrium/yii2-user#469]
When using composer to download Yii2-user, the correct command seems to be as follows.
composer require "dektrium/yii2-user":"0.9.*@dev"
The origin command on docs/getting-started.md is lacking of quotes on both sides of the colon and results in UnexpectedValueException as follows.
[UnexpectedValueException]
Could not parse version constraint <=2.*: Invalid version string "2.*"

**Comment by dmeroff** [comment]
I've checked command from manual and it works. Please make sure that you're using the latest composer version and using the same command given in docs.
