### ISSUE TITLE
i need help

### ISSUE THREAD

**Issue by wblbird** [dektrium/yii2-user#481]
i have promble
 add captcha to login ,follow adding-captcha.md
but it's not work.
can show captcha,but validate show wrong
/////////////////  \vendor\dektrium\yii2-user\models\LoginForm.php
 public $captcha;
 public function rules()
    {
        return [
            'requiredFields' => [['login', 'password','captcha'], 'required'],
             'captchalPattern'=>['captcha', 'captcha'],
            'loginTrim' => ['login', 'trim'],
 . . . .
/////////////////
///////////////// \vendor\dektrium\yii2-user\controllers\SecurityController.php
 public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    ['allow' => true, 'actions' => ['login', 'auth','captcha'], 'roles' => ['?']],
                    ['allow' => true, 'actions' => ['login', 'auth', 'logout'], 'roles' => ['@']],
                ]
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post']
                ]
            ]
        ];
    }

    /** @inheritdoc */
    public function actions()
    {
        return [
             'captcha' => [
                    'class' => 'yii\captcha\CaptchaAction',
                                 'minLength' => 4,
                                 'maxLength' => 4
                ],
            'auth' => [
                'class' => AuthAction::className(),
                // if user is not logged in, will try to log him in, otherwise
                // will try to connect social account to user.
                'successCallback' => \Yii::$app->user->isGuest
                    ? [$this, 'authenticate']
                    : [$this, 'connect'],
            ]
        ];
    }
////////////////////////
///////////////// \vendor\dektrium\yii2-user\views\security\login.php
use yii\captcha\Captcha;               
    <?= $form->field($model, 'captcha')->widget(Captcha::className(), [
                        'captchaAction' => ['/user/security/captcha']
                    ]) ?>
 . . . .
/////////////////

**Comment by dmeroff** [comment]
You are doing something wrong. Try to start from the beginning. The approach defined in documentation is 100% working.
