### ISSUE TITLE
Generate identicons for users that do not have gravatar

### ISSUE THREAD

**Issue by nirvana-msu** [dektrium/yii2-user#483]
Would be really nice if all users that do not have gravatars set up would automatically have an identicon generated for them, just like it's done on e.g. github, stackoverflow, etc.

**Comment by nirvana-msu** [comment]
Should be really easy to implement, as described here:
http://en.gravatar.com/site/implement/images/

And the keyword should be configurable, so that we could use e.g. `retro` instead of `identicon`, which also looks really cool (and similar to github).

**Comment by dmeroff** [comment]
You should do it yourself by adding needed parameter to gravatar url, since yii2-user only stores gravatar hash, but not the link to the avatar itself.

**Comment by nirvana-msu** [comment]
Yes, I already do that in my other views. Would be nice if that was supported out of the box in default views, e.g. `/user/profile/show` etc through module configuration option. Otherwise I have to override all these views just to add one parameter to the links.

**Comment by dmeroff** [comment]
I think it should be left as is, since you need to override only one view (profile view) to change the behavior.

**Comment by nirvana-msu** [comment]
Ok, thanks.

**Comment by nirvana-msu** [comment]
Actually it's also used in `_menu`, so I also need to override `settings/account`, `settings/networks` and `settings/profile`. But you're probably right that I should override these.
