### ISSUE TITLE
Using User as a related model

### ISSUE THREAD

**Issue by gdiazderadaa** [dektrium/yii2-user#485]
Hi there, I have a mode called Incident with a property called Resolver which needs to be a User model. This is how I defined the relationship:

    public function getResolver()
    {
        return $this->hasOne(User::className(), ['id' => 'resolver_id']);
    }

I'm getting an error right there because User does not extend ActiveRecord and hence does not have the find() method.

Is there any other way to set a relationship with the User model?

Many thanks in advance

**Comment by dmeroff** [comment]
You probably using wrong model to define a relation. I mean if you have your own `User` model in the same namespace with the model you defing relation in, PHP will use it instead of yii2-user User model. It's all about namespaces, you should read about them. If you want to use yii2-user User model then you should use it as follows:
```php
public function getResolver()
{
    return $this->hasOne(\dektrium\user\models\User::className(), ['id' => 'resolver_id']);
}
```

**Comment by gdiazderadaa** [comment]
Hi,
That does not solve anything, since I´m already using that User model. The problem is the model \dektrium\user\models\User does not extends ActiveRecord class but \yii\base\Object and hence does not implement the find() method. 
Sorry if my explanation was not enough accurate.

**Comment by dmeroff** [comment]
That's not truth, since User model of yii2-user extends ActiveRecord class.

**Comment by gdiazderadaa** [comment]
Hi dmeroff, 
You were right. I have another getCreator() that should represent the relationship with yii2-user model, but it was pointing to the built-in user model. Now it's working like a charm. Many thanks for your help!

**Comment by krethjr** [comment]
Adding the "use" statement to my refering models solved the issue for me.  In this case, I had a model called "Orders" with an OrderedBy_User column with a referential index back to the users table.
`<?php

namespace app\models;

use Yii;
use dektrium\user\models\User;

/**
 * This is the model class for table "orders".`
Jim
