### ISSUE TITLE
how can I use Url::Canonical()

### ISSUE THREAD

**Issue by ksakinala-c** [dektrium/yii2-user#486]
I have a scenario, that to hold the page url in the database. So I'm using `Url::Canonical()` to capture it.

When I try to use `Url::Canonical()` in SettingsController.php, I get the following error

` PHP Notice – yii\base\ErrorException
Trying to get property of non-object`

Can you please let me know how can I use it in yii-user.

**Comment by dmeroff** [comment]
This is not yii2-user problem. You probably doing something wrong.

**Comment by ksakinala-c** [comment]
can you please let me know, how to use it...
