### ISSUE TITLE
menu with url /user/security/login being display as /user/login

### ISSUE THREAD

**Issue by Shahrulhadi** [dektrium/yii2-user#491]
Your yii2 user module use route /user/security/login for login page.
So i create a menu and specify /user/security/login for url.
But when i rollover on the menu created, browser show it has hyperlink to /user/login.
So clicking it will result navigating to /user/login. The url in address bar also show /user/login.
Somehow the page /user/security/login is being displayed anyway and i can login using it.
Yii2 debug at bottom also show the page url has route /user/security/login.

Problem is when i use rbac manager created by someone else that allow access only to available route. And the rbac manager list route /user/security/login but not /user/login which is correct.
So clicking on the login menu now will result to Not Found (#404) error.

Problem is the url for menu being change, not the rbac manager.
This problem also happen for route /user/registration/register which being change to /user/register.

I disable your yii2 user module, then the menu has the specified url /user/security/login, but of course clicking on it will result to Not Found (#404) error because the module is disabled.

Please help, i only find one more working yii2 user module on the internet, but yours has better looking ui.

**Comment by dmeroff** [comment]
I don't understand your problem clearly. Url is displayed as `user/login` for `user/security/login` because of url rules. You can disabled them if you don't need them at all.
