### ISSUE TITLE
Migrations, versioning and BC

### ISSUE THREAD

**Issue by SamMousa** [dektrium/yii2-user#494]
We are developing an application using your module.
During development we made some changes to your tables using migrations, which then broke migrations that you added later.

The basic issue is that tables are not version controlled and migrations assume a known start-state.

How should we handle table changes (for example, we use email as username and would like to remove the username column)

**Comment by dmeroff** [comment]
Unfortunately I have no advice for you how to handle such situation. It is all on your own.
I can only offer you to mark broken yii2-user migration as applied manually (php yii migrate/mark <migrationName>) and then manually do only changes from that migration that fit your database schema.
