### ISSUE TITLE
Not getting Confirmation link in welcome mail

### ISSUE THREAD

**Issue by dbd5** [dektrium/yii2-user#495]
Hello Dmitry,

I have extended the user model as recommended in your documentation.

Everything works as expected except that when I create a new account, a mail is sent with the credentials but it does not provide a confirmation link even though the parameter enableConfirmation is true;

My configuration is below, do let me know what I am doing wrong.

Many thanks

Adam
...
CONFIG

----User
namespace common\models;

use Yii;
use dektrium\user\models\User as BaseUser;
class User extends BaseUser
{
...

----Main
Under Modules:

	'user' => [
		'class' => 'dektrium\user\Module',
		'modelMap' => [
			 'User' => 'common\models\User',
		],

		'confirmWithin' => 3600, // 1 Hour
		'recoverWithin' => 3600,
		'enableFlashMessages' => true,
		'cost' => 12,
		'enableConfirmation' => true,
		'enableUnconfirmedLogin' => false,
		'admins' => ['webmaster'],
		'mailer' => [
			'sender'                => ['robot@testdomain.lan' => 'testdomain Robot'],
			'welcomeSubject'        => 'testdomain.lan - Welcome!',
			'confirmationSubject'   => 'testdomain.lan - Mail Confirmation',
			'reconfirmationSubject' => 'testdomain.lan - Mail Address change',
			'recoverySubject'       => 'testdomain.lan - Mail Recovery',
		],

		'controllerMap' => [
			'settings' => 'common\controllers\user\SettingsController',
			'admin' => 'common\controllers\user\AdminController',
			'registration' => 'common\controllers\user\RegistrationController',
		],
	],

Under components:

	'user' => [
		'class'=>'yii\web\User',
		'identityClass' => 'common\models\User',
		'loginUrl'=>['/user/security/login'],
		// 'enableAutoLogin' => true,
		'enableSession' => true,
		'authTimeout' => 3600,
		'as frontend' => 'dektrium\user\filters\FrontendFilter',
	],

**Comment by dmeroff** [comment]
If you're creating account from admin panel, then you won't get any confirmation link.

**Comment by dbd5** [comment]
I will check - Many thanks

A

**Comment by dbd5** [comment]
Hello Dmitry,

Please have a look again - this is unresolved, the behavior occurs when a new account is created by guest from the frontend, not from the control panel

Regards,

Adam

**Comment by dmeroff** [comment]
@dbd5 please answer following questions:
1) Which module version do you use? You can check it in `@vendor/dektrium/yii2-user/Module.php` file.
2) Have you overridden `welcome.php` mail view?

**Comment by dbd5** [comment]
Hi Dmitry,

The version is '0.9.5'

I've not overridden welcome.php, I have only overridden the models - user, profile as well as the controllers - AdminController, RegistrationController, SecurityController and SettingsController in the recommended way

Regards,

A

**Comment by dmeroff** [comment]
Did you override `register` method of User model?

**Comment by dbd5** [comment]
Don't worry, I reconfigured afresh and it's all good now

**Comment by MagSag** [comment]
I have the same issue I overrided the welcome page and here is my configuration : 

```
'modules'=>[
        'user'=> [
            'class' => 'dektrium\user\Module',
            'modelMap'=>[
                'Profile'=>'app\models\Profile',
                'RegistrationForm'=>'app\models\RegistrationForm',
                'User'=>'app\models\User',
                'ResendForm'=>'app\models\resendForm'
                ],
                'controllerMap'=>[
                'recovery'=>'app\controllers\RecoveryController',
                'security'=>'app\controllers\SecurityController',
                'registration'=>'app\controllers\RegistrationController',
                'profile'=>'app\controllers\ProfileController',
                'settings'=>'app\controllers\SettingsController',
                ],
            'enableConfirmation'=>true,
            'enableUnconfirmedLogin' => false,
            'emailChangeStrategy' =>\dektrium\user\Module::STRATEGY_SECURE,
            'confirmWithin' => 21600,
            'cost' => 12,
            'admins' => ['admin']
        ],
```

and for views in the component config : 

`    'view' => [
        'theme' => [
            'pathMap' => [
                '@dektrium/user/views' => '@app/views'
            ],
        ],
    ],`
