### ISSUE TITLE
LinkedIn client

### ISSUE THREAD

**Issue by SamMousa** [dektrium/yii2-user#496]
use dektrium\user\clients\ClientInterface;
        
        class LinkedIn extends \yii\authclient\clients\LinkedIn implements ClientInterface
        {
        
            /** @inheritdoc */
            public function getEmail()
            {
                return isset($this->getUserAttributes()['email-address'])
                    ? $this->getUserAttributes()['email-address']
                    : null;
            }
        
            /** @inheritdoc */
            public function getUsername()
            {
                return $this->getEmail();
            }
        }

Note: this implementation uses the email address as username, your google implementation instead returns null.

**Comment by dmeroff** [comment]
Could you please send a pull-request?
