### ISSUE TITLE
Uncaught exception when Profile model does not exist.

### ISSUE THREAD

**Issue by SamMousa** [dektrium/yii2-user#497]
The settingscontroller tries to perform ajax validation regardless if the profile was found:

https://github.com/dektrium/yii2-user/blob/master/controllers/SettingsController.php#L84

Since performAjaxValidation does not allow null to be passed (null is not an instance of yii\base\Model) an exception is thrown.

Possible solutions:
1. Check return type, don't do performAjaxValidation if model was not found.
2. Add default null value for performAjaxValidation argument and skip the validation if model is null.

**Comment by dmeroff** [comment]
I'll fix this in a few days.

**Comment by SamMousa** [comment]
Great! Do you have documentation on how you like to have contributions? I don't mind implementing bugfixes and creating PRs myself!

**Comment by dmeroff** [comment]
Fixed!
