### ISSUE TITLE
Filter by profile

### ISSUE THREAD

**Issue by balo85** [dektrium/yii2-user#506]
How can i filter the user based on profile value?
And how can i filter by some rbac permission? Let's said that i want all the user with a particular permission (CreatePost, eg), can i do it?
Thanks!

**Comment by trbsi** [comment]
You can create your own CRUD and UserSearch model and inside UserSearch you can call dektrium User to created DataProvider
See here example https://gist.github.com/trbsi/3190e907cf837d988f2d

**Comment by dmeroff** [comment]
The way provided by @trbsi is OK.
