### ISSUE TITLE
[yii2-user] Unknown Property – yii\base\UnknownPropertyException

### ISSUE THREAD

**Issue by nikhilgopalakrishna** [dektrium/yii2-user#507]
In : common\models\User::status

1. in /var/www/html/kw/vendor/yiisoft/yii2/base/Component.php at line 143
134135136137138139140141142143144145146147148149150151152            foreach ($this->_behaviors as $behavior) {
                if ($behavior->canGetProperty($name)) {
                    return $behavior->$name;
                }
            }
        }
        if (method_exists($this, 'set' . $name)) {
            throw new InvalidCallException('Getting write-only property: ' . get_class($this) . '::' . $name);
        } else {
            throw new UnknownPropertyException('Getting unknown property: ' . get_class($this) . '::' . $name);
        }
    }
 
    /**
     * Sets the value of a component property.
     * This method will check in the following order and act accordingly:
     *
     *  - a property defined by a setter: set the property value
     *  - an event in the format of "on xyz": attach the handler to the event "xyz"
2. in /var/www/html/kw/vendor/yiisoft/yii2/db/BaseActiveRecord.php at line 247 – yii\base\Component::__get('status')
3. in /var/www/html/kw/vendor/yiisoft/yii2/validators/DefaultValueValidator.php at line 46 – yii\db\BaseActiveRecord::__get('status')
4. in /var/www/html/kw/vendor/yiisoft/yii2/validators/Validator.php at line 241 – yii\validators\DefaultValueValidator::validateAttribute(common\models\User, 'status')
5. in /var/www/html/kw/vendor/yiisoft/yii2/base/Model.php at line 356 – yii\validators\Validator::validateAttributes(common\models\User, ['status'])
6. in /var/www/html/kw/vendor/yiisoft/yii2/db/ActiveRecord.php at line 418 – yii\base\Model::validate(null)
7. in /var/www/html/kw/vendor/yiisoft/yii2/db/BaseActiveRecord.php at line 593 – yii\db\ActiveRecord::insert(true, null)
8. in /var/www/html/kw/frontend/models/SignupForm.php at line 52 – yii\db\BaseActiveRecord::save()
46474849505152535455565758        if ($this->validate()) {
            $user = new User();
            $user->username = $this->username;
            $user->email = $this->email;
            $user->setPassword($this->password);
            $user->generateAuthKey();
            if ($user->save()) {
                return $user;
            }
        }
 
        return null;
    }
9. in /var/www/html/kw/frontend/controllers/SiteController.php at line 153 – frontend\models\SignupForm::signup()
147148149150151152153154155156157158159     * @return mixed
     */
    public function actionSignup()
    {
        $model = new SignupForm();
        if ($model->load(Yii::$app->request->post())) {
            if ($user = $model->signup()) {
                if (Yii::$app->getUser()->login($user)) {
                    return $this->goHome();
                }
            }
        }
 
10. frontend\controllers\SiteController::actionSignup()
11. in /var/www/html/kw/vendor/yiisoft/yii2/base/InlineAction.php at line 55 – call_user_func_array([frontend\controllers\SiteController, 'actionSignup'], [])
12. in /var/www/html/kw/vendor/yiisoft/yii2/base/Controller.php at line 151 – yii\base\InlineAction::runWithParams(['r' => 'site/signup'])
13. in /var/www/html/kw/vendor/yiisoft/yii2/base/Module.php at line 455 – yii\base\Controller::runAction('signup', ['r' => 'site/signup'])
14. in /var/www/html/kw/vendor/yiisoft/yii2/web/Application.php at line 84 – yii\base\Module::runAction('site/signup', ['r' => 'site/signup'])
15. in /var/www/html/kw/vendor/yiisoft/yii2/base/Application.php at line 375 – yii\web\Application::handleRequest(yii\web\Request)
16. in /var/www/html/kw/frontend/web/index.php at line 18 – yii\base\Application::run()
12131415161718    require(__DIR__ . '/../../common/config/main-local.php'),
    require(__DIR__ . '/../config/main.php'),
    require(__DIR__ . '/../config/main-local.php')
);
 
$application = new yii\web\Application($config);
$application->run();
 $_GET = [
    'r' => 'site/signup',
];

$_POST = [
    '_csrf' => 'RTNyYmJMMGIRZTYAMHkAMgpfHDQsel09DF86JA0ZWhcrBAFQUBhfLQ==',
    'SignupForm' => [
        'username' => 'user1',
        'email' => 'user1@email.com',
        'password' => 'user1password',
    ],
    'signup-button' => '',
];

**Comment by s4astliv** [comment]
Looks like you are still user component configured. Make sure that you don't have user component configuration in your config files. If you are using advanced template, see my pull request with core clear and complete configuration steps.

https://github.com/dektrium/yii2-user/pull/508

**Comment by dmeroff** [comment]
Yii2-user does not have `status` field in User model. You're probably using default yii2 advanced template implementation of working with users.
