### ISSUE TITLE
Allow specifying admin permission name as well as usernames

### ISSUE THREAD

**Issue by rimas-kudelis** [dektrium/yii2-user#509]
The `admins` configuration value currently accepts a list of usernames only. It would be nice if a name of permission could be provided in a different value instead of, or along with these usernames. This way, after initial administrator is added and configures the permission system, other users could be promoted to "useradmins" without touching configuration files. At this point, the `admins` value would mainly serve as "plan B" in case something goes wrong and nobody has the specified permission anymore.

What I have in mind is something like this in `models/User.php`:
```php
public function getIsAdmin()
{
    if (!empty($this->module->adminPermission) && $this->can($this->module->adminPermission)) {
        return true;
    }

    if (in_array($this->username, $this->module->admins)) {
        return true;
    }

    return false;
}
```
except I'm not sure if $this->can() would work like that, which is why I haven't created a PR yet. :)

**Comment by dmeroff** [comment]
You can just override `getIsAdmin` method. This won't be included in Yii2-user to work out of the box.
