### ISSUE TITLE
Provide AccessRule implementation

### ISSUE THREAD

**Issue by SamMousa** [dektrium/yii2-user#510]
The docs here: https://github.com/dektrium/yii2-user/blob/master/docs/custom-access-control.md

Give an implementation of AccessRule that works with yii2-user, specifically the admin role.

Why not provide this implementation as part of the package so we can use it directly from configuration?

**Comment by dmeroff** [comment]
Good idea, I'll add this on weekend! Sorry for the delay with the answer!

**Comment by dmeroff** [comment]
Done!
