### ISSUE TITLE
Registration disabled, but users can register using social network login

### ISSUE THREAD

**Issue by innobilehu** [dektrium/yii2-user#512]
In the configuration the registration is disabled, of course user/register/register page is not available, but if a new user clicks on login with Google+ of Facebook, there is the normal registration procedure.

**Comment by dmeroff** [comment]
I'll fix this as soon as possible.

**Comment by innobilehu** [comment]
Thank you! Can you tell me, when will be the bugfix roughly committed?

**Comment by dmeroff** [comment]
@innobilehu I'm sorry for the delay. I will try to handle this on the weekend!

**Comment by dmeroff** [comment]
Fixed!
