### ISSUE TITLE
Setting Default role with Yii2-user

### ISSUE THREAD

**Issue by josemonmaliakal** [dektrium/yii2-user#513]
How do I modify Yii2-user such a way that I can set  default user role in Yii2-rbac . ??

**Comment by dmeroff** [comment]
At the moment you can override `beforeSave` method of User model and set the role there

**Comment by WowandersoN** [comment]
Sorry, but can you write, what i must override in that method?

**Comment by Monumentix** [comment]
I know this old, but i spent some time solving this one, and this is what i used.  You can use the authManager component to define defaultRoles.

http://stackoverflow.com/questions/28936747/rbac-yii2-doesnt-work-with-default-roles

```
'authManager' => [
    'class' => 'yii\rbac\DbManager',
    'defaultRoles' => ['admin', 'author'], // your define roles
],
```

**Comment by unreacheble** [comment]
Добрый день!
Использую Ваши компоненты yii2-user & yii2-rbac. 
Не пойму как назначить роль по умолчанию пользователю который авторизуется через соц. сети?

**Comment by Monumentix** [comment]
AuthManager is used by RBAC, so when setting that component up under in config, you can specify the default role that AuthManager object apply to the logged in user.  You wont see any entries in the RBAC tables as it looks to be an just an object property.

**Comment by tepaleguiojo** [comment]
This is how I solved it

```
public function afterSave($insert, $changedAttributes)
{
        parent::afterSave($insert, $changedAttributes);

        if ($insert) {
            $this->getDb()
                ->createCommand()
                ->insert('{{%auth_assignment}}', [
                    'item_name' => \app\helpers\RoleHelper::SUBSCRIBER,
                    'user_id' => $this->id,
                    'created_at' => time(),
                ])
                ->execute();
        }
}
```

I don't know if it's the proper way since I cannot do it in `beforeSave`.

**Comment by Islamsolnkey** [comment]
![screenshot from 2018-07-05 15 11 20](https://user-images.githubusercontent.com/14867759/42632351-78e232c6-85fa-11e8-9e65-27a2491822c6.png)
