### ISSUE TITLE
Adding fields to the table and methods to the model of Yii 2-User Extension

### ISSUE THREAD

**Issue by MagSag** [dektrium/yii2-user#515]
While looking for an extension that will simplify things, I find this yii2-user.dmeroff.ru/docs - Dektrium project and would like to add what are important for me miss in the model and table.

First of all , I have my user table(model) in my database but after
passing throught your extension I found it coul really help me but the
problem I have is in my table a part from user id, name,email,profile
photo(for comment(thumbnail) and profile) and password field I have
also gender,telephone number(which the user can use to log in) and my
user model has other methods too. how can I handle that using your
extension?

Secondly, I want to put the log in view and sign up view at the same
time on the main layout(kind of using them as blocks), How can I do
that?

Does it support Internationalization?how?

**Comment by dmeroff** [comment]
1) There is no easy way to use Yii2-user with already existing table. You should figure it out yourself.

2) There is a Login widget bundled with Yii2-user, you can override registration page and add that widget.

3) Yes, you can just change the language of application and Yii2-user will use appropriate language file (you can check if your language is supported in `messages` directory. if it does not you can send  pull-request which adds your language to Yii2-user)

**Comment by MagSag** [comment]
Thanks for the answer I got my way but following how to add field from prfile to registration after the user registers his profile is not being saved; here is what I did:

a)RegistrationForm Model (override from RegistrationForm)
	 public function loadAttributes()
    {
        // here is the magic happens
        $this->user->setAttributes([
            'email'    => $this->email,
            'username' => $this->username,
            'password' => $this->password,
        ]);
        /** @var Profile $profile */
        $profile = \Yii::createObject(Profile::className());
        $profile->scenario = 'signup';
        $profile->setAttributes([
            'gravatar_email' => $this->email,
            'pays' => $this->pays,
            'ville'=>$this->ville,
            'sexe'=>$this->sexe,
            'name'=>$this->name,
            'location'=>$this->location,
            
        ]);
        $this->user->setProfile($profile);
    }

    public function register()
    {
        if (!$this->validate()) {
            return false;
        }
        
        $this->loadAttributes();
        return $this->user->register();
    } 
}

b) User Model(override from user Model)

 public function afterSave($insert, $changedAttributes)
    {
        if ($insert) {
            //If I don't put this first line the user_id in insert statement is empty causing
            //SQL Integrity error
            $this->profile->user_id= $this->id;
            $this->profile->save();
        }
//        parent::afterSave($insert, $changedAttributes);
    }
    
    public function setProfile(Profile $profile){
  $this->profile = \Yii::createObject(Profile::className());
  $this->profile = $profile;
    }

I even tried to do this in RegistrationFor:
 public function register()
    {
        if (!$this->validate()) {
            return false;
        }

        $this->user->setAttributes([
            'email'    => $this->email,
            'username' => $this->username,
            'password' => $this->password
        ]);

        $valeur = $this->user->register();
        if($valeur){
         /** @var Profile $profile */
        $profile = \Yii::createObject(Profile::className());
        $profile->scenario='signup';
        $profile->setAttributes([
            'pays' => $this->pays,
            'ville'=>$this->ville,
            'sexe'=>$this->sexe,
            'name'=>$this->name,
            'location'=>$this->location,
            
        ]);
        $profile->save();
        }
        return $valeur;
    }
}

But still if I check the profile table nothing is being save a part from gravatar email which is being done in aftersave of user model
