### ISSUE TITLE
Getting unknown property: dektrium\user\models\Account::email

### ISSUE THREAD

**Issue by maxyc** [dektrium/yii2-user#517]
It is not clear for what reason has ceased to work authorization and registration in social networks. Registration through the form

https://vk.com/doc285585404_429340603
![](https://pp.vk.me/c622218/v622218404/56e29/aL4Y4SQv1UI.jpg)

**Comment by danielraimondi** [comment]
Same issue here with google+

**Comment by raditzlawliet** [comment]
Same issue Login when trying to login with Google+

**Comment by danielraimondi** [comment]
It worked!
Thank you

**Comment by dmeroff** [comment]
Closed, since answer was given.
