### ISSUE TITLE
log in

### ISSUE THREAD

**Issue by MagSag** [dektrium/yii2-user#518]
hello; I would just like to know if after the user has sign up with his email address and has obtained a user id can he use both to log in(exactly what twitter does and it adds more(telephone number))?

Best regards

**Comment by smilemd** [comment]
At the moment you can login with username and mail.

**Comment by MagSag** [comment]
Thanks a lot for the help, I would like to know what about :+1: 

Firstly , I have my user table(model) in my database; the
problem I have is in my table a part from user id, name,email,profile
photo(for comment(thumbnail) and profile) and password field I have
also gender,telephone number(which the user can use to log in) and my
user model has other methods too. how can I handle that using your
extension?

Secondly, I want to put the log in view and sign up view at the same
time on the main layout(kind of using them as blocks), How can I do
that?

Does it support Internationalization?how?

**Comment by smilemd** [comment]
Yes, it support Internationalization.
 
in rest from what i know, you should override base module to get what you want.

**Comment by MagSag** [comment]
Thanks it is working perfectly
