### ISSUE TITLE
This username has already been taken

### ISSUE THREAD

**Issue by maxyc** [dektrium/yii2-user#519]
![](https://i.gyazo.com/a969592b4d6ba13bcb9339d74751da10.png)
![](https://i.gyazo.com/5db5e45d08382dcfb626f5b03dce330e.png)
![](https://i.gyazo.com/cdc4222d0f98de72af36bbb27048bd9a.png)

Why username has already been taken???

**Comment by dmeroff** [comment]
The only way this is possible is obvious: there is a row in your user table which has that username.
