### ISSUE TITLE
Не проходит авторизация

### ISSUE THREAD

**Issue by des1roer** [dektrium/yii2-user#520]
Установил. В настройках указал

    'modules' => [
        'user' => [
            'class' => 'dektrium\user\Module',
            'admins' => ['des1roer','123'],
            'enableConfirmation' => false,
        ],
    ],

при регистрации данные в таблице появились. но авторизация не проходит

**Comment by dmeroff** [comment]
Нужно удалить компонент `user` из списка компонентов в конфиге.
В следующий раз, давайте все-таки по-английски.

**Comment by luckyalexandr** [comment]
After delete `user` from `component`

> User::identityClass must be set.

**Comment by faenir** [comment]
If you see this error, it means the module is installed incorrectly.
