### ISSUE TITLE
urlRules confilict

### ISSUE THREAD

**Issue by AlaFalaki** [dektrium/yii2-user#521]
Hi,
I've activate prettyURL in Yii2-advanced template, everything works fine when i use:
`sample.com/user/security/login`
`sample.com/user/recovery/request`
and so on...
but, the rules in this module, says that the URLs must be like:
`sample.com/user/login`
`sample.com/user/forgot`
and so on...
the module URL rules redirect me to a 404 page.
but when i put this config in my frontend/config/main.php file, the module URLs works just fine:
`'<module:user>/<id:\d+>'                    => '<module>/profile/show',`
`'<module:user>/<action:(login|logout)>'     => '<module>/security/<action>',`
`'<module:user>/<action:(register|resend)>'  => '<module>/registration/<action>',`
`'<module:user>/confirm/<id:\d+>/<code:\w+>' => '<module>/registration/confirm',`
`'<module:user>/forgot'                      => '<module>/recovery/request',`
`'<module:user>/recover/<id:\d+>/<code:\w+>' => '<module>/recovery/reset',`
`'<module:user>/settings/<action:\w+>'       => '<module>/settings/<action>',`
I want to know, is it a bug? am i doing something wrong?

**Comment by AlaFalaki** [comment]
and another thing, if i remove:
`'<controller:\w+>/<action:\w+>' => '<controller>/<action>',`
from my  frontend/config/main.php [urlManager] config file, i don't need anything else, and the modules url works just fine.

**Comment by dmeroff** [comment]
You probably do have some url rules in your config which conflict with url rules defined by Yii2-user. So just add Yii2-user rules to your main config, that's normal way.
