### ISSUE TITLE
m150623_212711_fix_username_notnull migrating problem in Postgresql 9.4

### ISSUE THREAD

**Issue by akaSStalkALEX** [dektrium/yii2-user#526]
Migration doesn't worked for my db due to syntax error. Problem is in "Type" keyword in pgsql string generated by alterColumn command. 
Here's connected issue in yii2 thread: https://github.com/yiisoft/yii2/issues/4492

Is there any way to fix it without rewriting migrations? 
I used this code $this->execute('ALTER TABLE "user" ALTER COLUMN "username" SET NOT NULL'); in "up" function as hack for now.

**Comment by dmeroff** [comment]
I don't support postgre sql migration, so you can either fix it locally and up migration, or send a pull-request which fixes incorrect behavior.
