### ISSUE TITLE
Getting unknown property: yii\web\Application::enableRegistration

### ISSUE THREAD

**Issue by dbd5** [dektrium/yii2-user#527]
Hi Dmitry,

Thanks again for this excellent module!
Yesterday I stumbled into what might be a logic bug, please verify as follows:

HOW TO REPRODUCE
1. Integrate yii2-user with Yii2-advanced template using configuration in documentation.
2. Override the registration model as documented in https://github.com/dektrium/yii2-user/blob/master/docs/overriding-models.md. In my case, the only 'magic' introduced is to use a different template for the registration process.

Now the introduced controller looks like this (listing of frontend\controllers\RegistrationController):
```php
<?php
namespace frontend\controllers;
use Yii;
use dektrium\user\controllers\RegistrationController as BaseRegistrationController;
class RegistrationController extends BaseRegistrationController
{
    public function actionRegister()
    {
        $this->layout = '/_register.php';
        return parent::actionRegister();
    }
}
```
Test as follows;

Open URL: http://localhost/registration/register (Remember the URL is incorrect by design - this is a test! The correct URL is http://localhost/user/registration/register BUT we also need to test how the application will behave when it meets the unexpected)

OUTCOME 
"Getting unknown property: yii\web\Application::enableRegistration". This also happens when you test with http://localhost/registration/resend. It doesn't  happen for any other incomplete actions from https://github.com/dektrium/yii2-user/blob/master/docs/available-actions.md

EXPLANATION
The extension of RegistrationController is located in the Yii2 standard folder for Controllers (frontend\controllers) therefore Yii sends the request to this as Controller (really extension) but the code reproduced above calls  return parent::actionRegister() when apparently the module is not initialized. The error occurs because parent::actionRegister() in the module tests for the setting enableRegistration
```php
public function actionRegister()
    {
        if (!$this->module->enableRegistration) {
            throw new NotFoundHttpException();
```
REQUIREMENT/EXPECTED BEHAVIOUR
The module is properly integrated with Yii2 and the overriding of the controller seems valid, I suggest that the module should throw new NotFoundHttpException() if you agree with my analysis or otherwise please let me know what I've done wrong

Regards,

Adam

**Comment by dmeroff** [comment]
The problem is that when you accessing registration controller via url `registration/register` (not `user/registration/register`, Yii sets the controllers' module property to Application. There are two ways to fix throwing `Getting Unknown property` exception:

1) restrict access to those urls via urlManager
2) check for module class:

```php
<?php
namespace frontend\controllers;
use Yii;
use dektrium\user\controllers\RegistrationController as BaseRegistrationController;
class RegistrationController extends BaseRegistrationController
{
    public function actionRegister()
    {
        if (!($this->module instanceof \dektrium\user\Module)) {
            throw new NotFoundHttpException();
        }
        $this->layout = '/_register.php';
        return parent::actionRegister();
    }
}
```

**Comment by dbd5** [comment]
Ok, thanks
