### ISSUE TITLE
Argument 1 passed to dektrium\user\controllers\RegistrationController::getUserEvent()

### ISSUE THREAD

**Issue by yoyhosoft** [dektrium/yii2-user#532]
When confirm with invalid user id. 

Argument 1 passed to dektrium\user\controllers\RegistrationController::getUserEvent() must be an instance of dektrium\user\models\User, null given, called in C:\xampp\htdocs\aaa.local\vendor\dektrium\yii2-user\controllers\RegistrationController.php on line 209 and defined

**Comment by dmeroff** [comment]
I'll check this on weekend!

**Comment by dmeroff** [comment]
Fixed! Thank you for the report!
