### ISSUE TITLE
Dependency references break serialization

### ISSUE THREAD

**Issue by SamMousa** [dektrium/yii2-user#535]
In init() the user model stores references to:
* `Finder`
* `Mailer`
* `Module`

These should instead be replaced by getters instead, this will allow for proper serialization without needlessly (and at the risk of errors) serializing dependencies.

Side note: dependencies should be either inserted via constructor or setter injection, not via global usage of the DI container. (That's service locator)

**Comment by SamMousa** [comment]
https://github.com/dektrium/yii2-user/pull/536

**Comment by dmeroff** [comment]
I'm sorry for the delay with answer, I'll check this on weekend!

**Comment by dmeroff** [comment]
PR merged, thanks!
