### ISSUE TITLE
Error 500 

### ISSUE THREAD

**Issue by EsoftsLimited** [dektrium/yii2-user#539]
When i try logging in/out an error 500, no errror logged on error file, kindly test admin.cfb.co.ke and me know if you know way round this

**Comment by dmeroff** [comment]
Error 500 means that internal server error occurred, you have to enable php errors output to figure out what is going on. And then either solve the problem your self or create an issue with more detailed explanation.

**Comment by EsoftsLimited** [comment]
I have enabled all error in my PHP.ini it doesnt show any error,  the problem seems to be random as sometime it works well sometime it throws this error, sometime after i loggin it direct me to favicon.ico url i really can not figure out why this is happening

**Comment by dmeroff** [comment]
It should show errors if php is configured correctly to show errors.
`sometime after i loggin it direct me to favicon.ico url`
this probably means that your server is configured in a wrong way.
