### ISSUE TITLE
various constants in the model USER on different servers o_O

### ISSUE THREAD

**Issue by martrix78** [dektrium/yii2-user#540]
when installed on the server get the error due to the changed constants USER_REGISTER_DONE and AFTER_REGISTER.
On the local machine i did `composer update` but nothing changes
How to fix it?
local file:
`
class User extends ActiveRecord implements IdentityInterface
{
    const USER_CREATE_INIT   = 'user_create_init';
    const USER_CREATE_DONE   = 'user_create_done';
    const USER_REGISTER_INIT = 'user_register_init';
    const USER_REGISTER_DONE = 'user_register_done';
`
remote file:
`
class User extends ActiveRecord implements IdentityInterface
{
    const BEFORE_CREATE   = 'beforeCreate';
    const AFTER_CREATE    = 'afterCreate';
    const BEFORE_REGISTER = 'beforeRegister';
    const AFTER_REGISTER  = 'afterRegister';
`

**Comment by dmeroff** [comment]
Your have wrong constants on your server `User` class. You'd better update files on your server.
