### ISSUE TITLE
Profile data from the registrationForm model are not being save in profile table.

### ISSUE THREAD

**Issue by MagSag** [dektrium/yii2-user#541]
Thanks for the answer I got my way but following how to add field from prfile to registration after the user registers his profile is not being saved; here is what I did:

a)RegistrationForm Model (override from RegistrationForm)
public function loadAttributes()
{
// here is the magic happens
$this->user->setAttributes([
'email' => $this->email,
'username' => $this->username,
'password' => $this->password,
]);
/** @var Profile $profile */
$profile = \Yii::createObject(Profile::className());
$profile->scenario = 'signup';
$profile->setAttributes([
'gravatar_email' => $this->email,
'pays' => $this->pays,
'ville'=>$this->ville,
'sexe'=>$this->sexe,
'name'=>$this->name,
'location'=>$this->location,

    ]);
    $this->user->setProfile($profile);
}

public function register()
{
    if (!$this->validate()) {
        return false;
    }

    $this->loadAttributes();
    return $this->user->register();
} 

}

b) User Model(override from user Model)

public function afterSave($insert, $changedAttributes)
{
if ($insert) {
//If I don't put this first line the user_id in insert statement is empty causing
//SQL Integrity error
$this->profile->user_id= $this->id;
$this->profile->save();
}
// parent::afterSave($insert, $changedAttributes);
}

public function setProfile(Profile $profile){

$this->profile = \Yii::createObject(Profile::className());
$this->profile = $profile;
}

I even tried to do this in RegistrationFor:
public function register()
{
if (!$this->validate()) {
return false;
}

    $this->user->setAttributes([
        'email'    => $this->email,
        'username' => $this->username,
        'password' => $this->password
    ]);

    $valeur = $this->user->register();
    if($valeur){
     /** @var Profile $profile */
    $profile = \Yii::createObject(Profile::className());
    $profile->scenario='signup';
    $profile->setAttributes([
        'pays' => $this->pays,
        'ville'=>$this->ville,
        'sexe'=>$this->sexe,
        'name'=>$this->name,
        'location'=>$this->location,

    ]);
    $profile->save();
    }
    return $valeur;
}

}

But still if I check the profile table nothing is being save a part from gravatar email which is being done in aftersave of user model; I don't figure out easly where my codes are messing up.

If there is a complete example until showing how the profile information on the registrationForm will be saved that can really help or An idea.

**Comment by dmeroff** [comment]
There is a complete tutorial on how to add profile fields to registration form - [check it out](http://yii2-user.dmeroff.ru/docs/adding-profile-fields-to-registration-form)

**Comment by MagSag** [comment]
I followed exactly that tutorial but what is there is in the user model there aren't code to save these data add on registration form. In the user model the gravatar email is the only one thing that is being save in aftersave; I think that why the other profile data are not being saved. I try to add things manually as explain about but nothing worked out for me.

**Comment by dmeroff** [comment]
You don't need to override `register` method of registration form model. Also make sure that you have validation rules for your fields inside Profile model.

**Comment by MagSag** [comment]
OK let me do what you say and give you the feedback. I duplicated thinking people will not see a closed issue, sorry.
