### ISSUE TITLE
Combination/merging of profiles

### ISSUE THREAD

**Issue by Evstigneev** [dektrium/yii2-user#542]
For example. User registered via email and later registers via oauth (eg Twitter). And we have two profiles of ONE user (two users in DB). How to combine/merge users and profiles?

Maybe we should put the protection from such cases and add a user an option to merge profiles?

Russian
К примеру. Пользователь зарегистрировался через почту и позже зарегистрировался через oauth (eg Twitter). В этом случае мы получаем 2 профиля одного пользователя (2 юзера в БД). Как объединить пользователей и профили?

Может стоит добавить защиту от подобных случаев и добавить пользователю возможность слияния профилей

**Comment by dmeroff** [comment]
At the moment user can connect social accounts from settings page. Moreover if user logs in with social network which provides email then Yii2-user will first search for the user with such email, and if it founds it then it will add social account to that user and log him in.
