### ISSUE TITLE
 Profile data from the registrationForm model are not being save in profile table. #541 

### ISSUE THREAD

**Issue by MagSag** [dektrium/yii2-user#548]
Refering to the issue #541 Execuse me to take long it because of internet issue and it is solved now.

I followed exactly that tutorial but what is there is in the user model there aren't code to save these data add on registration form. In the user model the gravatar email is the only one thing that is being save in aftersave; I think that why the other profile data are not being saved. I try to add things manually as explain about but nothing worked out for me. In the user Model there isn't even setProfile method.

**Comment by dmeroff** [comment]
Please stop duplicating issues on one topic. I've answered to you in #541

**Comment by MagSag** [comment]
I would like to give you the feedback but no way since the issue has been closed.
When I try to install the version 0.9.5 I am getting this error from the composer:

Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - yiisoft/yii2-jui 2.0.4 requires bower-asset/jquery-ui 1.11.*@stable -> no matching package found.
    - yiisoft/yii2-jui 2.0.3 requires bower-asset/jquery-ui 1.11.*@stable -> no matching package found.
    - yiisoft/yii2-jui 2.0.2 requires bower-asset/jquery-ui 1.11.*@stable -> no matching package found.
    - yiisoft/yii2-jui 2.0.1 requires bower-asset/jquery-ui 1.11.*@stable -> no matching package found.
    - yiisoft/yii2-jui 2.0.0 requires bower-asset/jquery-ui 1.11.*@stable -> no matching package found.
    - dektrium/yii2-user v0.9.5 requires yiisoft/yii2-jui ~2.0 -> satisfiable by yiisoft/yii2-jui[2.0.0, 2.0.1, 2.0.2, 2.0.3, 2.0.4].
    - Installation request for dektrium/yii2-user v0.9.5 -> satisfiable by dektrium/yii2-user[v0.9.5].

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://groups.google.com/d/topic/composer-dev/_g3ASeIFlrc/discussion> for more details.

Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.

Installation failed, reverting ./composer.json to its original content.

I don't know what to do so that it works; I even remember that what sent me to choose * for version for the first time I was trying to install the extension to. Thanks for your support.

Date: Mon, 23 Nov 2015 11:29:27 -0800

**Comment by dmeroff** [comment]
Do you have assets plugin installed?

**Comment by MagSag** [comment]
I installed Yii2 manually and think probably it is not installed. I am looking how to check it is installed and how to install it.
I'll let you know how it goes. I am stack in my project of the problem.

Date: Wed, 25 Nov 2015 12:43:50 -0800

**Comment by MagSag** [comment]
I've installed everything and yii2-user 0.9.5 I see codes that could do the work I'm gonna try it today. Thanks a lot for leading me

From: magezisagesse@hotmail.fr
To: reply@reply.github.com
Subject: RE: [yii2-user]  Profile data from the registrationForm model are not being save in profile table. #541  (#548)
Date: Thu, 26 Nov 2015 09:03:47 +0200




I installed Yii2 manually and think probably it is not installed. I am looking how to check it is installed and how to install it.
I'll let you know how it goes. I am stack in my project of the problem.

Date: Wed, 25 Nov 2015 12:43:50 -0800

**Comment by MagSag** [comment]
Now as I am trying to override the loadAttributes of registrationForm; I am getting the error :

                PHP Strict Warning
                – yii\base\ErrorException            Declaration of 
app\models\RegistrationForm::loadAttributes() should be compatible with 
dektrium\user\models\RegistrationForm::loadAttributes(dektrium\user\models\User
 $user)

What I did is :
protected function loadAttributes(User $user)
    {
        $user->setAttributes([
            'email'    => $this->email,
            'username' => $this->username,
            'password' => $this->password,
        ]);
        /** @var Profile $profile */
        $profile = \Yii::createObject(Profile::className());
        $profile->scenario = 'signup';
        $profile->setAttributes([
        'gravatar_email' => $this->email,
        'pays' => $this->pays,
        'ville'=>$this->ville,
        'sexe'=>$this->sexe,
        'name'=>$this->name,
        'location'=>$this->location]);
        $user->setProfile($profile);
    }

I dont really know what is different from the method I am trying to override:

/**
     * Loads attributes to the user model. You should override this method if you are going to add new fields to the
     * registration form. You can read more in special guide.
     *
     * By default this method set all attributes of this model to the attributes of User model, so you should properly
     * configure safe attributes of your User model.
     *
     * @param User $user
     */
    protected function loadAttributes(User $user)
    {
        $user->setAttributes($this->attributes);
    }

From: magezisagesse@hotmail.fr
To: reply@reply.github.com
Subject: RE: [yii2-user]  Profile data from the registrationForm model are not being save in profile table. #541  (#548)
Date: Thu, 26 Nov 2015 10:14:53 +0200




I've installed everything and yii2-user 0.9.5 I see codes that could do the work I'm gonna try it today. Thanks a lot for leading me

From: magezisagesse@hotmail.fr
To: reply@reply.github.com
Subject: RE: [yii2-user]  Profile data from the registrationForm model are not being save in profile table. #541  (#548)
Date: Thu, 26 Nov 2015 09:03:47 +0200




I installed Yii2 manually and think probably it is not installed. I am looking how to check it is installed and how to install it.
I'll let you know how it goes. I am stack in my project of the problem.

Date: Wed, 25 Nov 2015 12:43:50 -0800

**Comment by dmeroff** [comment]
You have to import User class at the beginning of your overridden Profile class since it is located in other namespace:

```php
use \dektrium\user\models\User
```

**Comment by MagSag** [comment]
Thanks a lot !!! it is working perfectly; 
I would like to know when a user confirm email address by clicking the link in his email address does that login him automatically ?

Date: Thu, 26 Nov 2015 07:50:15 -0800

**Comment by MagSag** [comment]
And I would also like to know how can I access the registered user Id directly after the registration in actionregister

From: magezisagesse@hotmail.fr
To: reply@reply.github.com
Subject: RE: [yii2-user]  Profile data from the registrationForm model are not being save in profile table. #541  (#548)
Date: Mon, 30 Nov 2015 11:39:09 +0200







Thanks a lot !!! it is working perfectly; 
I would like to know when a user confirm email address by clicking the link in his email address does that login him automatically ?

Date: Thu, 26 Nov 2015 07:50:15 -0800

**Comment by Alionides** [comment]
hello i have set up phone number field everything is working except on user/settings/account page phone number comes empty from database but its exists in db. here is my overridden settingsForm.php code

`<?php
namespace app\models;

class SettingsForm extends \dektrium\user\models\SettingsForm
{
    /**
     * @var string
     */
    public $phone;
    /**
     * @inheritdoc
     */
    public function rules()
    {
        $rules = parent::rules();
        $rules['phoneRequired'] = ['phone', 'required'];
        $rules['phoneLength']   = ['phone', 'integer'];
        return $rules;
    }
    public function attributeLabels()
    {
        $attributeLabels = parent::attributeLabels();
        $attributeLabels['phone'] = 'Tphone';        
        return $attributeLabels;
    }

    protected function loadAttributes(User $user)
{
$user->setAttributes([
'email' => $this->email,
'username' => $this->username,
'password' => $this->password,
]);
/** @var Profile $profile */
$profile = \Yii::createObject(User::className());
$profile->scenario = 'settings';
$profile->setAttributes([
'phone' => $this->phone
]);
$user->setProfile($profile);
}




}`
