### ISSUE TITLE
urgent problems!-'user already taken' without sending account-verify-mails

### ISSUE THREAD

**Issue by luobenyu** [dektrium/yii2-user#552]
I am using yii2-user to send account-verify-mails for my yii2-advanced project. However, it always seemed strange , as I config my 'mailer' part in common/config.php :
>         'mailer' => [ // within my 'components' part
            'class' => 'yii\swiftmailer\Mailer',
            'useFileTransport' => false, 
            'messageConfig' => [
                'from' => ['13535168941@163.com' => 'sender_name'], 
                'charset' => 'UTF-8',
            ],
            'transport' => [ 
                'class' => 'Swift_SmtpTransport',
                'host' => 'smtp.163.com',
                'username' => '13535168941@163.com',
                'password' => 'my_password_here',
                'port' => '25',
                'encryption' => 'tls',
            ]
        ],

and in dektrium codes,
>         protected function sendMessage($to, $subject, $view, $params = [])
    {
        $mailer = \Yii::$app->mailer;
        $mailer->viewPath = $this->viewPath;
        $mailer->getView()->theme = \Yii::$app->view->theme;
        if ($this->sender === null) {
            $this->sender = isset(\Yii::$app->params['adminEmail']) ? \Yii::$app->params['adminEmail'] : 'no-reply@example.com';
        }

>    
        return $mailer->compose(['html' => $view, 'text' => 'text/' . $view], $params)
            ->setTo($to)
            ->setFrom($this->sender)
            ->setSubject($subject)
            ->send();  }
}

I also config 'adminEmail'  as  '13535168941@163.com' within common/main.php . but the page just showed
>      'user already taken' 

and I receive NO mails from the project.
Is there anything to be really careful when using yii2-user with yii2-advanced template? thanks a lot!

**Comment by dmeroff** [comment]
Probably something is wrong with your smtp connection configuration. There should be no problems with using yii2-user with advanced template.
