### ISSUE TITLE
Cannot access 2 "views" once urlManager is added 

### ISSUE THREAD

**Issue by dfmmalaw** [dektrium/yii2-user#555]
I added UrlManager and the "sign up" and "sign in" pages started working (as they were 404'ing before). Unfortunately, it stopped two of my other links on the homepage from loading. My code is:
 `   'urlManager' => [`
               ` 'class' => 'yii\web\UrlManager',`
                `// Disable index.php`
               ` 'showScriptName' => true,`
               ` // Disable r= routes`
               ` 'enablePrettyUrl' => true,`
                `'rules' => array(`
                    ` '<controller:\w+>/<id:\d+>' => '<controller>/view',`
                    ` '<controller:\w+>/<action:\w+>/<id:\d+>' => '<controller>/<action>',`
                     `'<controller:\w+>/<action:\w+>' => '<controller>/<action>'`
                `),`
          `  ],``

Below is a screenshot of one of the pages trying to load. I am attempting to load `site/story` but `site/index` is loading. Is it because my rules are written incorrectly? I am newbie dev so I apologize if this seems somewhat remedial. By the way awesome extension!

http://prntscr.com/983ldj

**Comment by dmeroff** [comment]
Your probably do have some problems with your url rules, but you have to figure them out yourself.
