### ISSUE TITLE
configuring layout for yii2 user

### ISSUE THREAD

**Issue by msushil** [dektrium/yii2-user#556]
is there any way of configuring the layout for the controllers in the yii2-user module?. the controllers in the module takes default layout. is there configuration parameter or any way to configure the layout used by the controllers in the module ?

**Comment by dmeroff** [comment]
You can set `layout` property of the module.

**Comment by msushil** [comment]
would you please provide the code sample ? I've not found in the documentation.

**Comment by dmeroff** [comment]
```php
'user' => [
  'class' => 'dektrium\user\Module',
  'layout' => 'path-to-your-layout',
],
```

**Comment by msushil** [comment]
thank you.
I have a one question. is there any possibility/way to configure layouts for different controllers in this module? for eg: signin or logout method does not have same layout like in settings controller. if there is any way then please prove me some code sample..

**Comment by dmeroff** [comment]
You can use controller map:

```php
'class' => 'dektrium\user\Module',
'controllerMap' => [
	'login' => [
		'class' => 'dektrium\user\controllers\LoginController',
		'layout' => 'your-layout',
	],
],
```

**Comment by msushil** [comment]
## Thank You for your *response*

**Comment by msushil** [comment]
I think these guides need to be included in the documentation page. Most of the time, everyone has their own layout so it will be very convenient for novice like us to go through documentation page.
