### ISSUE TITLE
Form Submission Via ajax

### ISSUE THREAD

**Issue by MagSag** [dektrium/yii2-user#559]
I am still working on the registration form and would like to submit it via ajax. While submitting it is seems like the call of performAjaxValidation is not allowing the submission(it is ending the application); what can I do about that?

**Comment by dmeroff** [comment]
You can override registration controller and remove ajax validation code.

**Comment by MagSag** [comment]
Yeah I've done that but as I needed the ajax validation I got another way of doing using validationUrl on the form and put the code that was in side the performajaxvalidation in a controller action; so that controller action is the validation url. Thanks a lot dear.
