### ISSUE TITLE
Missing translation of flash message after translation

### ISSUE THREAD

**Issue by condesignpoland** [dektrium/yii2-user#561]
There is a missing translation used in RegistrationForm (line 118). It should be added to messages.
'Your account has been created and a message with further instructions has been sent to your email'

**Comment by dmeroff** [comment]
You can send a pull-request for your language which fixes this.

**Comment by condesignpoland** [comment]
As far as i see it occours all translations (not only my language, also in fr, de etc.). This message isn't just addes to any of translations. It is only seen in RegistrationForm file. I think it was ommited. Anyway thanks for fast reply.

**Comment by garciagaston** [comment]
It's still happening in all translations
