### ISSUE TITLE
Error configuring Backend/Frontend user

### ISSUE THREAD

**Issue by aenima700** [dektrium/yii2-user#562]
Hi.
I'm following the "Yii2-user with Yii2 advanced template" guide and I'm getting the following error:

ReflectionException
Class dektrium\user\filters\FrontendFilter does not exist

And the same for the backend
ReflectionException

Class dektrium\user\filters\BackendFilter does not exist

Any help??

Thanks!

**Comment by dmeroff** [comment]
You either installed yii2-user without composer or using outdated version.
