### ISSUE TITLE
Problem email confirmeted

### ISSUE THREAD

**Issue by Pablossoo** [dektrium/yii2-user#563]
Hi, why email confirmeted not send?  I have use Advanced template

my common/config/main.php

    'modules' => [
        'user' => [
            'class' => 'dektrium\user\Module',
            'enableRegistration'=>true,
            'enableGeneratingPassword'=>true,
            'enableUnconfirmedLogin' => true,
            'enableConfirmation'=>false,
            'confirmWithin' => 21600,
            'cost' => 12,
            'admins' => ['admin'],
    'mailer' => [
    'sender'                => 'My Email', // or ['no-reply@myhost.com' => 'Sender name']
    'welcomeSubject'        => 'Welcome subject',
    'confirmationSubject'   => 'Confirmation subject',
    'reconfirmationSubject' => 'Email change subject',
    'recoverySubject'       => 'Recovery subject',
],
      ],
    ],

**Comment by dmeroff** [comment]
You have to configure mail component of application to send emails. Yii2-user uses it to send mails, so you have to find the way how to configure mail component yourself.

**Comment by Pablossoo** [comment]
Yeea thanks!!  it working!, you can close :)
