### ISSUE TITLE
Restrict site 

### ISSUE THREAD

**Issue by Pablossoo** [dektrium/yii2-user#565]
Hi, i have  one yet problem...
When I  set  in frontend modules 

    'user' => [
            'class' => 'dektrium\user\Module',
            'as frontend' => [
                'class' => 'dektrium\user\filters\FrontendFilter',
                'only' => ['admin/index'], // Block View Admin Users Backend
            ],
        ],
and backend

        'user' => [
            'class' => 'dektrium\user\Module',
            'as backend' => [
                'class' => 'dektrium\user\filters\BackendFilter',
                'only' => ['registration/register'], // Block View Register Backend
            ],
        ],
    ],
gets
Class dektrium\user\filters\BackendFilter does not exist

I updated yii2-user through composer.. and it  not working

**Comment by dmeroff** [comment]
The error ` Class dektrium\user\filters\BackendFilter does not exist` if you are using outdated version. Please, check out which version of module do you use? You can find it in `vendor/dektrium/yii2-user/Module.php` file in VERSION constant.

**Comment by Pablossoo** [comment]
const VERSION = '0.9.3';   this is good version?

**Comment by dmeroff** [comment]
0.9.3 is outdated. Current version is 0.9.5

**Comment by Pablossoo** [comment]
but if i use "dektrium/yii2-user":"0.9.*@dev"  he downloading  me 9.3 version.. ? why?

**Comment by Pablossoo** [comment]
Ok, i upgrade to 9.5, but in user/admin/index i get
Setting unknown property: yii\jui\DatePicker::dateFormat why? 

   "minimum-stability": "dev",
    "require": {
        "php": ">=5.4.0",
        "yiisoft/yii2": ">=2.0.6",
        "yiisoft/yii2-bootstrap": "*",
        "yiisoft/yii2-swiftmailer": "*",
        "c006/yii2-migration-utility": "dev-master",
        "kartik-v/yii2-tree-manager": "@dev",
        "dmstr/yii2-adminlte-asset": "2.*",
        "kartik-v/yii2-widget-switchinput": "*",
		"dektrium/yii2-rbac": "dev-master",
		"dektrium/yii2-user": "0.9.*@dev",
        "yiisoft/yii2-jui": "^2.0"
