### ISSUE TITLE
How to change installation path?

### ISSUE THREAD

**Issue by Leopandro** [dektrium/yii2-user#566]
I have downloaded your yii2-user package, modified it and uploaded it into my github https://github.com/Leopandro/yii2-user. It seems like your package depends on folder name. How i can change installation path into "dektrium"?

Thats my composer.json file:
{
    "name": "yiisoft/yii2-app-basic",
    "description": "Yii 2 Basic Project Template",
    "keywords": ["yii2", "framework", "basic", "project template"],
    "homepage": "http://www.yiiframework.com/",
    "type": "project",
    "license": "BSD-3-Clause",
    "support": {
        "issues": "https://github.com/yiisoft/yii2/issues?state=open",
        "forum": "http://www.yiiframework.com/forum/",
        "wiki": "http://www.yiiframework.com/wiki/",
        "irc": "irc://irc.freenode.net/yii",
        "source": "https://github.com/yiisoft/yii2"
    },
    "minimum-stability": "dev",
    "prefer-stable" : true,
    "require": {
        "php": ">=5.4.0",
        "yiisoft/yii2": ">=2.0.5",
        "yiisoft/yii2-bootstrap": "*",
        "yiisoft/yii2-swiftmailer": "*",
        "dektrium/yii2-user": "dev-master",
        "execut/yii2-widget-bootstraptreeview": "dev-master",
        "2amigos/yii2-file-upload-widget": "~1.0",
        "kartik-v/yii2-widget-select2": "@dev",
        "paulzi/yii2-adjacency-list": "^1.0"
    },
    "require-dev": {
        "yiisoft/yii2-codeception": "*",
        "yiisoft/yii2-debug": "*",
        "yiisoft/yii2-gii": "*",
        "yiisoft/yii2-faker": "*"
    },
    "config": {
        "process-timeout": 1800
    },
    "scripts": {
        "post-create-project-cmd": [
            "yii\\composer\\Installer::postCreateProject"
        ]
    },
    "extra": {
        "yii\\composer\\Installer::postCreateProject": {
            "setPermission": [
                {
                    "runtime": "0777",
                    "web/assets": "0777",
                    "yii": "0755"
                }
            ],
            "generateCookieValidationKey": [
                "config/web.php"
            ]
        },
        "asset-installer-paths": {
            "npm-asset-library": "vendor/npm",
            "bower-asset-library": "vendor/bower"
        }
    }
}

**Comment by dmeroff** [comment]
You don't need to upload modified version of module to github, moreover you don't need to modify module's files directly in most cases. You can just override needed controllers and models as described in documentation.

However if you have reasons you can fork module and make your changes in forked repo, but you have to find out ways of how to do it yoursef.
