### ISSUE TITLE
have mulitiply themes and override views not work 

### ISSUE THREAD

**Issue by buuug7** [dektrium/yii2-user#570]
'view' => [
			'theme' => [
				//'basePath' => '@app/views/themes/basic',
				//'baseUrl' => '@web/themes/basic',
				'pathMap' => [
					'@dektrium/user/views' => '@app/views/user/a.php',
					'@app/views'=>'@app/views/themes/basic',

				],
			],
		],

'user' => [
			'class' => 'dektrium\user\Module',
			'enableUnconfirmedLogin' => true,
			'confirmWithin' => 21600,
			'cost' => 12,
			'modelMap' => [
				'User' => 'backend\models\AdminUser',
				'Profile'=>'backend\models\AdminProfile',
				'Token'=>'backend\models\AdminToken',
			],
			'controllerMap' => [
				'security' => 'backend\controllers\user\SecurityController'
			],
			'admins' => ['admin'],
			'mailer'=>[
				'sender'=>['youpp@126.com'=>'4039']
			]
		],
wether you change any value of '@dektrium/user/views'=>'xxx',the view file will not be override and not give some errors  or exceptions show

**Comment by buuug7** [comment]
will show only 
![image](https://cloud.githubusercontent.com/assets/12119289/11684637/fa4f6aa4-9ead-11e5-897f-3cec920cbd29.png)

**Comment by dmeroff** [comment]
`'@dektrium/user/views' => '@app/views/user/a.php'` you don't need to add `a.php` here. It should just point the directory with overriden views.
