### ISSUE TITLE
There are any way to terminate a user session?

### ISSUE THREAD

**Issue by invaderhd** [dektrium/yii2-user#572]
For example I block an user but since I have persistent login the user keep still logged in.

I think the "block" event should logged out the user.

**Comment by dmeroff** [comment]
At the moment there is now way to do it using yii2-user out of the box. Yii2 also does not support this at the momemnt. You can see discussion [here](https://github.com/yiisoft/yii2/issues/9718)

You can implement it yourself overriding user component, or using db session handler.

However this will be probably implemented in yii2-user in future.
