### ISSUE TITLE
Duplicated flashes

### ISSUE THREAD

**Issue by faustoFF** [dektrium/yii2-user#574]
Page after registration (right after activation email was sended) with message alert "Your account has been created and a message with further instructions has been sent to your email" have duplicated message.

After following to activation link alert message also duplicated.

**Comment by smilemd** [comment]
'enableFlashMessages' => false,

**Comment by faustoFF** [comment]
@smilemd Thanks, this fix my problem. But i think it is not normal when messages duplicated with default settings.

**Comment by dmeroff** [comment]
At the moment YIi2-user shows flash messages itself, however this behavior will probably be changed before alpha release.

**Comment by kepingatp** [comment]
I'm using Yii2 basic template, I've set 'enableFlashMessages' => false inside web.php but it still show duplicate flash. Why it didn't work for me? Any suggestion?
Thanks

**Comment by nakarin4350** [comment]
'modules' => [
        'user' => [
            'class' => 'dektrium\user\Module',
            'enableUnconfirmedLogin' => true,
            'confirmWithin' => 21600,
            'cost' => 12,
            'admins' => ['administrator'],
            'enableFlashMessages' => false,
        ],
    ],
