### ISSUE TITLE
Restrict acces  backend site  for normal user

### ISSUE THREAD

**Issue by Pablossoo** [dektrium/yii2-user#575]
Hey, How I can block enter on the backend site for normal users without rule admin? I would like, that only admin can be see backend site

**Comment by dmeroff** [comment]
If you are asking about restricting access to yii2-user controller in backend (e.g. registration, login, etc) then you should use filters provided with module.

**Comment by Pablossoo** [comment]
No,  as  wrote. I need, to only admin user could  see backend site.  e.g
User: admin
User: Test 

If i login admin, he can see backend site.

If i  login test he can't see backend site and If  type backend site in the  url  should an get error 404 e.g

**Comment by Stitpragya** [comment]
public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'actions' => ['login', 'error','eventcron'],
                        'allow' => true,
                    ],
                    [
                        'actions' => ['logout'],
                        'allow' => true,
                       
                        'roles' => ['@'],
                    ],
                    [
                        'actions' => [ 'index'],
                        'allow' => true,
                         'matchCallback' => function ($rule, $action) {
                            $isadmin="";
                            if(isset(Yii::$app->user->identity->username))
                            $isadmin=Yii::$app->user->identity->username;
                            return $isadmin === 'admin';
                        },

                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }


use this in your site controller.. so only admin user can access the actions.

**Comment by Stitpragya** [comment]
'actions' => [ 'index'], int his array gives list of your actions.. You can use this in anyother controller in backend too
