### ISSUE TITLE
Sometimes error 

### ISSUE THREAD

**Issue by pcimagenca** [dektrium/yii2-user#576]
i have that error on user%2Fsettings%2Fprofile, Argument 1 passed to dektrium\user\controllers\SettingsController::performAjaxValidation() must be an instance of yii\base\Model, null given, called in /home3/jilio1990/public_html/vendor/dektrium/yii2-user/controllers/SettingsController.php on line 86 and defined

**Comment by dmeroff** [comment]
I can not reproduce this problem, if you still have problems with this, please create new issue with the steps which describe how to reproduce problem.

**Comment by tiberiucontiu** [comment]
I had same problem. In my case, the 1 to 1 relation between `user` table and `profile` was broken. There was no correspondent entry in `profile` table for that user. 

I would rather suggest to develop some code, an approach, for this case. Users can be created in different ways, even imported ... if no entries in profile table, then you'll have to dig into code to find out why the application fails for profile routes.

**Comment by pcimagenca** [comment]
i cant remember how solved that problem :( sorry, im have that solved in bitbucket privated repo, i can soon upload to git

**Comment by dead142** [comment]
I hadsame problem, so I haven't `profile` in database for `user`) When I add `profile `problem was solved'/
