### ISSUE TITLE
Admin on Basic App

### ISSUE THREAD

**Issue by XplatformDev** [dektrium/yii2-user#584]
Can you access Admin views on the basic app.  I don't understand how to give my user (me at this point) admin access.  

JG

**Comment by skymanpl** [comment]
In your main config (default web.php) you should have sth like this:
```
$config = [
	// (...)
	'modules' => [
		// (...)
		'class' => 'dektrium\user\Module',
		'user' => [
			// (...)
			'admins'                   => ['admin', 'sky', 'XplatformDev'] //etc.
		],
	]
];
```
So just write usernames in admins array.

**Comment by dmeroff** [comment]
Closed, since answer was given.
