### ISSUE TITLE
REST API tutorial for this module

### ISSUE THREAD

**Issue by xloading** [dektrium/yii2-user#586]
Hello!
Thanks a lot for this module - it helps with user-related features of web application a lot indeed.
But could you advise on the plans of REST API support for yii2-user to improve opportunities for mobile applications development as well? Under issue #114 I found that you planned to add it quite long time ago but it still doesn't seem to be implemented.
Is there any chance we can see it in any of the nearest releases?

**Comment by dmeroff** [comment]
Unfortunately, I don't think there will be any implementation of REST API support for Yii2-user in the nearest future. However you are very welcome to implement it yourself and then send a pull-request ;)
