### ISSUE TITLE
Change setting module

### ISSUE THREAD

**Issue by Pablossoo** [dektrium/yii2-user#588]
I would like change setting module, e.g enableRegistration, but  through my  view and not manual in config file. What i need do?

**Comment by mzdani** [comment]
I have same problem like you sir, I store some web settings on database, and I want change Yii2 User some module config dynamically. So, I use this code to change Yii2 User module.

```php
<?php

// Get the current module
$UserModule = Yii::$app->getModule('user');

// Change public variable define on module
$UserModule->enableFlashMessages = false;
```

And I write those code with Yii2 `BootstrapInterface` class. So, everytime web open, the code will execute.

Maybe it's not a safer & good way to do it. Sorry, I'm just a newbie.

**Comment by dmeroff** [comment]
@mzdani has given correct approach. However you should never change module options from your views.
