### ISSUE TITLE
captcha always incorrect

### ISSUE THREAD

**Issue by ouewqa** [dektrium/yii2-user#591]
RegistrationForm

```
 public function rules()
    {
            $rules[] = ['captcha', 'required'];
            $rules[] = [
            'captcha',
            'captcha',
            'captchaAction' =>'/site/captcha',
            'message'       => '验证码错误，请重新输入或点击验证码图片重试。',
        ];
        return $rules;
    }
```

SiteController
```
 public function actions()
    {
        return [
            'captcha' => [
                'class'           => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
                'minLength'       => 4,
                'maxLength'       => 4,
            ],
        ];
    }
```

register.php

```
<?= $form->field($model, 'captcha')->widget(
                    Captcha::className(),
                    [
                        'captchaAction' => '/site/captcha',
                        'imageOptions'  => [
                            'id'    => 'captchaImg',
                            'alt'   => '点击换图',
                            'title' => '点击换图',
                            'style' => 'cursor:pointer',
                        ],
                    ]
                ) ?>
```

After I type captcha, browser send a ajax request for validate, and it passed.

when I submit the form, It always display captcha error.

In YII2 debugger. I found after browser sent a ajax. In session, the value of  "__captcha/site/captcha" has changed.

post captcha `karg`, ajax validate is OK
```
$_POST
Name	Value
_csrf	'M2pVR1hKZ0UKIiECNQ0TJwMoYgAheDB9WEclNToZVBd5PzkpOz0JJw=='
register-form	[
    'username' => 'test'
    'email' => 'test@test.com'
    'password' => '123456'
    'captcha' => 'karg'
]
```
But in session captcha's value is `korg`, So submit form is always fail.
```
$_SESSION
Name	Value
__flash	[]
__captcha/site/captcha	'korg'
__captcha/site/captchacount	2
```

what do I miss?

**Comment by cinghie** [comment]
Hi ouewqa,

I had the same problem and the cause is just validation ajax .

You can easily solve the problem overriding the registration view changing the Activeform from AjaxValidation to ClientValidation like this:

from

```
<?php $form = ActiveForm::begin([
                    'id'                     => 'registration-form',
                    'enableAjaxValidation'   => true,
                    'enableClientValidation' => false,
 ]); ?>
```

to 

```
<?php $form = ActiveForm::begin([
                    'id'                     => 'registration-form',
                    'enableAjaxValidation'   => false,
                    'enableClientValidation' => true,
 ]); ?>
```

**Comment by withoutfx** [comment]
thx cinghie

**Comment by tommyblink182** [comment]
To me it does not work in any way possible. I also tried to disable AJAX validation for individual field. I'm using "yii2-user-extended" developed by @cinghie , https://github.com/cinghie/yii2-user-extended

    <?= $form->field($model, 'captcha', ['enableAjaxValidation' => false, 'enableClientValidation' => false] )->widget(Captcha::className(), [
            'captchaAction' => ['/site/captcha'],
            'imageOptions'  => [
                'id'    => 'captchaImg',
                'alt'   => 'Immagine captcha',
                'title' => 'Captcha',
                'style' => 'cursor:pointer'
            ],
            'options' => ['class' => 'form-control'],
            'template' => '<div class="row"><div class="col-md-6">{input}</div><div class="col-md-6">{image}</div></div>'
    ]); ?>

**Comment by MagSag** [comment]
Are you submitting the form using Ajax? Because a form that contains a captcha must not be submitted using ajax.

**Comment by cinghie** [comment]
You need to active enableClientValidation: 'enableClientValidation' => true

**Comment by tommyblink182** [comment]
It does not work. The only way to start recording is removed from the model attribute 'captcha'. I can't understand why, are days that I try various modifications.

**Comment by dmeroff** [comment]
Captcha does not work with ajax validation enabled ([see](https://github.com/yiisoft/yii2/blob/master/framework/captcha/CaptchaValidator.php#L20). I've added note to the docs.

So in order to make it work you should disable ajax validation.
