### ISSUE TITLE
How can i make one view for registration and login?

### ISSUE THREAD

**Issue by gorsargsyan** [dektrium/yii2-user#592]
![inloggen - marktplaza nl](https://cloud.githubusercontent.com/assets/9119897/12261338/d7c27976-b939-11e5-8b69-ef091b645cbb.png)

like this

**Comment by gomonkey** [comment]
in registration view just add the login plugin:
`php
use dektrium\user\widgets\Login;
echo  Login::widget(); 
`

**Comment by dmeroff** [comment]
Information on this has been added to [FAQ](https://github.com/dektrium/yii2-user/blob/master/docs/faq.md).
