### ISSUE TITLE
Access to Admin

### ISSUE THREAD

**Issue by anushkanz** [dektrium/yii2-user#594]
Hi i am try to add super admin for Advance template, Please help that.
This route is not working " /user/admin/index "

**Comment by diego-betto** [comment]
Same problem. Try " /user/admin"

**Comment by anushkanz** [comment]
this urlManager should in common config

**Comment by anushkanz** [comment]
I have done this change what you ask but its not working

**Comment by noname007** [comment]
what's the return?

**Comment by gfirem** [comment]
I have the same problem

**Comment by noname007** [comment]
@gfirem you'd better view the log says..

**Comment by dmeroff** [comment]
If route `/user/admin/index` is not working, then you didn't configure module correctly.
