### ISSUE TITLE
Adding Field to the Profile table from registration form fails when User model is Overriden

### ISSUE THREAD

**Issue by Uthpala** [dektrium/yii2-user#596]
It fails if I override the dektrium User model. 

The below is the error given. 
Declaration of app\models\RegistrationForm::loadAttributes(app\models\User $user) should be compatible with dektrium\user\models\RegistrationForm::loadAttributes(dektrium\user\models\User $user)

Here is the overridden model 

<?php
namespace app\models;
use dektrium\user\models\User as BaseUser;

class User extends BaseUser
{

}

**Comment by asialong** [comment]
hi, do you solve this problem?

**Comment by Uthpala** [comment]
Nope skipped it by not overriding the user model.

**Comment by asialong** [comment]
How you solve it?

**Comment by Uthpala** [comment]
Like I did NOT solve it. I used the model that was given by dektrium. Check out the last lesson changing view file in Yii user module in doingiteasychannel. I use the dektrium user class.

**Comment by asialong** [comment]
OK ,Thanks a lot.

**Comment by gomonkey** [comment]
well, you are ovveride user and not profile... look my model:
```php
use dektrium\user\models\Profile as ProfileUser; 
 class Profile extends ProfileUser
{

**Comment by asialong** [comment]
Okay, thank you, I try to do

**Comment by dmeroff** [comment]
You should not change the signature of the `loadAttributes` method, so it should look like this:

```php
function loadAttributes(\dektrium\user\models\User $user)
```
