### ISSUE TITLE
Failed to apply migration for PostgreSQL

### ISSUE THREAD

**Issue by zevs-git** [dektrium/yii2-user#601]
*** applying m150623_212711_fix_username_notnull
    > alter column username in table {{%user}} to string(255) NOT NULL ...Exception 'yii\db\Exception' with message 'SQLSTATE[42601]: Syntax error: 7 ERROR:  syntax error at or near "NOT"
LINE 1: ...LE "user" ALTER COLUMN "username" TYPE varchar(255) NOT NULL
                                                               ^
The SQL being executed was: ALTER TABLE "user" ALTER COLUMN "username" TYPE varchar(255) NOT NULL'

in /home/zelenskiy/ppc_dream_tool/vendor/yiisoft/yii2/db/Schema.php:628

Error Info:
Array
(
    [0] => 42601
    [1] => 7
    [2] => ERROR:  syntax error at or near "NOT"
LINE 1: ...LE "user" ALTER COLUMN "username" TYPE varchar(255) NOT NULL
                                                               ^
)

**Comment by rockbarato** [comment]
Hi @zevs-git,

Remove **NOT NULL** at line 19 in file `vendor/dektrium/yii2-user/migrations/m150623_212711_fix_username_notnull.php` file located at

Regards.

**Comment by dmeroff** [comment]
This issue has been fixed by [this commit](https://github.com/dektrium/yii2-user/commit/c7f5d9874c74e2780bcdaeb431ddf685cbdbfde9), you should update module.
