### ISSUE TITLE
Unnecessary strict typing in User class

### ISSUE THREAD

**Issue by Ziggizag** [dektrium/yii2-user#604]
Hi,

I tried using https://github.com/cinghie/yii2-user-extended and found an issue with strict typing.

Your User class has a following function signature:

`protected function loadAttributes(User $user)`

and this expects a `dektrium\user\models\User` object as an argument.

Unfortunately, Cinghie extended your classes using model mapping:

`'User' => 'cinghie\yii2userextended\models\User'`

what is very convenient, but namespace is changed so `cinghie\yii2userextended\models\User` object is passed to **loadAttributes** function as an argument rather than a `dektrium\user\models\User` object.

Consequently, a **PHP Strict Warning** exception is thrown with the following message:

**Declaration of cinghie\yii2userextended\models\RegistrationForm::loadAttributes() should be compatible with dektrium\user\models\RegistrationForm::loadAttributes(dektrium\user\models\User $user)**

I encourage you to drop strict typing in this particular case as the most simple and effective solution and - perhaps - check argument being passed to **loadAttributes** function against implementing **IdentityInterface**.

That would allow avoiding **PHP Strict Warning** exceptions in a future.

Rgs,
Zig

**Comment by dmeroff** [comment]
There is nothing wrong with typing in `loadAttributes` method. However there is a problem with https://github.com/cinghie/yii2-user-extended because you must not change method signature in child classes, so it will not cause any warnings. The only thing that can be done here is that in yii2-user-extended, `loadAttributes` method signature should be changed to:
```php
protected function loadAttributes(\dektrium\user\models\User $user)
```

**Comment by cinghie** [comment]
thanks @Ziggizag for your issue and very thanks to @dmeroff for your work. I have fix it in my extension

**Comment by Ziggizag** [comment]
Your welcome!
