### ISSUE TITLE
Error messages translated into Russian

### ISSUE THREAD

**Issue by kvush** [dektrium/yii2-user#606]
Here same mistake in messages\ru\user  line 165 
'Your account on {0} has been created' => 'Ваш аккаунт на сайте "{0}" был успешно создан и мы сгенерировали пароль для вас'.
In case when enableGeneratingPassword set false, in Welcome message we get  double text with password generated info.
Change to 'Your account on {0} has been created' => 'Ваш аккаунт на сайте "{0}" был успешно создан'.

**Comment by dmeroff** [comment]
Can you please send a pull-request?
