### ISSUE TITLE
User::afterSave() method returns nothing - bad for overriding!

### ISSUE THREAD

**Issue by Ziggizag** [dektrium/yii2-user#608]
Model events should follow general signature for proper overriding:

public function beforeEvent($param1, $param2)
{
    if (parent::beforeEvent($param1, $param2)) {
        // ...custom code here...
        return true;
    } else {
        return false;
    }
}

Returning no value (boolean) makes it hard for overriding following this signature!

**Comment by dmeroff** [comment]
`afterSave` method has no return valuem and I don't think it really needs any changes.
