### ISSUE TITLE
Time for a 0.9.6 release?

### ISSUE THREAD

**Issue by schmunk42** [dektrium/yii2-user#609]
I just stumbled upon: https://github.com/dektrium/yii2-user/issues/526
And noticed, last release was almost half a year ago :)

Maybe it's time for another one?

Related: https://github.com/phundament/app/issues/195

**Comment by thyseus** [comment]
See https://github.com/dektrium/yii2-user/issues/621.

I also hope for a 1.0.0 "stable" release.

**Comment by dmeroff** [comment]
0.9.6 will be tagged on this sunday. Sorry for the delay.
