### ISSUE TITLE
How to save user_id

### ISSUE THREAD

**Issue by ionutz** [dektrium/yii2-user#610]
I have this code,

 ` public function actionCreate() {
        $user = \Yii::createObject(RegistrationForm::className());
        $post = new Post();

        if ($user->load(Yii::$app->request->post()) && $post->load(Yii::$app->request->post()) && Model::validateMultiple([$user, $post])) {

            $user->save(false); 
          $post->user_id = $user->id;  ???
            $post->save(false);

            return $this->redirect(['view', 'id' => $post->id]);
        } else {
            return $this->render('create', [
                        'user' => $user,
                        'post' => $post,
            ]);
        }
    }`

how to save user_id?

**Comment by gomonkey** [comment]
If the user is logged just write this code:
Yii::$app->user->id

**Comment by ionutz** [comment]
Thanks, but is not logged in

**Comment by gomonkey** [comment]
if is not logged in, that means there is not user, so you can not have the ID.

**Comment by noname007** [comment]
if the user have stored in the db ,you can query.If not and not login,the question will be no anwser.

**Comment by dmeroff** [comment]
Closed, since answer was given
