### ISSUE TITLE
gettin Error "Setting unknown property: dektrium\user\Module::authTimeout"

### ISSUE THREAD

**Issue by rumes** [dektrium/yii2-user#611]
my configuration is

`'user' => [
            'authTimeout'=> 100,
            'class' => 'dektrium\user\Module',
            'admins' => ['uthpala'],
            'modelMap' => [
                'Profile' => 'app\models\Profile',
            ],
            'controllerMap' => [
                'admin' => 'app\controllers\user\AdminController',
                'security' => 'app\controllers\user\SecurityController',
                'settings' => 'app\controllers\user\SettingsController',
            ],
        ],`
what is wrong with the code?.

**Comment by dmeroff** [comment]
There is no property named `authTimeout` in yii2-user.
