### ISSUE TITLE
captcha broken when override User Model

### ISSUE THREAD

**Issue by withoutfx** [dektrium/yii2-user#612]
actually im using this in common config area:
user' => [
'class' => 'dektrium\user\Module',
'modelMap' => [
'User' => 'app\models\User',
],
],

but, afterthat all the capcha image is broken only when i try to ovrride User Model.

**Comment by dmeroff** [comment]
I dont think the issue with captcha images has any connection to overriding yii2-user model. You have to debug the problem yourself.
