### ISSUE TITLE
Error in Login::widget

### ISSUE THREAD

**Issue by garciagaston** [dektrium/yii2-user#613]
After login in Login::widget returns the following error:

PHP Recoverable Error – yii\base\ErrorException

Object of class yii\web\Response could not be converted to string
1. in /var/www/ol/vendor/yiisoft/yii2/base/Widget.php

$out = $widget->run();
        } catch (\Exception $e) {
            // close the output buffer opened above if it has not been closed already
            if (ob_get_level() > 0) {
                ob_end_clean();
            }
            throw $e;
        }
 
        return ob_get_clean() . $out;
    }
 
    private $_id;

**Comment by garciagaston** [comment]
class Login extends Widget
{
    /** @var bool */
    public $validate = true;

    /** @inheritdoc */
    public function run()
    {
        $model  = Yii::createObject(LoginForm::className());
        $action = $this->validate ? null : ['/user/security/login'];

        if ($this->validate && $model->load(Yii::$app->request->post()) && $model->login()) {
            return Yii::$app->response->redirect(Yii::$app->user->returnUrl);
        }

This return fails!!

**Comment by dmeroff** [comment]
Thank you for reporting this.

**Comment by dmeroff** [comment]
Fixed!
