### ISSUE TITLE
Gravatar http(s)

### ISSUE THREAD

**Issue by andmemasin** [dektrium/yii2-user#614]
Gravatars are linked on http which ends up as ssl warnings in browser if https is used.
Would it be possible to add the protocol identification and use https://gravatar.com ... if ssl is used on site?

**Comment by dmeroff** [comment]
Done!
From now you can also access avatar url by using `getAvatarUrl` method of Profile model:

```php
\Yii::$app->user->identity->profile->getAvatarUrl();
// or you can specify size of avatar
\Yii::$app->user->identity->profile->getAvatarUrl(150);
```

**Comment by andmemasin** [comment]
Thank you!
