### ISSUE TITLE
How to change layout of controller with Advanced Template

### ISSUE THREAD

**Issue by tuannda** [dektrium/yii2-user#616]
I want change layout of Login controller in admin

**Comment by dmeroff** [comment]
You should use controllerMap property of `user` module:

```php
'user' => [
  'class' => 'dektrium\user\Module',
  'controllerMap' => [
    'admin' => [
      'class' => 'dektrium\user\controllers\AdminController',
      'layout' => 'your-layout',
    ],
  ],
],
```

**Comment by dmeroff** [comment]
I'll add this information to docs.

**Comment by dmeroff** [comment]
I've added [F.A.Q page](https://github.com/dektrium/yii2-user/blob/master/docs/faq.md) in documentation, where I described how to change layout for given controller.
