### ISSUE TITLE
Array to string conversion

### ISSUE THREAD

**Issue by mtvw** [dektrium/yii2-user#622]
I got this error on my application:

Array to string conversion
1. in /home/xxxxxxxxxxx/vendor/dektrium/yii2-user/views/_alert.php at line 23
14151617181920212223242526272829 */
?>
 
```
<?php if ($module->enableFlashMessages): ?>
    <div class="row">
        <div class="col-xs-12">
            <?php foreach (Yii::$app->session->getAllFlashes() as $type => $message): ?>
                <?php if (in_array($type, ['success', 'danger', 'warning', 'info'])): ?>
                    <div class="alert alert-<?= $type ?>">
                        <?= $message ?>       /* this is where the error happens */
                    </div>
                <?php endif ?>
            <?php endforeach ?>
        </div>
    </div>
<?php endif ?>
```

happened only once, when trying to access /user/login
when I opened the same page again, there was no error anymore (probably because the flash messages were already "viewed" by then). I have no idea what the flash messages were about and I can't reproduce the problem

**Comment by uldisn** [comment]
In 23 row replace "=$message" with var_dump($message) and check, where incorect used Yii::$app->getSession()->setFlash().

**Comment by dmeroff** [comment]
Closed, because I dont have any information on how to reproduce the issue.
