### ISSUE TITLE
How can i configure my aplication in YII2 , for login to work in subdomain

### ISSUE THREAD

**Issue by josemonmaliakal** [dektrium/yii2-user#623]
How can i configure my aplication in YII2 , for login to work in subdomain. I'm using advanced template

**Comment by dmeroff** [comment]
You have to configure your session component, you can read more in [Yii2-cookbook](https://github.com/samdark/yii2-cookbook/blob/master/book/cookies.md#cross-subdomain-authentication-and-identity-cookies)
