### ISSUE TITLE
Loging out is not working and is prompting error

### ISSUE THREAD

**Issue by MagSag** [dektrium/yii2-user#625]
When I try to log out( I am getting the following error message:

> exception 'yii\web\MethodNotAllowedHttpException' with message 'Method Not Allowed. This url can only handle the following request methods: POST.' in C:\wamp\www\pub\vendor\yiisoft\yii2\filters\VerbFilter.php:105
> Stack trace:

And if I comment the following code from the behaviors function in the securityController; everything is working perfectly:
```

 'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
```
What is the problem?

**Comment by adipriyantobpn** [comment]
the VerbFilter configuration in your controller behavior method is prevented user to access logout action, except POST http request method.

So, it is clear why after you delete the VerbFilter configuration, logout action can be accessed via any POST or GET http request

**Comment by MagSag** [comment]
the problem how can I indicate in anchor element that the method to send the request should be POST.

**Comment by dmeroff** [comment]
You can check out how logout is implemented in [yii2-app-basic template](https://github.com/yiisoft/yii2-app-basic/blob/master/views/layouts/main.php#L46) and adjust logout url accordingly.
