### ISSUE TITLE
Setting Module emailChangeStrategy to Module::STRATEGY_SECURE

### ISSUE THREAD

**Issue by MagSag** [dektrium/yii2-user#626]
How(where) can set the User module emailChangeStrategy to Module::STRATEGY_SECURE; I tried to do it as following in config.php(module section) : 

`'emailChangeStrategy'=>Module::STRATEGY_SECURE,`

but prompted error; I understand that I don't know how to do it; so any type of help is appreciable

**Comment by adipriyantobpn** [comment]
You must use fully qualified class name to refer Module class, then specity the property name

here is the example:
'emailChangeStrategy' => \dektrium\user\Module::STRATEGY_SECURE

**Comment by dmeroff** [comment]
@adipriyantobpn is correct
