### ISSUE TITLE
support windows sql servevr

### ISSUE THREAD

**Issue by rdvitka** [dektrium/yii2-user#633]
Whether it will support windows sql server?

**Comment by ascalabro** [comment]
Yii2 supports connecting to Windows SQL Server
See Yii2 documentation for connecting your Yii2 application to a database server [here](http://www.yiiframework.com/doc-2.0/guide-db-dao.html)
Here's a usage example http://www.yiiframework.com/forum/index.php/topic/61115-select-schema-and-table-in-sqlserver-with-yii2/

**Comment by dmeroff** [comment]
I have no plans on implementing this by myself.
If you need yii2-user to support windows sql server, you have to adjust migrations accordingly and make sure that they are applied correctly. Then you are very welcome to send a pull-request ;)
