### ISSUE TITLE
I don't undestand how get user username and avatar from social

### ISSUE THREAD

**Issue by hrupin** [dektrium/yii2-user#635]
Hello. Very good modul, thank you very match. But i not undestand how get data user from VK.
Please talk me how can i do

**Comment by dmeroff** [comment]
At the moment, there isn't any guide, which describes the way you can retrieve social network data. However I'll try to add documentation on this point in a few days.

**Comment by hrupin** [comment]
Thank you

**Comment by dmeroff** [comment]
I've added basic exaple in [docs](https://github.com/dektrium/yii2-user/blob/master/docs/social-auth.md#how-to-access-social-network-attributes). I'll try to add more complex example a little bit later.

**Comment by hrupin** [comment]
Спасибо большое.
