### ISSUE TITLE
Class 'dektrium\user\widgets\Login' not found

### ISSUE THREAD

**Issue by VoroninAndr** [dektrium/yii2-user#636]
Sorry, I'm beginner on Yii, and can't find answer for my problem.
I'm installed Yii2 advance and dektrium yii2-user module.

my config:
```
'modules' => [
        'user' => [
            'class' => 'dektrium\user\Module',
          ...
        ],
    ],
```

I try to use Login Widget.
In view file, I write:

`use dektrium\user\widgets\Login;`
and than
`Login::widget();`

I get the error:

> Class 'dektrium\user\widgets\Login' not found

What I need to do?

**Comment by dmeroff** [comment]
Did you install Yii2-user using composer?

**Comment by VoroninAndr** [comment]
Yes. Now I understood what was going on. After install I just copied it on local server without composer autoload files. I was my mistake, sorry.

**Comment by Andreslav** [comment]
Люди добрые, помогите!

У меня та же проблема: "Class 'dektrium\user\widgets\login' not found".

Подключаю так:
```
use dektrium\user\widgets\Connect;
use dektrium\user\widgets\login;
```

Затем звоню:
`<?= Login::widget() ?>`

Причём это работает:
`<?= Connect::widget() ?>`

------

Good people, help!

I have the same problem: "Class 'dektrium\user\widgets\login' not found".

I connect this way:
```
use dektrium\user\widgets\Connect;
use dektrium\user\widgets\login;
```

Then call:
`<?= Login::widget() ?>`

And it works:
`<?= Connect::widget() ?>`

**Comment by Andreslav** [comment]
Проблема решена. Опечатка в пути..

---
Problem solved. Typo on the way ..
