### ISSUE TITLE
Create a new table and add fields associated with User

### ISSUE THREAD

**Issue by tommyblink182** [dektrium/yii2-user#641]
Hi,
I created a new table 'Businsess' and on this I created 'ActiveRecord', I did override of the RegistrationForm inserting attributes, rules, scenarios etc.
I did override User by adding methods getBusiness() setBusiness().
During registration how do I associate these attributes and save them?

Whereas the relationship between User and Business and hasOne (same as the table Profile).

I do override of loadAttributes or more?

Thanks in advance.

**Comment by dmeroff** [comment]
I dont clearly understand what is your problem? Could you provide more detailed explanation, and code snippets which tried to use and errors which you got.

**Comment by yarrgh** [comment]
@tommyblink182 I'm assuming that you are trying to use setBusiness() to create and persist the Business ActiveRecord, correct? When the User ActiveRecord is saved, it doesn't save other related ActiveRecords. If you want data from other related ActiveRecords (ex: your Business Active Record) to persist as well, you'll have to specifically tell that ActiveRecord to `save()`.

If I'm wrong, please, somebody call me out on it.

**Comment by tommyblink182** [comment]
Thanks anyway but I used like() method in the model.

Thank you very much

**Comment by uldisn** [comment]
I prefer all person data manage in separate extension. That allow create person record with out login rights. When necessary, person can invite (create login record and send invitation by email). For Yii1 I created module https://github.com/DBRisinajumi/d2person. [Screen example](http://www.weberp.lv/uploads/images/Gallery/AtvalinajumuUzskaite/Personas-Dati.jpg)
