### ISSUE TITLE
RecoveryController not validating the password reset Url

### ISSUE THREAD

**Issue by choxx** [dektrium/yii2-user#650]
At line 156, $token->isExpired is always giving true i.e. I'm not able to reset password. 
However changing $token->getIsExpired() directly gives the exact result  i.e. making user able to display reset password form if clicked within the time mentioned in 'recoverWithin' var in config.php
Please review.

**Comment by dmeroff** [comment]
I can not reproduce this issue, could you please provide more information.
Actually, `$token->isExpired` and `$token->getIsExpired()` mean the exact same thing.

**Comment by choxx** [comment]
Yeah I am getting these two are exactly same but dunno why it isn't working. I tried a number of times with setting **recoverWithin** time with different different values (30, 60, 90, 1800, 3600, .. seconds).`$token->isExpired` didn't work for me. However changing it to `$token->getIsExpired()` worked like a charm. I'm also trying to figure it out why is it happening!!
