### ISSUE TITLE
Php7 performAjaxValidation trait compatibilty 

### ISSUE THREAD

**Issue by akaSStalkALEX** [dektrium/yii2-user#652]
Here's error: 
```
Declaration of dektrium\user\traits\AjaxValidationTrait::performAjaxValidation(yii\base\Model $model) should be compatible with dektrium\user\controllers\AdminController::performAjaxValidation($model)
```

**Comment by dmeroff** [comment]
I cannot reproduce this issue. Actually AdminController does not use AjaxValidationTrait, so I have no idea how did you even get this problem. You have to provide more information, so I'll be able to fix it.

**Comment by akaSStalkALEX** [comment]
Sorry that I bothered you and wasted your time. I overrided `actionCreate` in `AdminController` and thought that `performAjaxValidation` method came from trait, hadn't noticed it in controller.
