### ISSUE TITLE
404 error on advanced app if backend is subdir

### ISSUE THREAD

**Issue by macklus** [dektrium/yii2-user#653]
Hi:

I install advanced app like:
www.domain.com -> frontend
www.domain.com/admin -> backend

after install yii2-user, it works on frontend, but always return error on backend.

Module config is:

`'modules' => [
        'user' => [
            'class' => 'dektrium\user\Module',
            'enableFlashMessages' => true,
            'enableRegistration' => false,
            'enableGeneratingPassword' => true,
            'enableConfirmation' => true,
            'enableUnconfirmedLogin' => false,
            'enablePasswordRecovery' => true,
            'confirmWithin' => 86400,
            'rememberFor' => 1209600,
            'recoverWithin' => 21600,
            'admins' => ['macklus'],
            'cost' => 10,
            'urlPrefix' => '/user',
            'urlRules' => [],
        ],
    ],`

is a urlPrefix problem ? who can this scenary be done?

**Comment by dmeroff** [comment]
I don't know, I never tried to use advanced template in subdir, and I cannot help you.
