### ISSUE TITLE
Error when overriding Profile class

### ISSUE THREAD

**Issue by chtidom** [dektrium/yii2-user#654]
Hi,

I did override the Profile class and I tried to change the views of the updating form accordingly (?r=user%2Fadmin%2Fupdate-profile&id=1). I then got the following error : null given on line 256 of AdminController while an instance of Profile was expected.
I did override the AdminController to change the code as follows:
        $profile = $user->profile;     
        if ($profile == null) {
            $profile = Yii::createObject(Profile::className());
            $profile->link('user', $user);
        }
        $event   = $this->getProfileEvent($profile);
instead of 
        $profile = $user->profile;
        $event   = $this->getProfileEvent($profile);
        if ($profile == null) {
            $profile = Yii::createObject(Profile::className());
            $profile->link('user', $user);
        }
Is it a bug ?

**Comment by dmeroff** [comment]
This is a bug, and it has been fixed (https://github.com/dektrium/yii2-user/blob/master/controllers/SettingsController.php#L142) in master branch.
