### ISSUE TITLE
Image cropper or gravatar

### ISSUE THREAD

**Issue by DmitryBay** [dektrium/yii2-user#656]
Idea:
 
Adding next type of user's avatars:
- use gravatar
- use basic file upload widget 
- use croppic widget

Why?
I make more than 10 projects on yii2 with this module, and I always make functional wiht uploading images.

**Comment by SlimSavernake** [comment]
говорили, что в первой версии будет аватар
осталось узнать, когда будет первая версия

**Comment by smilemd** [comment]
если есть наработки, попробуйте добавить pull request, многие думаю оценят.

**Comment by dmeroff** [comment]
Support for uploading avatars will be in stable version 1.0.0. However, I'm sorry, but I don't know when it will be released :( I'm really busy right now, and I don't think that I start work more on Yii2-user before summer. But you're very welcome to send pull-requests.
