### ISSUE TITLE
User's login can be e-mail?

### ISSUE THREAD

**Issue by DmitryBay** [dektrium/yii2-user#660]
I my project, I can insert email as login. Is this Issue? 

Because, when we Login, if we input email, it will find email, no user login.

**Comment by smilemd** [comment]
From what I know you can use email as login credentials.

**Comment by DmitryBay** [comment]
```
In User:
/** @var string Default username regexp */
    public static $usernameRegexp = '/^[-a-zA-Z0-9_\.@]+$/';
```

We can have 
login@example.com as login
and
email@example.com as email. 

but in:
vendor/dektrium/yii2-user/Finder.php

`/**
     * Finds a user by the given username or email.
     *
     * @param string $usernameOrEmail Username or email to be used on search.
     *
     * @return models\User
     */
    public function findUserByUsernameOrEmail($usernameOrEmail)
    {
        if (filter_var($usernameOrEmail, FILTER_VALIDATE_EMAIL)) {
            return $this->findUserByEmail($usernameOrEmail);
        }

        return $this->findUserByUsername($usernameOrEmail);
    }`

It means, we cant login,  using "login@example.com".

**Comment by DmitryBay** [comment]
So, will it issue been fix? 

Because now, username allow emails. But this username-email not worked in login.

**Comment by dmeroff** [comment]
Yes there is a little problem with this, but I don't have any ideas on how to fix it. If you have any ideas on how to fix this issue, please send a pull-request.
