### ISSUE TITLE
RESTful API

### ISSUE THREAD

**Issue by thecortex** [dektrium/yii2-user#661]
Is there a built-in way that works out of the box for exporting the class functionality via a RESTful API?

**Comment by thecortex** [comment]
I found you have already discussed this matter as a feature for a future version. I'd love to start on a patch for this feature.
I guess we need also to consider API authentication, as per this documentation:
http://www.yiiframework.com/doc-2.0/guide-rest-authentication.html

**Comment by dbd5** [comment]
@thecortex 
I'm sure Dmitry will welcome your patch, just implement and send a pull request. See https://github.com/dektrium/yii2-user/issues/586

**Comment by thecortex** [comment]
@dbd5 , thank you, am I on the right track though? By extending the class to authenticate API users - the developers & devices using the API - through REST providing a bearer token in return as a first step? Then, we see how to expose more features step by step?

**Comment by dmeroff** [comment]
You're very welcome to implement this, start work, then send a pull-request and I'll review your code.

**Comment by mtangoo** [comment]
#742
