### ISSUE TITLE
Setting unknown property: yii\jui\DatePicker::dateFormat

### ISSUE THREAD

**Issue by Richie1710** [dektrium/yii2-user#672]
Hello I installed yii2-user,

my Version is '1.0.0-dev';.
When I Try to open index.php?r=user/admin/index I get a error:

Setting unknown property: yii\jui\DatePicker::dateFormat, 
I also tryed to replace with files from master branch and did migrate step:

php yii migrate/up --migrationPath=@vendor/dektrium/yii2-user/migrations
Yii Migration Tool (based on Yii v2.0.8-dev)
No new migrations found. Your system is up-to-date.

**config: **

 'modules' => [
        'user' => [
            'class' => 'dektrium\user\Module',
            'enableUnconfirmedLogin' => true,
            'admins' => ['admin'],
            'confirmWithin' => 21600,
            'cost' => 12
            
        ],
        'rbac' => [
            'class' => 'dektrium\rbac\Module',
        ],
],

Hope you can help me.

**Comment by dmeroff** [comment]
Which version of `yiisoft/yii2-jui` do you have installed?

**Comment by veyselsahin** [comment]
I think you have to remove this parameter because index view working without this as expected. I override views and removed dateFormat parameter.
