### ISSUE TITLE
Getting unknown property: app\models\User::isAdmin

### ISSUE THREAD

**Issue by brain2xml** [dektrium/yii2-user#673]
On http://sitename/user/admin have error 

 in /home/rus/yii/adv/vendor/dektrium/yii2-user/filters/AccessRule.php at line 40 – yii\base\Object::__get('isAdmin')
```

            } elseif ($role === '@') {
                if (!\Yii::$app->user->isGuest) {
                    return true;
                }
            } elseif ($role === 'admin') {
                if (!\Yii::$app->user->isGuest && \Yii::$app->user->identity->isAdmin) {
                    return true;
                }
            }
        }
 
        return false;

```
my config

```
	'modules' => [
					'user' => [
							'class' => 'dektrium\user\Module',
							'enableUnconfirmedLogin' => true,
							'confirmWithin' => 21600,
							'cost' => 12,
							'admins' => ['admin']
					],
			],

```

**Comment by ckristo** [comment]
Hi,

I guess you have to configure Yii2's user component to use Yii2-user's User class:

````php
// web.php config file
// ...
'components' => [
        // ...
        'user' => [
            'identityClass' => 'dektrium\user\models\User',
            'enableAutoLogin' => true,
        ],
        // ...
// ...
````
This should go into the install instructions.

**Comment by brain2xml** [comment]
You right! thanks! 
One small question. After migration I have User table in my db. But it empty. So, how can I login as admin if no record in table?

**Comment by ckristo** [comment]
You can create a user via the yiic command, and add the user to the 'admins' property.

BR, Chris

**Comment by ckristo** [comment]
For the yiic command to be available, you have to add the yii2-user module to the console config as well. See https://github.com/dektrium/yii2-user/blob/master/docs/console.md

BR, Chris

**Comment by brain2xml** [comment]
Hooray! it works!
Many thanks!
