### ISSUE TITLE
Adding Yii2-User to existing application

### ISSUE THREAD

**Issue by newscloud** [dektrium/yii2-user#674]
I am trying to add Yii2-user to my application which already has a User table. I received the error below. Is there a straightforward way to resolving this without having to create a self-host custom version of your plugin?

Error Info:
Array
(
    [0] => 42S01
    [1] => 1050
    [2] => Table 'user' already exists
)

**Comment by dmeroff** [comment]
There isn't any straightforward way, but you can do following steps:

1) rename your user table (for example old_user)
2) run migrations from yii2-user
3) migrate data from your old_user to user table
