### ISSUE TITLE
Feature request: 2-step authentification process

### ISSUE THREAD

**Issue by WeeSee** [dektrium/yii2-user#675]
Is it planned to integrate an option for 2-step authentification in Yii2-user?
Google, Yahoo and Apple have recently introduced that and maybe
in Yii2 applications there are reasons to simplify authentification, too.
Here are some discussions about the 2-step authentification process:
http://ux.stackexchange.com/questions/78805/why-is-google-using-a-new-2-step-gmail-sign-in-process
What are your thoughts about that?

**Comment by dmeroff** [comment]
This is a cool feature, but I don't think it will be implemented any time soon. But you're very welcome to send a pull-request.
