### ISSUE TITLE
Social signup stopped working after upgrade to 0.9.6 

### ISSUE THREAD

**Issue by dbd5** [dektrium/yii2-user#678]
Hi,

I just found that after authenticating via a social network and returning to the application to supply Email and Username (/user/registration/connect), user data is not saved like before after you click the CONTINUE button, and no errors are thrown. The form reloads and comes back with the data previously entered.

I can confirm that this has worked before and successfully saved user data authenticated by the social network. This seems to have started since after upgrading to 0.9.6.

Please advise on what I am missing. Thank You.

Adam

**Comment by dbd5** [comment]
Resolved

**Comment by nagaokashi** [comment]
@dbd5 
How did you resolve this issue ? plz teach me.
