### ISSUE TITLE
Custom profile class -- Error due to typehints on EventTrait functions

### ISSUE THREAD

**Issue by ckristo** [dektrium/yii2-user#679]
Hi,

I currently try to replace yii2-user's profile model class with a custom one that does not extend `dektrium\user\models\Profile`, and I'm getting a PHP Recoverable Error due to typehints present on the argument of `getProfileEvent(Profile $profile)`.

Does yii2-user support arbitrary profile models? If yes, is there a need to set the typehint here? Otherwise, we could remove it and it should work for arbitary profile instances...

BR,

**Comment by ckristo** [comment]
If supported, I would prefer creating a Profile class derived from ActiveRecord directly, i.a. because overwriting methods for removed functionality would not be needed, e.g.
```php
    public function getAvatarUrl($size = 200)
    {
        throw new Exception('Unsupported method.');
    }
```

**Comment by dmeroff** [comment]
Actually we can remove strict typehinting for Profile model, it isn't necessary. Could you please send a pull-request?

**Comment by ckristo** [comment]
Hi,

Sure, I'll give it a try. Just to get an idea how you'd like to solve this issue: Do you want to a) simply remove type hinting (and rely on the dynamics of PHP such that in case a model gets overwritten and does not provide a needed function, an exception will be thrown) or b) do you want to introduce interfaces (e.g. IModel, IUser, IToken, ...) that require a dev who wants to overwrite a model to implement (at least some basic) functions required for the library to work.

a) would require less work, b) would be the more solid, type-safe way, but is more work and involves some refactoring, including decisions on what functions of which models to require (in my case, do we require to implement `Profile::getAvatarUrl($size)`?)

BR,
Chris

**Comment by dmeroff** [comment]
Sorry for late answer, I don't think we need interfaces here atm, just removing type hinting for profile model will be perfectly fine.
