### ISSUE TITLE
 exception 'yii\base\InvalidConfigException' with message 'User::identityClass must be set.' 

### ISSUE THREAD

**Issue by MagSag** [dektrium/yii2-user#681]
Without    ```
 'user' => [
        'identityClass' => 'app\models\User',
        'enableAutoLogin' => true,
        // You inserted it here
    ],
``` in the web.php configuration file; I am getting error saying: 

> An Error occurred while handling another error: 
> exception 'yii\base\InvalidConfigException' with message 'User::identityClass must be set.' 
Is it ok if I add that in the configuration? but I don't understand what that configuration does !!!

**Comment by dmeroff** [comment]
Did you install Yii2-user using composer?

**Comment by MagSag** [comment]
no but I have added that line it  working  but I am just worried of the effect.

**Comment by dmeroff** [comment]
You should install Yii2-user using composer and it will work (otherwise I cannot help you in that case)
