### ISSUE TITLE
Alert user on account / profile change

### ISSUE THREAD

**Issue by dbd5** [dektrium/yii2-user#682]
Hi Dmitry,

I know that this module now fires EVENT_AFTER_ACCOUNT_UPDATE and EVENT_AFTER_PROFILE_UPDATE, I'd like to take advantage of these events to send a mail notification to the account owner when the account is modified. It seems that this is best practise that even large service providers provide. Please advise how I can achieve this.

Regards,

Adam

**Comment by dmeroff** [comment]
There is a page in documentation, which describes basic usage of events - https://github.com/dektrium/yii2-user/blob/master/docs/using-controller-events.md#using-controllers-events

All you need to do is subscribe to needed event and then do whatever you want (for example send an email to user).

**Comment by dbd5** [comment]
Yea, thats exactly the documentation I studied and yes I can subscribe to the events but I need a way to pass the appropriate parameters to make it meaningful. In this particular case, how do I know the account that was changed and the fields that were changed so I can create a meaningful email message? 

How do I get these parameters?

**Comment by dmeroff** [comment]
When event is triggered, event class is passed to each handler. You can checkout which event class is passed to the event you need.

For example, EVENT_AFTER_PROFILE_UPDATE is triggered with [\dektrium\user\events\UserEvent](https://github.com/dektrium/yii2-user/blob/master/events/UserEvent.php), so you find you which user has changed his account.
