### ISSUE TITLE
Captcha Tabindex not working

### ISSUE THREAD

**Issue by b987123** [dektrium/yii2-user#692]
The tabindex for captcha is not working. 

However if I change
`    public $options = ['class' => 'form-control'];`
tp
`    public $options = ['class' => 'form-control'  ,'tabindex' => '3'];`
in
`/vendor/yiisoft/yii2/captcha/Captcha.php`
the tabindex works. 

Is this an error of Yii2?

**Comment by jmbb** [comment]
```
echo $form->field($model, 'captcha')->widget(Captcha::className(), [
	'options' => ['class' => 'form-control', 'tabindex' => 3],
])->hint('Click on the image to retrieve a new verification code.');
```

Works fine for me.
