### ISSUE TITLE
How to add social auth in widget Login ?

### ISSUE THREAD

**Issue by kireniusdena** [dektrium/yii2-user#694]
How to add social auth into widget Login?

`
use dektrium\user\widgets\Login;
echo Login::widget();

#my config web.php
line component
authClientCollection' => [
            'class' => yii\authclient\Collection::className(),
            'clients' => [
                'facebook' => [
                    'class' => 'dektrium\user\clients\Facebook',
                    'clientId' => 'blablabla',
                    'clientSecret' => 'blablabla',
                ],
                'twitter' => [
                    'class' => 'dektrium\user\clients\Twitter',
                    'consumerKey' => 'CONSUMER_KEY',
                    'consumerSecret' => 'CONSUMER_SECRET',
                ],
                'google' => [
                    'class' => 'dektrium\user\clients\Google',
                    'clientId' => 'CLIENT_ID',
                    'clientSecret' => 'CLIENT_SECRET',
                ],
            ],
        ],
`

thank you..

**Comment by dmeroff** [comment]
Just call it right after your login widget.
