### ISSUE TITLE
Confirmation link displaying : You are not allowed to perform this action.

### ISSUE THREAD

**Issue by MagSag** [dektrium/yii2-user#703]
I tried to register and it sent an email to my account  with the link : https://mydomain.com/index.php/user/confirm/167/F_SOqeMFj6XfbzDHMSjXYR9bFl2RzrNz.php
but when I click the link the access control is saying "You are not allowed to perform this action."
The component configuration is : 
```

   'user' => [
    'identityClass' => 'app\models\User', //<= this
    'enableAutoLogin' => true,
```

My urlManager configuration is : 

```
  'urlManager' => [
'enablePrettyUrl' => true,
'showScriptName' =>true,
],
```

My module configuration is : 
```
 'modules'=>[
        'user'=> [
            'class' => 'dektrium\user\Module',
            'modelMap'=>[
                'Profile'=>'app\models\Profile',
                'RegistrationForm'=>'app\models\RegistrationForm',
                'User'=>'app\models\User',
                ],
                'controllerMap'=>[
                'recovery'=>'app\controllers\RecoveryController',
                'security'=>'app\controllers\SecurityController',
                'registration'=>'app\controllers\RegistrationController',
                'profile'=>'app\controllers\ProfileController',
                'settings'=>'app\controllers\SettingsController',
                ],
            'enableConfirmation'=>true,
            'enableUnconfirmedLogin' => false,
            'emailChangeStrategy' =>'\dektrium\user\Module::STRATEGY_SECURE',
            'confirmWithin' => 21600,
            'cost' => 12,
            'admins' => ['admin']
        ],
```

**Comment by MagSag** [comment]
I extended some controllers(registration,settings,recovery and security) to override some methods in them(register,confirm,resend..). 

I tried to configure the urlManager but the problem now is if I copy and paste the confirmation url in the browser it is redirecting to the default action(as if it is redirecting because it missed the route).

```
rules=>array(
  'user/confirm/<id:\d+>/<token:\w+>' => 'registration/confirm'),
```

**Comment by mmutinda** [comment]
i have installed yii2 user ,the user can sign up but cannot get a confirmation email?how do i solve this
