### ISSUE TITLE
Url route issue on confirm

### ISSUE THREAD

**Issue by zeevy** [dektrium/yii2-user#704]
Module has route rule as 'confirm/<id:\d+>/<code:[A-Za-z0-9_-]+>' => 'registration/confirm',
confirmation code generated is pN=7nHkObLf_EGeWVNe_truWGc7HLwqNP
above regex for the route is invalid as the code contains "=", so it gives 404 error

**Comment by dmeroff** [comment]
Actually the code does not contain `=`. If you check `token` table in your database you'll find out that code is `pN7nHkObLf_EGeWVNe_truWGc7HLwqNP`. This is probably encoding problem with your email client.
