### ISSUE TITLE
Add Yii::$app->name to Mailer sendMessage function

### ISSUE THREAD

**Issue by MagSag** [dektrium/yii2-user#710]
Email received are showing the email address without a name, adding the app name is something interesting.

> Line 230 in  mailer.php

`setFrom([$this->sender=>Yii::$app->name])`

**Comment by dmeroff** [comment]
You can configure it without problem. You can either configure `adminEmail` in your params config:

```php
'adminEmail' => ['no-reply@example.com' => 'Your app'],
```

or configure `mailer` module's property:

```php
'mailer' => [
  'sender' => ['no-reply@example.com' => 'Your app'],
],
```
