### ISSUE TITLE
Authentication via LDAP

### ISSUE THREAD

**Issue by nikhiltri** [dektrium/yii2-user#714]
Hello,

I'm trying to use yii2-user with authentication via LDAP, possibly with the adldap package. What do you think the best way to go about this is? Is it:

- To create a custom authClient?
- Overriding the Password class to add it my own authentication?

How do I add this is without overriding too many classes?

Thanks!
nikhil

**Comment by dmeroff** [comment]
I've never worked with ldap. But I suppose it's better to override login form and implement your authentcation logic there.

**Comment by nikhiltri** [comment]
That's what I ended up doing. In the config:

```php
    'modules' => [
       ...
       'user' => [
         'class' => 'dektrium\user\Module',
         'modelMap' => [
           'LoginForm' => 'common\models\LoginForm',
         ],
       ],
    ],
```

And then in my LoginForm I overwrote the `passwordValidate` rule:

```php
  public function rules() {
    $rules = parent::rules();
    $rules['passwordValidate'] = [
      'password',
      function ($attribute) {
        if (Yii::$app->ldap->authenticate($this->login,$this->password)) {
            ...
        }
      }
    ];
    return $rules;
  }
```

**Comment by philippfrenzel** [comment]
howmto configure ldap?

**Comment by nikhiltri** [comment]
I'm using a separate package to handle the LDAP side of things. Yii::$app->ldap is a wrapper component object of [Adldap2](https://github.com/Adldap2/Adldap2).

**Comment by philippfrenzel** [comment]
ok, thanks and how did you include the ldap class into your app? As you are using Yii::$app->ldap it looks like you are autoloading it?!

**Comment by nikhiltri** [comment]
First I created a wrapper component for the Adldap object:

```php
namespace common\components;

class Adldap2 extends \yii\base\Component
{

  /** @var array Options that will be passed to original Adldap class */
  public $options = [];

  /** @var Adlpad Original class instance */
  private $_instance;

  /** @inheritdoc */
  public function init() {
    parent::init();
    // Create a new connection provider.
    $provider = new \Adldap\Connections\Provider($this->options);

    // Construct new Adldap instance.
    $this->_instance = new \Adldap\Adldap();

    // Add the provider to Adldap.
    $this->_instance->addProvider('default', $provider);
  }

  /** @inheritdoc */
  public function __call($methodName, $methodParams) {
    if ( method_exists($this->_instance, $methodName)) {
      return call_user_func_array([$this->_instance, $methodName], $methodParams);
    }
  }
}
```

Then used that component in my `main-local.php` config:

```php
    'components' => [
        'ldap' => [
          'class' => 'common\components\Adldap2',
          'options' => [
            // See https://github.com/Adldap2/Adldap2/blob/master/docs/configuration.md for config options
          ],
        ],
    ],
```

Now you can call `Yii::$app->ldap->getDefaultProvider()->auth()->attempt(...)` to authenticate, `Yii::$app->ldap->getDefaultProvider()->search()` to search and so forth.

**Comment by philippfrenzel** [comment]
thanks! that's a great implementation! You should make a yii component and post it in yiigist! Best Philipp

**Comment by schmunk42** [comment]
@philippfrenzel How about this? https://github.com/edvler/yii2-adldap-module

**Comment by philippfrenzel** [comment]
I will check this with the LDAP-Servers from our customers - I tried it with the adLDAP direct and always had some small issues - I’ll let you know around wedneday ;)

Cheers!
