### ISSUE TITLE
Login with progressive disclosure pattern

### ISSUE THREAD

**Issue by WeeSee** [dektrium/yii2-user#715]
Google, Yahoo and others started recently to ask for username and password in two steps. each step has to be confirmed with a button, aka ["progressive disclosure"](https://en.wikipedia.org/wiki/Progressive_disclosure).

Why they do that is [discussed a lot](http://ux.stackexchange.com/questions/78805/why-is-google-using-a-new-2-step-gmail-sign-in-process), the main reasons are singe point of focus and better mobile experience.

Is that already on the roadmap of Yii2-user or should we make this a target? 

Such a state-of-the-art feature could be another USP compared to other frameworks and extensions and underpins the excellent Yii2-user approach.

**Comment by dmeroff** [comment]
Sounds interesting. I'll try to add this as an option.

**Comment by thyseus** [comment]
The best answer in the StackExchange link you, @WeeSee, posted is, in my humble opinion:

> Reason "why would google do it" is simple - if you stay signed in, they can track you much better as you go around on the web, and thus make more money. So it might probably benefit Google bottom line more then reasons mentioned in official explanation

I doubt developers building an application with yii2-user has the same intentions.

**Comment by dmeroff** [comment]
After thinking, I've decided that this won't be added to the core. It requires a lot of work, but I'm sure it will be used by a very little percentage of developers. So it shouldn't be part of the core. Maybe this can be added as a tutorial to the documentation though.
