### ISSUE TITLE
Urgent Request: Is it possible to use same email Id for multiple users

### ISSUE THREAD

**Issue by mohdqasim98** [dektrium/yii2-user#719]
We have a system where we manually create new users , and provide credentials to the users.
But there's a strange requirement, that there can multiple users with same email id.
Is it possible ?

**Comment by thiagotalma** [comment]
Quick response: is not possible without extending the class.

From User.php
```PHP
    public function rules()
    {
        return [
             ...
            // email rules
            'emailUnique'   => ['email', 'unique', 'message' => Yii::t('user', 'This email address has already been taken')],
             ...
        ];
    }
```



To allow repeated email you must overwrite the class. Follow the guide's instructions.

**Comment by mohdqasim98** [comment]
Thanks @thiagotalmathiagotalma  for suck a quick reply.
I managed to solve this and will soon post the code to handle this.

**Comment by dmeroff** [comment]
@mohdqasim98 You should also be aware of unique index on `email` column, it may prevent you from inserting same email twice, so you should probably get rid of that index.
