### ISSUE TITLE
Multiple Profile Tables

### ISSUE THREAD

**Issue by zmoddynamics** [dektrium/yii2-user#720]
Hi,

I was wondering if you had any advice on extending your module to allow multiple profile tables, or at the very least, how to change the profile table name. 

My application requires several "user types" ie. Teacher, admin, secretary etc. Each type has different profile fields applicable to them and not the others so a single profile table does not work here. The RBAC role works fine as each user can be assigned a different role but just having one global profile table doesn't seem like a good approach. 

If not possible, if I could change the profile table name, (without having to override 100's of files) that could be an option as well since I could define separate user extension for each application. 

Do you have any advice ?

**Comment by dmeroff** [comment]
You can create different profile tables for each role (teacher, admin, etc) and completely get rid of `profile` table. Then you will need to create different actions to edit profiles.
