### ISSUE TITLE
Repeated xmlns in html.php view layout

### ISSUE THREAD

**Issue by Ziggizag** [dektrium/yii2-user#724]
Hi,

dektrium\views\mail\layouts\html.php

has duplicated xmlns declaration:

`<html xmlns="http://www.w3.org/1999/xhtml" xmlns="http://www.w3.org/1999/xhtml" style="font-family: 'Helvetica Neue', 'Helvetica', Helvetica, Arial, sans-serif; font-size: 100%; line-height: 1.6; margin: 0; padding: 0;">`

This does not parse through loadHTML of a DOMDocument while sent through PHPMailer.

**Comment by dmeroff** [comment]
Thank you, fixed now!
