### ISSUE TITLE
Security: More common error messages

### ISSUE THREAD

**Issue by jkmssoft** [dektrium/yii2-user#725]
I think that there are too many detailed error messages.

What about removing some of the messages and/or replacing some of them by more common ones?

**Comment by dmeroff** [comment]
I don't understand what are you talking about. Could you please provide examples?

**Comment by jkmssoft** [comment]
For example in models/RecoveryForm.php
`````php
            'emailExist' => [
                'email',
                'exist',
                'targetClass' => $this->module->modelMap['User'],
                'message' => Yii::t('user', 'There is no user with this email address'),
            ],
`````

I would prefer that the user doesn't see a error like this.
In case of the RecoveryForm I think for all inputs the user should see a message like
`If your email address exists, an email has been sent with instructions for resetting your password`

**Comment by dmeroff** [comment]
Yes, that's valid point. Could you please provide any other examples?

**Comment by jkmssoft** [comment]
See this branch [formSecurityRecoveryResend](https://github.com/jkmssoft/yii2-user/tree/formSecurityRecoveryResend).

Some tests then need also to be modified.

**Comment by dmeroff** [comment]
Done.
