### ISSUE TITLE
Backend yii2-user

### ISSUE THREAD

**Issue by AlimovRoostam** [dektrium/yii2-user#728]
Подскажите как реализовать невозможность войти в бекэнд не залогиневшись?

**Comment by thiagotalma** [comment]
This is an international collaborative project (like most open source projects).

Please use the [http://translate.google.com](http://translate.google.com) and rewrite the issue in English.

**Comment by AlimovRoostam** [comment]
I use advansed template. How do I disable enter not authorized in the backend

**Comment by dmeroff** [comment]
@AlimovRoostam you should use `yii\web\AccessControl` filter.
