### ISSUE TITLE
Auto Login after Registration

### ISSUE THREAD

**Issue by kevinkt** [dektrium/yii2-user#730]
I want my user to be logged in after registration. I tried the solution here: https://github.com/dektrium/yii2-user/issues/685

But that gives me a 500 error.
--
The localhost page isn’t working

localhost is currently unable to handle this request.
HTTP ERROR 500
--

Also here's the code I'm using. Pretty much a copy & paste from the other solution:

		'user' => [
		            'class' => 'dektrium\user\Module',
		            'controllerMap' => [
		                'registration' => [
		                    'class' => \dektrium\user\controllers\RegistrationController::className(),
		                    'on ' . \dektrium\user\controllers\RegistrationController::EVENT_AFTER_REGISTER => function ($e) {
		                        $user = \dektrium\user\models\User::findOne(['username'=>$e->form->username, 'email'=>$e->form->email]);

		                        if ($user) {
		                            Yii::$app->user->switchIdentity($user);
		                        }
		                        \Yii::$app->response->redirect(\Yii::$app->user->returnUrl);
		                    },
		                ],
		            ],

Any thoughts on what could be going wrong?

**Comment by thiagotalma** [comment]
Please, post the complete error message.

**Comment by kevinkt** [comment]
The localhost page isn’t working

localhost is currently unable to handle this request.
HTTP ERROR 500

**Comment by thiagotalma** [comment]
Please, post the complete error message, with the stack trace.
Set YII_DEBUG to true

**Comment by kevinkt** [comment]
There is no error message, just the localhost page 500 error shows. I have yii debug set as true.

**Comment by kevinkt** [comment]
I looked at PHP error log and saw this: [09-Jul-2016 10:20:05 Europe/Berlin] PHP Parse error: syntax error, unexpected ';', expecting ']' in /Users/kevin/documents/hello/config/web.php on line 152

**Comment by thiagotalma** [comment]
> syntax error, unexpected ';', expecting ']' in /Users/kevin/documents/hello/config/web.php on line 152

You forget an opened array. Close them and be happy!
