### ISSUE TITLE
how to override the urls for each opeartion in yii2-user

### ISSUE THREAD

**Issue by shyandsy** [dektrium/yii2-user#732]
how to override the urls for each opeartion in yii2-user?

for example:
     register operation /user/registration/register 
     I wanna change it to /customer/register

**Comment by jkmssoft** [comment]
Example (for use with pretty urls):
`````php
$config = [
...
    'modules' => [
        'user' => [
...
            'urlPrefix' => 'customer',
            'urlRules' => [
                '<action:(register|resend)>' => 'registration/<action>',
            ],
...
        ],
...
    ],
....
`````

**Comment by dmeroff** [comment]
@jkmssoft is correct. You can override routes by using url manager.
