### ISSUE TITLE
Contributing: Which coding standard?

### ISSUE THREAD

**Issue by jkmssoft** [dektrium/yii2-user#733]
Which coding standard should be used to write valid code?
Please add to CONTRIBUTING.md.

[PSR-2](http://www.php-fig.org/psr/psr-2/) or [Yii2 coding standard](https://github.com/yiisoft/yii2-coding-standards)?

Example usage of [Yii2 coding standard](https://github.com/yiisoft/yii2-coding-standards):
`phpcs --extensions=php --standard=~/yii2-coding-standards/Yii2 .`

**Comment by dmeroff** [comment]
I've updated contributing guide. PSR-2 should be used.
