### ISSUE TITLE
can not login

### ISSUE THREAD

**Issue by janitov** [dektrium/yii2-user#734]
i have last version of yii2 advanced and yii2-user with yii2-rbac , but i cannot login using username that i had created. the problem is the same pointed in this link https://github.com/dektrium/yii2-user/issues/215, and I have removed the user component from your config's components section. but but login still does not work.

**Comment by dmeroff** [comment]
Please use [our support forum](https://dektrium.com) for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only.
