### ISSUE TITLE
After login event issue

### ISSUE THREAD

**Issue by saranvarma** [dektrium/yii2-user#738]
MY main.php in common/config looks like this

<?php
return [
    'vendorPath' => dirname(dirname(__DIR__)) . '/vendor',
    'modules' => [
        'user' => [
            'class' => 'dektrium\user\Module',           
        ],
    ],
    'components' => [
        
        'cache' => [
            'class' => 'yii\caching\FileCache',
        ],
    ],
];

i want to redirect to site/search page after login and set some data in session by getting it from another table with userid . but when i use after login event ,  its not working . please let me know some solution

**Comment by soap** [comment]
You did not provide any information, how you implement it in your code? Please see how to use controller event in document section.

**Comment by dmeroff** [comment]
Please use [our support forum](https://dektrium.com) for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only.
