### ISSUE TITLE
Support for SQL Server

### ISSUE THREAD

**Issue by hoaaah** [dektrium/yii2-user#739]
I am using SQL Server as my DBMS. When I tried to migrate, I got error
> Exception 'RuntimeException' with message 'Your database is not supported!'
And I found that yii2-user only support MySQL and PgSQL 
[migration.php](https://github.com/dektrium/yii2-user/blob/master/migrations/Migration.php)
`    public function init()
    {
        parent::init();
        switch (Yii::$app->db->driverName) {
            case 'mysql':
                $this->tableOptions = 'CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE=InnoDB';
                break;
            case 'pgsql':
                $this->tableOptions = null;
                break;
            default:
                throw new \RuntimeException('Your database is not supported!');
        }
    }`
I hope I didn't misunderstood the problem.

**Comment by dmeroff** [comment]
Yes, you understood corectly. Yii2-user does not support SQL server.
Actually, it may work well with SQL server, but I didn't test it. You can try using it with SQL server (you can update migration code and check if it works well), then you can send a pull-request if everything is ok.

**Comment by hoaaah** [comment]
Already tried a simple modification to migration.php so I add this line
`//migration.php
    public function init()
    {
        parent::init();

        switch (Yii::$app->db->driverName) {
            case 'mysql':
                $this->tableOptions = 'CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE=InnoDB';
                break;
            case 'pgsql':
                $this->tableOptions = null;
                break;
            case 'sqlsrv':
                $this->tableOptions = null;
                break;				
            default:
                throw new \RuntimeException('Your database is not supported!');
        }
    }`
But after that migration get some error. SQL Server didn't recognize "RESTRICT" as UPDATE/DELETE  action. In SQL Server restrict are applied by default. So I uncommented the "RESTRICT from migration. But got this error again, still not sure what this mean,
`    > alter column username in table {{%user}} to string(255) NOT NULL ...Exception 'yii\db\Exception' with message 'SQLSTATE[42000]: [Microsoft][ODBC Driver 11 for SQL Server][SQL Server]The
index 'user_unique_username' is dependent on column 'username'.
The SQL being executed was: ALTER TABLE [user] ALTER COLUMN [username] nvarchar(255) NOT NULL'`
I'll keep you posted. I'll send pull-request after migration success without error.
Thanks @dmeroff

**Comment by dmeroff** [comment]
`The index 'user_unique_username' is dependent on column 'username'`

I'm not sure, but I think this error means that you cannot alter column that is used within index.
