### ISSUE TITLE
Support for Multi Factor Authentication

### ISSUE THREAD

**Issue by zmoddynamics** [dektrium/yii2-user#741]
### What is the expected result?
Can we add feature to support multi factor authentication ? Via Google authenticator app ?

### Additional info

| Q                 | A
| ----------------- | ---
| Yii2 version      |
| Yii2-user version |
| PHP version       |

**Comment by dmeroff** [comment]
I don't think this will be added in the near future. However you're very welcome to send pull-request.
Next time use [our support forum](https://dektrium.com) to create feature requests. We reserve the issues tracker for issues only.
