### ISSUE TITLE
Redirect after login

### ISSUE THREAD

**Issue by diego-betto** [dektrium/yii2-user#743]
Trying to redirect users to products page after login. Not working ('controllerMap' seems ignored, 'enableXXXXX' are working)

This is the configuration. Any clue?

```
...
'modules' => [
        'user' => [
            'class' => 'dektrium\user\Module',
            'admins' => ['aaaa','bbb'],
            'enableRegistration' => false,
            'enableConfirmation' => true,
            'enablePasswordRecovery' => true,
            'controllerMap' => [
                'login' => [
                    'class' => \dektrium\user\controllers\SecurityController::className(),
                    'on ' . \dektrium\user\controllers\SecurityController::EVENT_AFTER_LOGIN => function ($e) {
                        \Yii::$app->response->redirect('product');
                    },
                ],
            ],
        ],
...
```

**Comment by dmeroff** [comment]
Please use [our support forum](https://dektrium.com) for questions/help, where we will be able to help you. We reserve the issues tracker for issues only.

**Comment by re8us** [comment]
can't register on forum via github 
https://dektrium.com/?error=redirect_uri_mismatch&error_description=**The+redirect_uri+MUST+match+the+registered+callback+URL+for+this+application**.&error_uri=https%3A%2F%2Fdeveloper.github.com%2Fv3%2Foauth%2F%23redirect-uri-mismatch&state=8IZATJcBqabaa37OqSubOHqj1OU8u53o

**Comment by dmeroff** [comment]
@re8us should be fixed now.

**Comment by muet84** [comment]
Hey, how you solved your redirect problem?? I want to do the same and tried with controller map and not able to redirect after login.

**Comment by Negossia** [comment]
It doesn't work ((

**Comment by Martin-Hogge** [comment]
I know this is closed but I want to achieve the same and the forum seems down (ERR_CONNECTION_TIMED_OUT). I don't know where to ask so I ask it here: is their a solution to redirect after login? Thank's.

**Comment by diego-betto** [comment]
Temp Workaround: solved setting products page as home page and accessible only when authenticated.

**Comment by asilvestre87** [comment]
@diego-betto try this:
'security' => [
                    'class' => \dektrium\user\controllers\SecurityController::className(),
                    'on ' . \dektrium\user\controllers\SecurityController::EVENT_AFTER_LOGIN => function ($e) {
                        Yii::$app->response->redirect(array('/product'))->send();
                        Yii::$app->end();
                    },
                ],

**Comment by gl00m** [comment]
@asilvestre87 your answer was not readable for me)) found answer myself))
should add to controllerMap **"security"** but NOT **"login"** field
