### ISSUE TITLE
Error during password recovery

### ISSUE THREAD

**Issue by sergalius** [dektrium/yii2-user#745]
Hi. 
If I want to restore  password.  http://site.local/admin/user/forgot Enter email to form.
Go to email and click link http://site.local/admin/user/recover/1/2YHM5JApp67QaBjyoNjeb4WFRayXaJBr
Enter new pasword showed messsage success. All ok.
But if again click link http://site.local/admin/user/recover/1/2YHM5JApp67QaBjyoNjeb4WFRayXaJBr
will be error
![screenshot](https://cloud.githubusercontent.com/assets/16141970/17278037/ce062b34-575a-11e6-9030-f5b3f40c90ae.png)

**Comment by dmeroff** [comment]
This has been fixed in master branch. You should wait until next release or use unstable version from master branch.

P.S. Could you please follow issue template next time? It helps a lot. Thank you.
