### ISSUE TITLE
Unable to find 'app\models\User' in file: C:\xampp\htdocs\app/models/User.php. Namespace missing?

### ISSUE THREAD

**Issue by akpanowo** [dektrium/yii2-user#751]
i recently implemented yii2 user in my app. i am trying to override the model User model and i get the error:
Unable to find 'app\models\User' in file: C:\xampp\htdocs\app/models/User.php. Namespace missing?

My custom model code is:

```
<?
namespace app\models;
use dektrium\user\models\User as BaseUser;
class User extends BaseUser
{
}
?>
```

in the web config file i have it set up as:

```
'modules' => [
		'user' => [
				'class' => 'dektrium\user\Module',
				'enableUnconfirmedLogin' => true,
				'confirmWithin' => 21600,
				'cost' => 12,
				'modelMap' => [
					'User' => 'app\models\User',
					'Profile' => 'app\models\Profile',
				],
				'admins' => ['admin']
			],
	],
```

Wht am i doing wrong please?

**Comment by dmeroff** [comment]
Please use [our support forum](https://dektrium.com) for questions/help, where we will be able to help you. We reserve the issues tracker for issues only.
