### ISSUE TITLE
Call to undefined method setencryptions

### ISSUE THREAD

**Issue by sciefylab** [dektrium/yii2-user#756]
Hi guys,

when index.php?r=user%2Fregistration%2Fregister

it says:
PHP User Error – yii\base\ErrorException

Call to undefined method setencryptions

whats mean?

| Q |
| --- |
| Yii2 2.0.9 |
| Yii2-user 0.9.6.0 |
| PHP 5.6.8 |

**Comment by dmeroff** [comment]
Yii2-user does not use any methods named `setencryptions`. If problem still exists, then provide more information and reopen the issue.
