### ISSUE TITLE
Social Registration and AFTER_CONFIRM event

### ISSUE THREAD

**Issue by zeevy** [dektrium/yii2-user#761]
When registered via social accounts user account is auto confirmed but not AFTER_CONFIRM event is fired
### What steps will reproduce the problem?

register via any supported social account, user account is marked as confirmed in db, but no AFTER_CONFIRM  event fired
### What is the expected result?

AFTER_CONFIRM  event should get fired for social registrations
### What do you get instead?

No AFTER_CONFIRM  event fired
### Additional info

| Q | A |
| --- | --- |
| Yii2 version | 2.0.9 |
| Yii2-user version | 0.9.9 |
| PHP version | 5.6.19 |

**Comment by CyanoFresh** [comment]
Need this feature, too. I event think it's a bug
