### ISSUE TITLE
/user/admin/create fails on windows but works on linux

### ISSUE THREAD

**Issue by philippfrenzel** [dektrium/yii2-user#764]
### What steps will reproduce the problem?

I have a docker machine with ubuntu linux running, where the /user/admin/create works without any issues, if I move it to the production system which is a native xampp installation on win2012 server it's not creating users anymore. Sadly I don't get any error message
### What is the expected result?

User get's created in both systems
### What do you get instead?

User only gets created in linux environment
### Additional info

| Q | A |
| --- | --- |
| Yii2 version | 2.0.9 |
| Yii2-user version | 0.9.8 |
| PHP version | 5.6.0 under windows and 5.6.23 under linux |

**Comment by philippfrenzel** [comment]
Update: Looks like the user get's created, but within the profile creation an error occures and then the total create get's roled back? :/ how can I debug this...?

**Comment by mugubrainpan** [comment]
+1  

I'm seeing the same behavior with 0.9.9:  I can update existing users, but cannot create any new ones.

The DB table is incrementing, but no new user record is created.  My deduction is that new rows are getting deleted immediately after creation.  

No error is displayed on the site.  No Apache errors are logged.  

Interestingly, on a different server running somewhat different versions (see below), the exact same Yii code and DB structure works perfectly.

**BROKEN:**
Yii2 version: 2.0.9
Yii2-user version: 0.9.9
PHP Version: 5.6.24
Server OS: Ubuntu 12.04.5 LTS

**WORKING:**
Yii2 version: 2.0.8
Yii2-user version: 0.9.6
PHP Version: 7.0.8-0ubuntu0.16.04.2
Server OS: Ubuntu 16.04 LTS

**Comment by mugubrainpan** [comment]
Update:  In my case, **downgrading** to Yii2-user 0.9.6 restored my ability to create new users.

**Comment by philippfrenzel** [comment]
Ok - so did you check what changed from 0.9.6 to latest version? I don't understand why it broke :(
Thanks for sharing your solution!

**Comment by mugubrainpan** [comment]
No, I've not run a diff or otherwise tried to isolate the root cause since reverting.

**Comment by philippfrenzel** [comment]
ok, thanks! I will ask one of our team members to debug it ;)

**Comment by kvush** [comment]
I guess you should to accept this migration -> m151218_234654_add_timezone_to_profile. It is 
necessary for versions older than 0.9.6. If you had updated your "profile" table manually, please check that name of new field was exactly tha same as timezone and type varchar 40. No camel case in name!

**Comment by germanliu** [comment]
I have the same issue with 0.9.8, downgrading worked for me, I'm on a Mac and did a clean install

**Comment by nduytu87** [comment]
I also have this issue and I found that I forgot to config stmp. When user was created, but the email wasn't send. So the record has created which is deleted.

**Comment by philippfrenzel** [comment]
stmp? you mean smtp? and shouldn't it take the config from mailer? as I always have "useFileTransfer" = true while developing?!

**Comment by nduytu87** [comment]
smtp. i typed incorrectly. 

'host' => $myconfig['smtp_host'],
                'username' => $myconfig['smtp_username'],
                'password' => $myconfig['smtp_password'],

**Comment by dmeroff** [comment]
I cannot reproduce this issue. If you are still stumble upon it, please reopen it and attach logs, errors or something, so I can dig into it ;)
