### ISSUE TITLE
authTimeout feature

### ISSUE THREAD

**Issue by maccine** [dektrium/yii2-user#766]
is there a way to implement an authtimeout feature similar with the original user from yii2?
i need to force logout users when idle for 5 minutes, thank you!

**Comment by OsoTranquilo** [comment]
I also need to control the time that the application uses to perform the logout, and did not find the way.
If this is possible? appreciate some indication, or to include it in an update.
Thank you.

**Comment by dmeroff** [comment]
There is no such feature at the moment, and I don't think it will be ever added.
