### ISSUE TITLE
No welcome message sent when admin creates new user, disregarding config settings

### ISSUE THREAD

**Issue by mugubrainpan** [dektrium/yii2-user#768]
When an admin creates a new user, no welcome email is sent no matter what settings are in the config.  

In my case, self-registration is disabled and **all** accounts will be created by admins -- so having automatic welcome emails will be critical. This is especially important when passwords are auto-generated (which I expect will be the majority of the time).  
- I do have mailer transport configured and validated as working.  Password recovery emails are sent successfully.  Also, the site's contact form successfully sends email with no difficulty.
- Explicitly setting `enableConfirmation` to `true` in the config has no impact of any kind. This contradicts what the documentation says (even when `enableRegistration` is set to `false`, as in my case).
- Explicitly setting `enableGeneratingPassword` to `true` in the config also has zero impact -- that is:  a password does get generated, but no email is sent. This contradicts what the documentation says.

Please note that I am currently using yii2-user **v0.9.6**.  (I had to downgrade from v0.9.9 because admins were not able to create new users at all.)  I have not tried v0.9.7.

Thanks very much for your time.

**Comment by rrhyne** [comment]
I had the same issue, problem was with my the yii Mailer config, not this module.

**Comment by dmeroff** [comment]
Can not reproduce on the latest version (0.9.9). If you still have this problem, please reopen the issue.
