### ISSUE TITLE
RecoveryController->actionReset($id, $code) 'TypeError' Exception if token not found

### ISSUE THREAD

**Issue by corpsepk** [dektrium/yii2-user#769]
### What steps will reproduce the problem?

go to `example.com/user/recover/1/{wrong-token-code}`
### What is the expected result?

Expecting to get message 

> Recovery link is invalid or expired. Please try requesting a new one.
### What do you get instead?

Exception `TypeError`
### Additional info

Bug is here https://github.com/dektrium/yii2-user/blob/master/controllers/RecoveryController.php#L150

``` php
// can return `null`
$this->finder->findToken([...])->one();

// but on next line $token must be an instance of `dektrium\user\models\Token`
$this->getResetPasswordEvent($token);
```

**Comment by dmeroff** [comment]
This issue has been fixed in version 0.9.7 or later.
