### ISSUE TITLE
Profile - strcmp() expects parameter 2 to be string, object given

### ISSUE THREAD

**Issue by kvush** [dektrium/yii2-user#771]
After update to version 0.9.9 from version 0.9.6
I get error if try to open /user/settings/profile

strcmp() expects parameter 2 to be string, object given
 in C:\OpenServer\domains\myApp\vendor\yiisoft\yii2\helpers\BaseHtml.php at line 1712 
### Additional info

| Q | A |
| --- | --- |
| Yii2 version | 2.0.9 |
| Yii2-user version | 0.9.9 |
| PHP version | 5.6 |

**Comment by kvush** [comment]
I am sorry, i was stupid. I forget make migration/up. After when i update profile table the error was gone.
Please close this issue.

**Comment by philippfrenzel** [comment]
can this be the issue for #764 ??
