### ISSUE TITLE
Feature request: login as an other user

### ISSUE THREAD

**Issue by skeeran** [dektrium/yii2-user#772]
hi,

i am was thinking of new feature.. maybe one of u have already implemented.
As admin i want be possible to simulate an user: that means i can login in the backend of a user and see what they also seeing without knowing his password, so i can help them if they have question or problem.

Any idea how this one is possible ? Would be a nice feature

**Comment by thyseus** [comment]
+1 for having this feature !

**Comment by skeeran** [comment]
found that yii has a function for this:

Yii::$app->user->switchIdentity($user, $duration);

**Comment by thyseus** [comment]
I have implemented this feature into the backend: 

https://github.com/dektrium/yii2-user/pull/791

**Comment by skeeran** [comment]
cool Thank you buddy

**Comment by dmeroff** [comment]
PR from @thyseus has been merged. Sorry for the delay with the answer.

**Comment by thyseus** [comment]
Nice. Thanks for merging and welcome back. I thought about this feature, and we need to protect the actionSwitch() method for unauthorized access (e.g. by url). Will do this overmorrow when i am back in office.
