### ISSUE TITLE
Feature Request: failed_login_attempts 

### ISSUE THREAD

**Issue by thyseus** [dektrium/yii2-user#773]
Hey,

i want to implement the following feature: 

if a user enters a wrong password, the count of wrong attempts is saved into the database. Once the user logs in correctly, a message gets displayed (via flash) saying: "Warning: X failed login attempts since last login".

This is already implemented in yii-user-management for yii1: 
https://github.com/thyseus/yii-user-management/blob/80daa94fb9a6bd118b759eea5a5e3a078c4d4372/user/controllers/YumAuthController.php#L158

https://github.com/thyseus/yii-user-management/blob/master/user/controllers/YumAuthController.php#L188

Also, i would like to add a column 'last_login' next to 'created_at' and 'updated_at'.
Would it be OK to change the column type from int(11) to DATETIME ?

@dmeroff : Do you want me to implement this feature like done in yii-user-management?

Thanks !

**Comment by thyseus** [comment]
Update: the DATETIME issue has already been discussed and rejected: https://github.com/dektrium/yii2-user/issues/372 . I´m Still sad about that - DATETIME is so much better readable for humans than an timestamp.

**Comment by thyseus** [comment]
See https://github.com/dektrium/yii2-user/pull/774 which is a proposal to implement the last_login part of this issue.

**Comment by thyseus** [comment]
@jkmssoft: This is exactly what i supposed! Thanks for this work.
@dmeroff: Your project is breathing... :)

**Comment by smilemd** [comment]
+1, would be nice to have that feature

**Comment by dmeroff** [comment]
Closed in favor of #829
