### ISSUE TITLE
User registration should rethrow exceptions.

### ISSUE THREAD

**Issue by SamMousa** [dektrium/yii2-user#777]
### What steps will reproduce the problem?

Try user registration with misconfigured mailer.
### What is the expected result?

User registration visibly fails.
### What do you get instead?

The form gets reloaded without any feedback.
### Additional info

Because the `register()` function in the user model catches all exceptions (to rollback the transaction), a message is never shown. In my opinion the only validation errors should cause a refresh of the form (which would then show the validation error message). Other errors, like exceptions from any dependency like the db or mailer components should throw exceptions.

A simple fix would be to throw the caught exception instead of returning false, here:
https://github.com/dektrium/yii2-user/blob/master/models/User.php#L321

| Q | A |
| --- | --- |
| Yii2 version |  |
| Yii2-user version |  |
| PHP version |  |

**Comment by saepulm** [comment]
I have followed the tutorial from : 

https://code.tutsplus.com/tutorials/how-to-program-with-yii2-integrating-user-registration--cms-22974 

on setting registration and mailer along, I've retrace the tutorial but remain the same, for the first I can send email but for the next application that I created does not work even though I've been following an application process before I have made, but still does not work

**Comment by dmeroff** [comment]
Done. Sorry for such a delay with the answer.
Release 0.9.10 with this fix will be ready in a few days.
