### ISSUE TITLE
Migrations don't work with DB handle other than "db"

### ISSUE THREAD

**Issue by hiasl** [dektrium/yii2-user#778]
### What steps will reproduce the problem?

If your console.php does not have a database connection called "db" but with a different name, migrations will fail, because they have "db" hardcoded.

this is my db:

```
        'helperdb' => [
            'dsn' => 'mysql:host=192.168.33.1;dbname=helperdb',
        ],

```
### What is the expected result?

migrations should work when you call them like this from the shell:
`./yii migrate --db=helperdb --migrationPath=@vendor/dektrium/yii2-user/migrations`
### What do you get instead?

this exception:
`Exception 'yii\base\InvalidConfigException' with message 'Unknown component ID: db'`
caused by this line
`switch (Yii::$app->db->driverName) {`
in yii2-user/migrations/Migration.php

there are more Migrations having the same problem:
e.g. yii2-user/migrations/m141222_110026_update_ip_field.php
### Additional info

| Q | A |
| --- | --- |
| Yii2 version | 2.09 |
| Yii2-user version | 0.9 |
| PHP version | 5.5 |

**Comment by dmeroff** [comment]
Done. Sorry for such a delay with the answer.
Release 0.9.10 with this fix will be ready in a few days.

**Comment by hiasl** [comment]
same problem btw. for the console commands. they also do not know the option --db=something, like this:
`./yii --db=helperdb user/create ...`
