### ISSUE TITLE
Facebook registration not generate automatically a username

### ISSUE THREAD

**Issue by invaderhd** [dektrium/yii2-user#781]
I search and find a method on user model called "generateUsername", I think we should have an option to automatically generate a username when a user use a social network to sign up.

There are any way to do that?

**Comment by vladyslavstartsev** [comment]
Not all of them. For example, if you login with vkontakte you can get users username

**Comment by dmeroff** [comment]
I don't think this will be added in the near future.
However you're very welcome to send a pull-request.
