### ISSUE TITLE
Features Suggestion: User to confirm email after somedays of use.

### ISSUE THREAD

**Issue by MagSag** [dektrium/yii2-user#784]
User registers and access the application without confirming is email address. After somedays (e.g:30days) ask the user to confirm the email address before accessing the application.

When registering a flash message should come telling the a confirmation message has been sent and giving him option to choose if he wants to confirm later and if so, he should not be obliged to confirm before a defines days(e.g:30 days). When the days are expired, Oblige him to confirm.

**Comment by dmeroff** [comment]
I don't think this feature is needed to be presented in module out of the box.
