### ISSUE TITLE
Failing to update from version 0.9.5 to the latest via composer

### ISSUE THREAD

**Issue by MagSag** [dektrium/yii2-user#785]
### What steps will reproduce the problem?

composer update dektrium/yii2-user:0.9.*@dev
### What is the expected result?

Update the from 0.9.5 to the latest stable 0.9.*@dev
### What do you get instead?

Package "dektrium/yii2-user:0.9.*@dev" listed for update is not installed. Ignoring.
Loading composer repositories with package information
Updating dependencies (including require-dev)
Nothing to install or update
Package facebook/php-sdk-v4 is abandoned, you should avoid using it. Use facebook/graph-sdk instead.
Generating autoload files
### Additional info

| Q | A |
| --- | --- |
| Yii2 2.7 |  |
| Yii2-user 0.9.5 |  |
| PHP 5.6 |  |

**Comment by dmeroff** [comment]
You should use `composer require` instead of `composer update`
