### ISSUE TITLE
Exception in signin action

### ISSUE THREAD

**Issue by naeemtawwos** [dektrium/yii2-user#792]
exception 'yii\base\InvalidRouteException' with message 'Unable to resolve the request "user/login".' in C:\xampp\htdocs\vendor\yiisoft\yii2\base\Module.php:460
Stack trace:
#0 C:\xampp\htdocs\vendor\yiisoft\yii2\web\Application.php(87): yii\base\Module->runAction('user/login', Array)
#1 C:\xampp\htdocs\vendor\yiisoft\yii2\base\Application.php(375): yii\web\Application->handleRequest(Object(yii\web\Request))
#2 C:\xampp\htdocs\web\index.php(12): yii\base\Application->run()
#3 {main}

Next exception 'yii\web\NotFoundHttpException' with message 'Page not found.' in C:\xampp\htdocs\vendor\yiisoft\yii2\web\Application.php:99
Stack trace:
#0 C:\xampp\htdocs\vendor\yiisoft\yii2\base\Application.php(375): yii\web\Application->handleRequest(Object(yii\web\Request))
#1 C:\xampp\htdocs\web\index.php(12): yii\base\Application->run()
#2 {main}

**Comment by dmeroff** [comment]
You probably did not install Yii2-user correctly. Please check all the steps again.
