### ISSUE TITLE
Registration email does not receiving

### ISSUE THREAD

**Issue by viskas** [dektrium/yii2-user#798]
When trying to register a new user and click on register button. I saw a message that email was sended. But my email box is still empty even spam folder.

I expect message with confirmation link.

Instead that email not receided.
### Additional info
I install Yii2 with composer command "composer create-project --prefer-dist yiisoft/yii2-app-basic basic".
Yii2 user module i install with composer command "composer require "dektrium/yii2-user:0.9.*@dev".

**Comment by dmeroff** [comment]
This is probably because you have wrong configuration for your mailer component.
