### ISSUE TITLE
GhostHTML:a

### ISSUE THREAD

**Issue by TheMetalMonkey** [dektrium/yii2-user#802]
### What steps will reproduce the problem?
use ghosthtml:a('Delete', [delete]) doesn't hide the link when permission is denied.
Just replace the Html:a links on the standard gii pages.

### What is the expected result?
Hides the permission

### What do you get instead?
Link shows without filtering.

### Additional info
Something to do with how yii unifyRoute is stripping down the url - no controller id is passed to Route::isRouteAllowed.

I have a workaround - although I'm not sure how robust it is if other type of url are passed into the function. I put this into GhostHtml although it might be more sensible to modify the User:canRoute function.

```
public static function a($text, $url = null, $options = [])
	{
		if ( in_array($url, [null, '', '#']) )
		{
			return parent::a($text, $url, $options);
		}
               // addition
		if(is_array($url) && strpos($url[0], '/')===false)
		{
			$url[0] = Yii::$app->controller->id . '/' . $url[0];
		}
		return User::canRoute($url) ? parent::a($text, $url, $options) : '';
	}
```

| Q                 | A
| ----------------- | ---
| Yii2 version      | 2.0.10
| Yii2-user version | 1.0.13
| PHP version       | 5.5.38

**Comment by dmeroff** [comment]
I think you created issue in a wrong repository :smile:
