### ISSUE TITLE
How to replace route "../user/<id>"?

### ISSUE THREAD

**Issue by ankkk** [dektrium/yii2-user#803]
Hi, how to replace the default route with the **../user/<id>** on **../user/<username>** ?

**Comment by Thoulah** [comment]
You will have to extend `ProfileController`

```
	public function actionShow($username) {
		$user = $this->finder->findUserByUsername($username);
		if (!$user)
			throw new NotFoundHttpException('Profile not found.');

		$profile = $this->finder->findProfileById($user->id);
		if (!$profile)
			throw new NotFoundHttpException('Profile not found.');

		return $this->render('show', [
			'profile' => $profile,
		]);
	}
```

**Comment by Thoulah** [comment]
Perhaps this should be in core `actionShowById` and `actionShowByUsername` :)

**Comment by ankkk** [comment]
@Thoulah 
I extend `ProfileController`
`
use dektrium\user\controllers\ProfileController as Profile;
use yii\web\NotFoundHttpException;

class ProfileController extends Profile
{

    /**
     * Shows user's profile.
     *
     * @param $username
     *
     * @return \yii\web\Response
     * @throws \yii\web\NotFoundHttpException
     */
    public function actionShow($username) {
        $user = $this->finder->findUserByUsername($username);
        if (!$user)
            throw new NotFoundHttpException('User not found.');

        return parent::actionShow($user->id);
    }
}
`
Also added a line in `web.php`
`
'controllerMap' => [
                'profile' => 'app\controllers\ProfileController',
}
`
But i still can't get the link:
**site.com/user/<username>**
What is my problem?

**Comment by Thoulah** [comment]
Possibly urlRules missing?

```
	'modules' => [
		'user' => [
			'class' => 'dektrium\user\Module',
			'controllerMap' => [
				'profile' => 'app\controllers\user\ProfileController',
			],
			'urlRules' => [
				'profile/<username:\w+>'					=> 'profile/show',
				'<action:(login|logout)>'					=> 'security/<action>',
				'<action:(register|resend)>'				=> 'registration/<action>',
				'confirm/<id:\d+>/<code:[A-Za-z0-9_-]+>'	=> 'registration/confirm',
				'forgot'									=> 'recovery/request',
				'recover/<id:\d+>/<code:[A-Za-z0-9_-]+>'	=> 'recovery/reset',
				'settings/<action:\w+>'						=> 'settings/<action>',
			],
		],
	],
```

I'm not sure if you need to (re)define all rules. You can try.

@dektrium Please update your SSL certificate.

**Comment by dmeroff** [comment]
Please note, that the GitHub Issue Tracker is for bug reports and feature requests only.

We are happy to help you on the [support forum](https://dektrium.com). Please use it to discuss the problem.

If the result of the discussion turns out that there really is a bug in the extension, feel free to
come back and provide information on how to reproduce the issue. This issue will be closed for now.
