### ISSUE TITLE
Feature request: OTP

### ISSUE THREAD

**Issue by etopian** [dektrium/yii2-user#812]
This project supports Google Authenticator and e-mail for OTP. Is it possible to add that to this project, pretty please?

https://github.com/nineinchnick/yii-usr

Thanks.

**Comment by philippfrenzel** [comment]
Have you seen:

https://github.com/dektrium/yii2-user/blob/master/docs/social-auth.md

**Comment by etopian** [comment]
@philippfrenzel i have. not the same thing. i want to add a bit more security to logins to prevent stole password problems. this does that sort of bit people can easily steal social logins too.

**Comment by philippfrenzel** [comment]
hmm, understand your worries... - I don't have a solution to that issue on a quick run...:/ Sorry!

**Comment by dmeroff** [comment]
I don't think this will be added in the near future.

**Comment by etopian** [comment]
If I add it can I do a p/r and expect it to be merged?

**Comment by dmeroff** [comment]
Yes, I think so. Could you please create new issue, in which you will describe what you want to achieve and how are going to implement this within yii2-user? So we can discuss it.

**Comment by etopian** [comment]
great. will do as soon as i am ready to implement after studying the module.
