### ISSUE TITLE
Trying to get property of non-object in yii2

### ISSUE THREAD

**Issue by Kakengi** [dektrium/yii2-user#815]
When am trying logging out user in my app it gives me this error Trying to get property of non-object 
Please Help

**Comment by vladyslavstartsev** [comment]
that's because you're trying to get property of user, but there is no user object for you if your are guest

**Comment by dmeroff** [comment]
You need to give us more information on how to reproduce this issue, otherwise there is nothing we can do. Please read CONTRIBUTING.md file for more information about creating bug reports. Thanks!

**Comment by Kakengi** [comment]
Aky let me share codes am using admin lte theme but a tried to modify logout button inorder user clicks the system will log him/her out.Codes are this is header.php



<?php
use yii\helpers\Html;

/* @var $this \yii\web\View */
/* @var $content string */
?>

<header class="main-header">

    <?= Html::a('<span class="logo-mini">HRMS</span><span class="logo-lg">' . Yii::$app->name . '</span>', Yii::$app->homeUrl, ['class' => 'logo']) ?>

    <nav class="navbar navbar-static-top" role="navigation">
        

        <div class="navbar-custom-menu">

            <ul class="nav navbar-nav">

                <li class="dropdown user user-menu">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                        
                        <span class="hidden-xs"><?php echo "Logout:",( Yii::$app->user->identity->username) ; ?></span>
                    </a>
                    <ul class="dropdown-menu">
                        
                        
                        
                        <li class="user-footer">

                            
                                <?= Html::a(
                                    'Sign out',
                                    ['/site/logout'],
                                    ['data-method' => 'post', 'class' => 'btn btn-default btn-flat']
                                ) ?>
                            
                        </li>
                    </ul>
                </li>

            </ul>
        </div>
    </nav>
</header>
