### ISSUE TITLE
Why are tables designed in such an unwieldy way?

### ISSUE THREAD

**Issue by Suseika** [dektrium/yii2-user#818]
- Why such strange type on `user.id`? Why `INT(11) NOT NULL` instead of the usual `INT(10) NOT NULL UNSIGNED` (a non-unique id is a very strange decision)? That id is not even unique for some reason. 
- Why no surrogate `id` public key field for the other tables?

This all makes it quite difficult to build upon the existing code, e.g. referencing the tables from application's custom tables via public key.

**Comment by dmeroff** [comment]
`user.id` is a primary key. It is unique by design. I don't really understand what are you talking about.
`user.id` is also signed just because yii2-user migrations use yii2 schema builder which defines primary key as signed integer.
