### ISSUE TITLE
Yii2-user

### ISSUE THREAD

**Issue by dmeroff** [dektrium/yii2-user#819]
Hey guys!

I'm really sorry for being inactive for so a long time. I must be honest, I've lost all my motivation on supporting this project last year, and I also had very little time to work on it. However that's not the way this project should be developed. I'm going to work hard and maintain it without being inactive.

In the next few days I'm going to review all issues and pull requests, and answer all the questions on https://dektrium.com.

Now I have a lot of free time now to work on the project, I also have a lot of ideas how to improve it. Dektrium project also will get a few new extensions in the next months.

**Comment by thyseus** [comment]
May i ask here for an estimation on a timeline for the yii2-profile split? I may, at least, would like to separate the profile features out of the yii2-user module if you are too busy to handle this at the moment.

**Comment by philippfrenzel** [comment]
Hey, great to hear you are back! Some way to support you?

**Comment by dmeroff** [comment]
@thyseus firstly I need to release 1.0.0-alpha, it is going to be somewhere on the next week (approximately on February 1st). It will come with huge refactoring, and will break a lot of BC, you can check out dev branch to see the progress. After that I will start working on Yii2-profile split.

@philippfrenzel sending a PR always helps ;)
