### ISSUE TITLE
Unable to translate email subject in main config with Yii::t() function

### ISSUE THREAD

**Issue by MichielTG** [dektrium/yii2-user#821]
As explained in the 'mailer' option it is possible to change the email subject in the main config. This is possible however it doesn't seem to work with the build in Yii::t() function.
I also tried to get the information from a static function outside the main config, but this doesn't work either. 

So I was wondering if it this message is limited to just one language. 

Thank you for your reply.

**Comment by dmeroff** [comment]
I've answered [here](https://dektrium.com/d/10-mail-subjects-on-different-languages)
