### ISSUE TITLE
Implement findIdentityByAccessToken

### ISSUE THREAD

**Issue by jkmssoft** [dektrium/yii2-user#822]
### What steps will reproduce the problem?
Login with QueryParamAuth does not work.
```php
// add to your "api controller"
use yii\filters\auth\QueryParamAuth;
        $behaviors['authenticator'] = [
            'class' => QueryParamAuth::className(),
        ];
```
### What is the expected result?
Login with QueryParamAuth.
### What do you get instead?
NotSupportedException: Method is not implemented.
### Additional info
Implement the method.
Additional attribute in user table required or using auth_key?

```php
    /** @inheritdoc */
    public static function findIdentityByAccessToken($token, $type = null)
    {
        $user = static::findOne(['access_token' => $token]);
        if (!$user->isBlocked && $user->isConfirmed) {
            return $user;
        }
        return null;
    }
```

| Q                 | A
| ----------------- | ---
| Yii2 version      | 2.0.10
| Yii2-user version | 0.9.9
| PHP version       | 7.0

**Comment by dmeroff** [comment]
I don't think we should implement this method in Yii2-user. The way how identity is searched may vary in different projects.
