### ISSUE TITLE
RegistrationController - actionConnect

### ISSUE THREAD

**Issue by trinkity** [dektrium/yii2-user#824]
### What steps will reproduce the problem?
set /var/www/project1/backend/runtime/mail/ to owner: "user", without www-data have permission to write
### What is the expected result?
message that there is a problem

### What do you get instead?
nothing... button not go next. no message and page is locked in self page
 
### Additional info
When $user->create() in RegistrationController.php function actionConnect CALL \daktrium\user\models\User function create()
$this->mailer->sendWelcomeMessage($this, null, true);
go in exception
This exception is lost. only \Yii::warning($e->getMessage()); 
Suggest message as "Internal Error. Contact Administrator"

| Q                 | A
| ----------------- | ---
| Yii2 version      |  last
| Yii2-user version | ?
| PHP version       |  7.0.8-3ubuntu3

**Comment by dmeroff** [comment]
This problem has been fixed in the master branch. Exception now are rethrown after failed registration.
This fix will be included in version `0.9.10` which will be released tomorrow.
