### ISSUE TITLE
inconsistent use of last_login and last_login_at

### ISSUE THREAD

**Issue by mfrdm** [dektrium/yii2-user#836]
### What steps will reproduce the problem?
update  : branch master, migration : m160929_103127_add_last_login_at_to_user_table.
try login, error : Setting unknown property: dektrium\user\models\User::last_login_at
### What is the expected result?
consistent property last_login_at
### Additional info

| Q                 | A
| ----------------- | ---
| Yii2 version      | 2.0.10
| Yii2-user version | master 26a4de6
| PHP version       | 7.0.0

**Comment by dixonsatit** [comment]
Migrations is update "m160929_103127_add_last_login_at_to_user_table" try

php yii migrate/up --migrationPath=@vendor/dektrium/yii2-user/migrations

**Comment by mfrdm** [comment]
sorry, not the process of migration. But inconsisten last_login and last_login_at
models/User.php :
@property integer $last_login

migrations/m160929_103127_add_last_login_at_to_user_table.php :
$this->addColumn('{{%user}}', 'last_login_at', $this->integer());

models/LoginForm.php :
if ($this->validate()) {
            $this->user->updateAttributes(['last_login_at' => time()]);

**Comment by mfrdm** [comment]
Okay I will try your suggestion, thanks

**Comment by mfrdm** [comment]
Ah, I forgot to erase the cache db schema. 
running perfectly.

Thanks

**Comment by alvaropineda** [comment]
When i try php yii migrate/up --migrationPath=@vendor/dektrium/yii2-user/migrations

it shows all migrations:

Total 12 new migrations to be applied:
        m140209_132017_init
        m140403_174025_create_account_table
        m140504_113157_update_tables
        m140504_130429_create_token_table
        m140830_171933_fix_ip_field
        m140830_172703_change_account_table_name
        m141222_110026_update_ip_field
        m141222_135246_alter_username_length
        m150614_103145_update_social_account_table
        m150623_212711_fix_username_notnull
        m151218_234654_add_timezone_to_profile
        m160929_103127_add_last_login_at_to_user_table

Apply the above migrations? (yes|no) [no]:

but it fails with the first one exiting with:

*** applying m140209_132017_init
    > create table {{%user}} ...Error: SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'user' already exists

**Comment by mfrdm** [comment]
My problem is because forgot to clear the cache in the database schema, everything worked perfectly after cleared. Models/user.php @property integer last_login will only provide notification error / warning in IDE like PhpStorm, should @property integer last_login_at.

May i close this issue? or there are those who want to help to solve the problems of alfaropineda

**Comment by AntonYu** [comment]
https://github.com/dektrium/yii2-user/blob/master/models/LoginForm.php#L140
and
https://github.com/dektrium/yii2-user/blob/master/models/User.php#L46

It seems that property in User model need to be fixed.

**Comment by thyseus** [comment]
https://github.com/dektrium/yii2-user/pull/845

**Comment by ejoful** [comment]
ALTER TABLE `user` ADD `last_login_at` INT(11) NOT NULL AFTER `flags`;
