### ISSUE TITLE
Running yii2 advanced app tests results in error

### ISSUE THREAD

**Issue by rrhyne** [dektrium/yii2-user#844]
### What steps will reproduce the problem?

Running tests for my app with:

codecept run -c frontend -v

Results in errors for each test reading "  [yii\base\InvalidParamException] Invalid path alias: @dektrium/user/views".

I have overridden views in my main configuration as so:

        'view' => [
          'theme' => [
              'pathMap' => [
                  '@dektrium/user/views' => '@app/views/user'
              ],
          ],
        ],

If I comment out the path map override, the tests run without producing this error.

### What is the expected result?

The tests should run properly.

### What do you get instead?

[yii\base\InvalidParamException] Invalid path alias: @dektrium/user/views

### Additional info

| Q                 | A
| ----------------- | ---
| Yii2 version      | 2.0.10 - 
| Yii2-user version | 0.9.12
| PHP version       |

**Comment by rrhyne** [comment]
This turned out to be configuration issues with the yii2 advanced template. Once I solved those, I was able to run tests with the overridden ui.

**Comment by mateuszmalek** [comment]
@rrhyne Could you tell me what changes have you made to make it working?
