### ISSUE TITLE
Same message for confirmed and not confirmed  

### ISSUE THREAD

**Issue by bscheshirwork** [dektrium/yii2-user#849]
### What steps will reproduce the problem?
click "resend" 
### What is the expected result?
email in my inbox
### What do you get instead?

php-code/vendor/dektrium/yii2-user/models/ResendForm.php

send if not confirmed
```
        if ($user instanceof User && !$user->isConfirmed) {
...
            $this->mailer->sendConfirmationMessage($user, $token);
        }
```
and show a message, anyone. 
```
        \Yii::$app->session->setFlash(
            'info',
            \Yii::t(
                'user',
                'A message has been sent to your email address. It contains a confirmation link that you must click to complete registration.'
            )
        );
```

**Comment by dmeroff** [comment]
This is working as intended, see #725

**Comment by bscheshirwork** [comment]
1. User already confirmed ($user->isConfirmed is true). Has been created from console command (for example).
2. User use resend form.
3. User have flash message "A message has been sent to your email address. It contains a confirmation link that you must click to complete registration."
4. User check your email.
5. User reaction: "WTF???"
