### ISSUE TITLE
Error on update

### ISSUE THREAD

**Issue by diamardan** [dektrium/yii2-user#853]
### What steps will reproduce the problem?
use composer update
### What is the expected result?
Load Login screen
### What do you get instead?
Error Trying get property of non-object
### Additional info
<strong><?= Yii::$app->user->identity->profile->name ;?></strong>
| Q                 | A
i have a login module who uses Dektrium user, it was working fine with Yii2-user 0.9.5, but, after composer update, i can´t get access to login, it shows "Trying to get property of non-object". and if i use an old dektrium folder it works again, i don´t really know if this is an easy problem.

| ----------------- | ---
| Yii2 version      | Yii 2.0.10
| Yii2-user version | 0.9.12
| PHP version       | PHP 5.6.28

**Comment by dmeroff** [comment]
Run the migration command, there is a new fields in user table.
