### ISSUE TITLE
Putting dollar sign in password trough console truncates it

### ISSUE THREAD

**Issue by vincent-ferotin** [dektrium/yii2-user#859]
### What steps will reproduce the problem?

Setting password through command line, with `yii user/password`, truncates it if it contains a dollar sign (`$`):  
`yii user/password <user> "head$tail"`

### What is the expected result?

The expected result would be setting new password for <user> to `head$tail`.

### What do you get instead?

New password for <user> is to `head`.

### Additional info

| Q                 | A
| ----------------- | ---
| Yii2 version      | 2.0.10
| Yii2-user version | 0.9.9.0
| PHP version       | 5.6.29

**Comment by dmeroff** [comment]
That's not yii2-user issue, that is just how bash works. You should either use `'` instead of `"`, or escape $ sign: `\$`
http://unix.stackexchange.com/a/162477

**Comment by vincent-ferotin** [comment]
Oh, sorry for missing that and creating such ticket! Thanks for the link.
