### ISSUE TITLE
Invalid path alias: @dektrium/user/views when testing

### ISSUE THREAD

**Issue by ferllings** [dektrium/yii2-user#874]
Hello,

I'm trying to use codeception for functional testing, in my yii2-advanced-app (like described here https://github.com/yiisoft/yii2-app-advanced/blob/master/docs/guide/start-testing.md)

The testing works fine with no dependencies, but when I add yii2-user, it doesn't seems to load the module bootstrap settings

```
yii\base\InvalidParamException: Invalid path alias: @dektrium/user/views in /app/vendor/yiisoft/yii2/BaseYii.php:152
```
The module is declared in config/main.php

```
<?php
$params = array_merge(
require(__DIR__ . '/../../common/config/params.php'),
require(__DIR__ . '/../../common/config/params-local.php'),
require(__DIR__ . '/params.php'),
require(__DIR__ . '/params-local.php')
);

return [
  'modules' => [
    'user' => [
        'class' => 'dektrium\user\Module',
...
```

And loaded from config/test.php:
```
<?php
return yii\helpers\ArrayHelper::merge(
  require(__DIR__ . '/main.php'),
...
```

Any idea?

**Comment by ferllings** [comment]
I fixed it, with updating the various config file

**Comment by mateuszmalek** [comment]
@ferllings Could you tell me what do you actually changed in your config file to get it working?

**Comment by ferllings** [comment]
@mateuszmalek I'm not exactly sure what fixed it: I generated a new yii advanced app, and I did a diff on all the config files

**Comment by cornernote** [comment]
I managed to trigger this same error, the stack started with "An Error occurred while handling another error".  Also `YII_DEBUG=0` so that it tries to render an error page using your site's template.  Hope this helps.
