### ISSUE TITLE
im trying to run this command on composer to install dektrium/yii2-user on  yii2 basic framework

### ISSUE THREAD

**Issue by akhiltanveer** [dektrium/yii2-user#906]
**#im trying to run this command on composer to install dektrium/yii2-user on  yii2 basic framework**
https://github.com/dektrium/yii2-user/blob/master/docs/getting-started.md

### i followed steps from above document
first step went well
in the second step
i had to paste below code in config file
'modules' => [
    'user' => [
        'class' => 'dektrium\user\Module',
    ],
],

i pasted this in the config file
my config file is 
web.php
```
<?php

$params = require(__DIR__ . '/params.php');

$config = [
    'id' => 'basic',
    'basePath' => dirname(__DIR__),
    'bootstrap' => ['log'],
    'components' => [
        'request' => [
            // !!! insert a secret key in the following (if it is empty) - this is required by cookie validation
            'cookieValidationKey' => 'dansjdsdam',
        ],
        'cache' => [
            'class' => 'yii\caching\FileCache',
        ],
        'user' => [
            'identityClass' => 'app\models\User',
            'enableAutoLogin' => true,
        ],
        'errorHandler' => [
            'errorAction' => 'site/error',
        ],
        'mailer' => [
            'class' => 'yii\swiftmailer\Mailer',
            // send all mails to a file by default. You have to set
            // 'useFileTransport' to false and configure a transport
            // for the mailer to send real emails.
            'useFileTransport' => true,
        ],
        'log' => [
            'traceLevel' => YII_DEBUG ? 3 : 0,
            'targets' => [
                [
                    'class' => 'yii\log\FileTarget',
                    'levels' => ['error', 'warning'],
                ],
            ],
		
        ],
		
		'controllerMap'       => [
    'migrate' => [
        'class' => 'dmstr\console\controllers\MigrateController'
								 ],
				 ],

				 
	'modules' => [
			'user' => [
			'class' => 'dektrium\user\Module',
					  ],
				 ],
				 
				 
        'db' => require(__DIR__ . '/db.php'),
        /*
        'urlManager' => [
            'enablePrettyUrl' => true,
            'showScriptName' => false,
            'rules' => [
            ],
        ],
        */
    ],
    'params' => $params,
 
];


if (YII_ENV_DEV) {
    // configuration adjustments for 'dev' environment
    $config['bootstrap'][] = 'debug';
    $config['modules']['debug'] = [
        'class' => 'yii\debug\Module',
        // uncomment the following to add your IP if you are not connecting from localhost.
        //'allowedIPs' => ['127.0.0.1', '::1'],
    ];

    $config['bootstrap'][] = 'gii';
    $config['modules']['gii'] = [
        'class' => 'yii\gii\Module',
        // uncomment the following to add your IP if you are not connecting from localhost.
        //'allowedIPs' => ['127.0.0.1', '::1'],
    ];
}

return $config;

```

## iam on windows 7
yii2 framework latest version

when i follow the third step

php yii migrate/up --migrationPath=@vendor/dektrium/yii2-user/migrations
# 
 i get the following error in composer

C:\xampp\htdocs\isa-usa2>php yii migrate
Exception 'yii\base\InvalidConfigException' with message 'Migration failed.
ctory specified in migrationPath doesn't exist: @app/migrations'

in C:\xampp\htdocs\isa-usa2\vendor\yiisoft\yii2\console\controllers\BaseMig
ontroller.php:106

Stack trace:
#0 C:\xampp\htdocs\isa-usa2\vendor\yiisoft\yii2\console\controllers\Migrate
oller.php(168): yii\console\controllers\BaseMigrateController->beforeAction
ct(yii\base\InlineAction))
#1 C:\xampp\htdocs\isa-usa2\vendor\yiisoft\yii2\base\Controller.php(154): y
nsole\controllers\MigrateController->beforeAction(Object(yii\base\InlineAct

#2 C:\xampp\htdocs\isa-usa2\vendor\yiisoft\yii2\console\Controller.php(128)
\base\Controller->runAction('', Array)
#3 C:\xampp\htdocs\isa-usa2\vendor\yiisoft\yii2\base\Module.php(523): yii\c
e\Controller->runAction('', Array)
#4 C:\xampp\htdocs\isa-usa2\vendor\yiisoft\yii2\console\Application.php(180
i\base\Module->runAction('migrate', Array)
#5 C:\xampp\htdocs\isa-usa2\vendor\yiisoft\yii2\console\Application.php(147
i\console\Application->runAction('migrate', Array)
#6 C:\xampp\htdocs\isa-usa2\vendor\yiisoft\yii2\base\Application.php(380):
onsole\Application->handleRequest(Object(yii\console\Request))
#7 C:\xampp\htdocs\isa-usa2\yii(20): yii\base\Application->run()
#8 {main}

any help in solving this is appreciated thank you

**Comment by akhiltanveer** [comment]
quick update it worked the path was wrong

now stuck at this line


PHP Fatal error:  Class 'dektrium\user\migrations\Migration' not found in C:\xam
pp\htdocs\isa-usa2\vendor\yiisoft\vendor\dektrium\yii2-user\migrations\m140209_1
32017_init.php on line 17

**Comment by akhiltanveer** [comment]
somebody please help

C:\xampp\htdocs\isa-usa2>php yii migrate/up --migrationPath=@vendor/yiisoft/vend
or/dektrium/yii2-user/migrations
Yii Migration Tool (based on Yii v2.0.11)

Total 12 new migrations to be applied:
        m140209_132017_init
        m140403_174025_create_account_table
        m140504_113157_update_tables
        m140504_130429_create_token_table
        m140830_171933_fix_ip_field
        m140830_172703_change_account_table_name
        m141222_110026_update_ip_field
        m141222_135246_alter_username_length
        m150614_103145_update_social_account_table
        m150623_212711_fix_username_notnull
        m151218_234654_add_timezone_to_profile
        m160929_103127_add_last_login_at_to_user_table

Apply the above migrations? (yes|no) [no]:yes
*** applying m140209_132017_init
Exception 'ParseError' with message 'syntax error, unexpected '-', expecting ','
 or ';''

in C:\xampp\htdocs\isa-usa2\vendor\yiisoft\vendor\dektrium\yii2-user\migrations\
m140209_132017_init.php:12

Stack trace:
#0 C:\xampp\htdocs\isa-usa2\vendor\yiisoft\yii2\console\controllers\BaseMigrateC
ontroller.php(653): yii\console\controllers\MigrateController->createMigration('
m140209_132017_...')
#1 C:\xampp\htdocs\isa-usa2\vendor\yiisoft\yii2\console\controllers\BaseMigrateC
ontroller.php(166): yii\console\controllers\BaseMigrateController->migrateUp('m1
40209_132017_...')
#2 [internal function]: yii\console\controllers\BaseMigrateController->actionUp(
0)
#3 C:\xampp\htdocs\isa-usa2\vendor\yiisoft\yii2\base\InlineAction.php(57): call_
user_func_array(Array, Array)
#4 C:\xampp\htdocs\isa-usa2\vendor\yiisoft\yii2\base\Controller.php(156): yii\ba
se\InlineAction->runWithParams(Array)
#5 C:\xampp\htdocs\isa-usa2\vendor\yiisoft\yii2\console\Controller.php(128): yii
\base\Controller->runAction('up', Array)
#6 C:\xampp\htdocs\isa-usa2\vendor\yiisoft\yii2\base\Module.php(523): yii\consol
e\Controller->runAction('up', Array)
#7 C:\xampp\htdocs\isa-usa2\vendor\yiisoft\yii2\console\Application.php(180): yi
i\base\Module->runAction('migrate/up', Array)
#8 C:\xampp\htdocs\isa-usa2\vendor\yiisoft\yii2\console\Application.php(147): yi
i\console\Application->runAction('migrate/up', Array)
#9 C:\xampp\htdocs\isa-usa2\vendor\yiisoft\yii2\base\Application.php(380): yii\c
onsole\Application->handleRequest(Object(yii\console\Request))
#10 C:\xampp\htdocs\isa-usa2\yii(20): yii\base\Application->run()
#11 {main}

C:\xampp\htdocs\isa-usa2>

**Comment by bscheshirwork** [comment]
I think problem here
```
		'controllerMap'       => [
    'migrate' => [
        'class' => 'dmstr\console\controllers\MigrateController'
								 ],
				 ],
```

**Comment by akhiltanveer** [comment]
worked like charm thank you
