### ISSUE TITLE
Include username & url in welcome email

### ISSUE THREAD

**Issue by TonisOrmisson** [dektrium/yii2-user#919]
For any sites disabling user self-registrations it would be useful to have the username and site url also in the welcome e-mail.

**Comment by thyseus** [comment]
You can override the outgoing e-mails by providing an mail/ directory in your application. See https://github.com/dektrium/yii2-user/blob/master/docs/overriding-views.md - explanation is valid for views and email templates.

**Comment by TonisOrmisson** [comment]
Thanks. 
Yes I know about overriding things. 

I was just using the module out of the box for a simple application for which I really did not want to overcomplicate things in starting to customize the user module. It just seemed like a good idea to include the login URL and username in the welcome e-mail by default. 

It is essential to have that if you use the module with registration disallowed. And it really does not seem very much downsides for the registration allowed version. Or? It would just be better usable out of the box in a more variety of use cases. Just a suggestion to offer more convenience for some cases. 

I would have done a pull request but did not want to do it without getting any feedback first.

**Comment by thyseus** [comment]
Ok, i agree that providing the username and e-mail does make sense in the activation e-mail. It should be inside the default template.

**Comment by SamMousa** [comment]
@TonisOrmisson would you care to submit a PR?
Please direct it here: https://github.com/dabilite/yii2-user
