### ISSUE TITLE
syntax error, unexpected '::' (T_PAAMAYIM_NEKUDOTAYIM)

### ISSUE THREAD

**Issue by cerqueiranews** [dektrium/yii2-user#921]
### What steps will reproduce the problem?
Access user/admin/index
### What is the expected result?
List user
### What do you get instead?
Error
### Additional info
Error on line 96 on dektrium\user\models\UserSearch
I corrected by changing 
$table_name = $query->modelClass::tableName(); 
to 
$model = $query->modelClass;
$table_name = $model::tableName();

| Q                 | A
| ----------------- | ---
| Yii2 version      | 2.0.12
| Yii2-user version | 0.9
| PHP version       |  5.6

**Comment by alvaropineda** [comment]
same here

**Comment by thyseus** [comment]
Seems to be my fault. It's introduced here: https://github.com/dektrium/yii2-user/pull/905/files#diff-6d2e196a503baa701d108fb03201a729R99

Fix: https://github.com/dektrium/yii2-user/compare/master...thyseus:patch-2

@thiagotalma please merge :)

**Comment by diegotejadav** [comment]
@thiagotalma is this commit https://github.com/thyseus/yii2-user/commit/230b28b68e57105d60a4ae42fc9fcc697ad58758 already merged? I need it please!

**Comment by cgernert** [comment]
In my solution I only replaced the double colons with the **_->_** operator (PHP 5 syntax).
#933

**Comment by cgernert** [comment]
Could you please create a pull request

**Comment by thiagotalma** [comment]
Fixed in https://github.com/dektrium/yii2-user/commit/a025d446c6d512ef042d30211107a2f336b86734
Thanks!

**Comment by devquora** [comment]
[T_PAAMAYIM_NEKUDOTAYIM](https://www.onlineinterviewquestions.com/core-php-interview-questions/) is scope resolution operator used as :: (double colon) .Basically, it used to calling static methods/variables of a Class.

Example usage:-		
 $Cache::getConfig($key);

**Comment by wgxh5201** [comment]
php版本5.6，($model::MODEL)::getList($params)，仍然出现unexpected '::' (T_PAAMAYIM_NEKUDOTAYIM)错误，为什么？
