### ISSUE TITLE
Override email template

### ISSUE THREAD

**Issue by yepes** [dektrium/yii2-user#923]
Is it possible to override the email template (content) the same way we do with normal files?

### What steps will reproduce the problem?
Edited yii config file
```
'modules' => [
		'user' => [
			....
			'mailer' => [
                            'viewPath' => '@app/views/user/mail',
                       ]
            ],
]
```
and I have created views/mail/welcome.php

### What is the expected result?
Send the overridden template

### What do you get instead?
View not Found – yii\base\ViewNotFoundException
The view file does not exist: [...]/views/user/mail/layouts/html.php

### Additional info

If i create the template, I get the same with the "text" subdirectory

| Q                 | A
| ----------------- | ---
| Yii2 version      | 2.0.11.2
| Yii2-user version | 0.9.12
| PHP version       | 7.1.1

**Comment by pablonunez-dev** [comment]
You need two files on your mail/layout folder,  one called html.php and other called text.php.

For testing copy that files from vendor\dektrium\yii2-user\views\mail\layouts to your custom mail folder.
