### ISSUE TITLE
Followed this Doc for Profile name field 

### ISSUE THREAD

**Issue by IgnitedCoder** [dektrium/yii2-user#925]
### What steps will reproduce the problem?

https://github.com/dektrium/yii2-user/blob/master/docs/adding-profile-fields-to-registration-form.md

### What is the expected result?

Name field as part of the Registration Form

### What do you get instead?

Exception (Unknown Property) 'yii\base\UnknownPropertyException' with message 'Getting unknown property: dektrium\user\models\RegistrationForm::name' 
in /home/vagrant/Code/app.viewer.com/vendor/yiisoft/yii2/base/Component.php:147

### Additional info

| Q                 | A
| ----------------- | ---
| Yii2 version      | 2.0.5
| Yii2-user version | .9.12
| PHP version       | 5.6

**Comment by IgnitedCoder** [comment]
Solved... Apologies, did not Map the class in config.

**Comment by co2nut** [comment]
May I know how did you map the class in config?

**Comment by junaidcs** [comment]
> May I know how did you map the class in config?

```
'class' => 'dektrium\user\Module',
'modelMap' => [
    'RegistrationForm' => 'app\modules\user\models\RegistrationForm',   
],
```
