### ISSUE TITLE
Typo in update_tables migration

### ISSUE THREAD

**Issue by mattheobjornson** [dektrium/yii2-user#934]
### What steps will reproduce the problem?
yii migrate/down all

### What is the expected result?
Migration succeeds

### What do you get instead?
Exception

``
create unique index {{%user_recovery} on {{%user}} (id, recovery_token) ...Exception 'yii\db\Exception' with message 'SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '{{%user_recovery} (`id`, `recovery_token`)' at line 1
The SQL being executed was: ALTER TABLE `user` ADD UNIQUE INDEX {{%user_recovery} (`id`, `recovery_token`)'
``

### Additional info

| Q                 | A
| ----------------- | ---
| Yii2 version      | 2.0.11.2 / any
| Yii2-user version | master
| PHP version       | 7.0 / any

### Reason/solution
There is a typo in https://github.com/dektrium/yii2-user/blob/master/migrations/m140504_113157_update_tables.php#L56 '{{%user_recovery}' instead of '{{%user_recovery}}', implemented in #767

**Comment by omer-sds** [comment]
+1 for the post I also received the same when i ran migrate/down all

**Comment by pravda1979** [comment]
+1 for the post I also received the same when i ran migrate/down all

**Comment by thiagotalma** [comment]
Fixed!
