### ISSUE TITLE
How to check if user is admin?

### ISSUE THREAD

**Issue by pedroponte** [dektrium/yii2-user#936]
### What steps will reproduce the problem?
E.G. Yii::$app->user->isAdmin
### What is the expected result?
true / false
### What do you get instead?
function not available
### Additional info

| Q                 | A
| ----------------- | ---
| Yii2 version      |
| Yii2-user version |
| PHP version       |

**Comment by septemberboy7** [comment]
I use something like this.

\dektrium\user\models\User::findOne(['id'=> Yii::$app->user->id])->isAdmin

**Comment by myomyintaung512** [comment]
You can use 
```
Yii::$app->user->isGuest; // check if user is guest
Yii::$app->user->identity->isAdmin; // check if user is an admin

```

Duplicate of #201

**Comment by bscheshirwork** [comment]
#986
