### ISSUE TITLE
cant extend controller

### ISSUE THREAD

**Issue by ultra2mh** [dektrium/yii2-user#951]
i extended registrationform controller as below: but i cant access my varible in view ... is my web.php configuration right?

namespace app\controllers;

use app\models\AuthItem;
use dektrium\user\models\RegistrationForm;
use yii\web\NotFoundHttpException;

use dektrium\user\controllers\RegistrationController as BaseRegistrationController;

class RegistrationController extends BaseRegistrationController
{
// my code
}

**my web.php config file** 

    'modules' => [
        'user' => [
            'class' => 'dektrium\user\Module',
            'modelMap' => [
                'RegistrationForm' => 'app\models\RegistrationForm',
            ],
            'controllerMap' => [
                'Registration' => 'app\controllers\RegistrationController'
            ]
        ],
        'setting' => [
            'class' => 'app\modules\settings\Settings',
        ],
    ],

**Comment by buttflattery** [comment]
you need o place your controllers and views inside user folder, which you havent, it should be frontend/controllers/user/RegistrationController
and frontend/views/user/viewname

**Comment by buttflattery** [comment]
in your case it should be app/controllers/user

**Comment by ultra2mh** [comment]
now config file is :  
```
 'controllerMap' => [
                'Registration' => 'app\controllers\user\RegistrationController'
            ]
```
and  i put registrationController inside user folder  with namespace: 
`namespace app\controllers\user;
`
but still i dont have my parametr its not working :(
