### ISSUE TITLE
Cannot use yii\base\Object as Object because 'Object' is a special class name

### ISSUE THREAD

**Issue by cyberaleks** [dektrium/yii2-user#984]
The class Finder extends from Object. That is not allowed in YII 2.0.13 and an error is thrown.

> Class Object has been replaced by [[BaseObject]] in version 2.0.13 because `object` has become a reserved word which can not be used as class name in PHP 7.2.

**Comment by bscheshirwork** [comment]
#992

**Comment by kshitizsingh** [comment]
i'm recieving the same error

**Comment by thiagotalma** [comment]
Fixed by https://github.com/dektrium/yii2-user/commit/ad757cd086e395ace15a04b17c635bb90d8625d2
