### ISSUE TITLE
Missed curly bracket in the update_tables migration 

### ISSUE THREAD

**Issue by petartonchev** [dektrium/yii2-user#985]
There is a missing curly bracket on line 56 where it's written `'{{%user_recovery}'` it should be `'{{%user_recovery}}'` instead.
https://github.com/dektrium/yii2-user/blob/73e1c3b247b276b8b0071f4888cffabc15443d04/migrations/m140504_113157_update_tables.php#L56

**Comment by thiagotalma** [comment]
Already fixed.
Thanks!
