### ISSUE TITLE
PHP 7.2 compatibility

### ISSUE THREAD

**Issue by marty-macfly** [dektrium/yii2-user#992]
### What steps will reproduce the problem?

Use php 7.2

### What is the expected result?

Yii-user should work

### What do you get instead?

Yii-user not working with the following error:

```php
 PHP Fatal error:  Cannot use yii\base\Object as Object because 'Object' is a special class name in /var/www/html/vendor/dektrium/yii2-user/Finder.php on line 17
PHP Compile Error 'yii\base\ErrorException' with message 'Cannot use yii\base\Object as Object because 'Object' is a special class name
```

### Additional info

| Q                 | A
| ----------------- | ---
| Yii2 version      |  2.0.13
| Yii2-user version | 0.9.12
| PHP version       |  7.2.0

**Comment by bscheshirwork** [comment]
I create PR.

**Comment by StalkAlex** [comment]
15 days last... Is anybody going to merge those fixes for 7.2?

**Comment by thiagotalma** [comment]
Fixed by https://github.com/dektrium/yii2-user/commit/ad757cd086e395ace15a04b17c635bb90d8625d2

**Comment by StalkAlex** [comment]
@thiagotalma , it's not a fix. You just lowered php version, now it won't install at all. And this issue was about working on php 7.2, not about making versioning more correct.

**Comment by thiagotalma** [comment]
@StalkAlex What do you suggest to solve the problem?

**Comment by StalkAlex** [comment]
@thiagotalma problem in "object" word, it became reserved, so I propose to inherit from BaseObject instead of Object as yii team described in change log where it used in code.

**Comment by thiagotalma** [comment]
check now

**Comment by wzh190015** [comment]
update?

**Comment by thiagotalma** [comment]
Have you found a problem?

**Comment by JonasAeschlimann** [comment]
I have replaced "use yii\base\Object" with "use yii\base\BaseObject" direct in the vendor. I am sure its not right but it is working... What would be the better way?

**Comment by subcat** [comment]
Hi
Im working on a new vps server with installed php 7.2.17-0ubuntu0.18.04.1
Im running into a similar error when trying to run `php yii migrate`
could you please try to explain how to overcome this? Im not a developer.

php yii migrate PHP Fatal error: Cannot use yii\base\Object as Object because 'Object' is a special class name in /var/www/html/vendor/dektrium/yii2-user/Finder.php on line 17
Error: Cannot use yii\base\Object as Object because 'Object' is a special class name

**Comment by evecute** [comment]
> I have replaced "use yii\base\Object" with "use yii\base\BaseObject" direct in the vendor. I am sure its not right but it is working... What would be the better way?
> 
> and of course -> class Object extends BaseObject

when i do this, i cannot create permission it shows "SyntaxError: JSON.parse: unexpected non-whitespace character after JSON data at line 1 column 3 of the JSON data" can anyone help? with php 7.2 of course
