### ISSUE TITLE
Error in enableUnconfirmedLogin

### ISSUE THREAD

**Issue by nayoma** [dektrium/yii2-user#995]
### What steps will reproduce the problem?
I config enableUnconfirmedLogin in config file. but, I got error.
"Setting unknown property: dektrium\\user\\Module::enableUnconfirmedLogin "
### Additional info
#
<img width="675" alt="capture" src="https://user-images.githubusercontent.com/29333716/33873792-58296018-df42-11e7-9d27-adce27fd5524.PNG">

| Q                 | A
| ----------------- | ---
| Yii2 version      |
| Yii2-user version |
| PHP version       |

**Comment by thiagotalma** [comment]
Please, check your config.
